### ISSUE TITLE
RankLib install

### ISSUE THREAD

**Issue by sstults** [o19s/elasticsearch-learning-to-rank#1]
The documentation about installing the RankLib jar talks about using maven, but the maven command won't work without a pom. More instructions on installing the jar would be helpful.

**Comment by BeifeiZhou** [comment]
Hi guys, I can not build the project with gradle, and it gives this error: 

FAILURE: Build failed with an exception.

* Where:
Build file '/home/bzhou/softwares/elasticsearchLtrPlugin/elasticsearch-learning-to-rank/build.gradle' line: 18

* What went wrong:
A problem occurred evaluating root project 'ltr-query'.
> Failed to apply plugin [id 'carrotsearch.randomized-testing']
   > Could not create task of type 'RandomizedTestingTask'.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED


Do you have any suggestions?

Many thanks,
Beifei

**Comment by gibrown** [comment]
Here's also how to build it and install:

```
git clone git@github.com:o19s/RankyMcRankFace.git
cd RankyMcRankFace
mvn package
mvn install:install-file "-DgroupId=com.o19s" "-DartifactId=RankLibPlus" "-Dversion=0.1" "-Dpackaging=jar" "-Dfile=./target/RankLibPlus-0.1.0.jar"
```

**Comment by epugh** [comment]
I managed to publish the 0.1.0 version of the RankyMcRankface on Github (https://github.com/o19s/RankyMcRankFace/releases) and created a release on Bintray.   See https://github.com/o19s/elasticsearch-learning-to-rank/pull/21 for more...

**Comment by epugh** [comment]
I believe, with the changes made, that this issue can be closed!
