### ISSUE TITLE
What happens when mustache param is missing?

### ISSUE THREAD

**Issue by softwaredoug** [o19s/elasticsearch-learning-to-rank#101]
TODO to investigate

**Comment by nomoa** [comment]
For now an error is thrown, perhaps it could make sense to have a way to set parameters at multiple level : 
- define a default value in the feature it self
- override default values in the featureset
- override default values in the model
note that I haven't thought about all the consequences: will this be error-prone regarding logging/training?

**Comment by softwaredoug** [comment]
I think an error is preferred for now, thanks for investigating!
