### ISSUE TITLE
no [query] registered for [query]

### ISSUE THREAD

**Issue by NarimanN2** [o19s/elasticsearch-learning-to-rank#102]
Hi, I am doing everything the documentation said for adding a featureset, but when I was adding my first feature, validation failed and I got theses errors: 

> Cannot create query while parsing feature [title_query]

> no [query] registered for [query]

here is my featureset: 
`{
   "validation": {
     "params": {
         "keywords": "rambo"
     },
     "index": "movies"
    },
    "featureset": {
        "name": "movie_features",
        "features": [
            {
                "name": "title_query",
                "params": [
                    "keywords"
                ],
                "template_language": "mustache",
                "template": {
                    "query": {
                        "match": {
                            "title": "{{keywords}}"
                        }
                    }
                }
            }
        ]
    }
}`

**Comment by nomoa** [comment]
@NarimanN2 I think it's a bug in the documentation, the query should not be nested inside a `query` block but be directly put under `template`, the `featureset` should look like:
```json
{
  "featureset": {
    "name": "movie_features",
    "features": [
      {
        "name": "title_query",
        "params": [
          "keywords"
        ],
        "template_language": "mustache",
        "template": {
          "match": {
            "title": "{{keywords}}"
          }
        }
      }
    ]
  },
  "validation": {
    "params": {
      "keywords": "rambo"
    },
    "index": "movies"
  }
}
```
