### ISSUE TITLE
Error in DenseDataPoint::setFeatureValue(): feature (id=95) not found.

### ISSUE THREAD

**Issue by besson** [o19s/elasticsearch-learning-to-rank#104]
I am getting this error when trying to load a LambdaMART model that does not use all features in my featureset. Describing in more details, I did the following steps:

1. Created a featureset of 371 features
2. Trained a LambdaMART model on Ranklib. This model uses 133 features (not all features of my feature set)
3. Loaded the model (output file generated by Ranklib)
4. Used the model in the sltr query and as a return I got the error `Error in DenseDataPoint::setFeatureValue(): feature (id=95) not found.`

**Comment by softwaredoug** [comment]
Thanks @besson -- Is there anyway you could create a simpler version that recreates the bug using test data we have access too? Such as the TMDB data set?

Also is there a stacktrace anywhere associated with this?

**Comment by softwaredoug** [comment]
Sweet, thanks. That helps. So it does seem to be an issue with unused features in RankLib models.

**Comment by softwaredoug** [comment]
Can you show me features 1-3 you're using? I've been trying this with 3 simple match queries and haven't been able to recreate thus afr

**Comment by besson** [comment]
Sure. These are the features:

```
"features": [
        {
          "name": "1",
          "params": [
            "keywords"
          ],
          "template_language": "mustache",
          "template": {
            "match": {
              "title": "{{keywords}}"
            }
          }
        },
        {
          "name": "2",
          "params": [
            "keywords"
          ],
          "template_language": "mustache",
          "template": {
            "match": {
              "overview": "{{keywords}}"
            }
          }
        },
        {
          "name": "user_rating",
          "params": [],
          "template_language": "mustache",
          "template": {
            "function_score": {
              "functions": [
                {
                  "field_value_factor": {
                    "field": "user_rating",
                    "missing": 0
                  }
                }
              ],
              "query": {
                "match_all": {}
              }
            }
          }
        }
      ]
```

**Comment by softwaredoug** [comment]
Thanks for your patience @besson and collaborating on this! I have still had trouble, here's a script that I think attempts to perform the steps you mention. Perhaps you could try it out and modify it to recreate your issue https://github.com/o19s/elasticsearch-learning-to-rank/blob/104-hunt-for-bug/demo/do104.py#L83

**Comment by softwaredoug** [comment]
I built a bit of a chaos monkey test and seem to have recreated the bug!

**Comment by softwaredoug** [comment]
When the feature set has many features, but a Ranklib model only uses a few of them, we

- Still run each scorer, as seen [here](https://github.com/o19s/elasticsearch-learning-to-rank/blob/master/src/main/java/com/o19s/es/ltr/query/RankerQuery.java#L262)
- But we rely on the model to tell us how many features are possible, on [this line](https://github.com/o19s/elasticsearch-learning-to-rank/blob/master/src/main/java/com/o19s/es/ltr/ranker/ranklib/RanklibRanker.java#L56)

For Ranklib, we should always construct these vectors based on the number of features in the featureSet, and not rely on the model. And it'd be nice to not score unused features (unclear how common this is outside testing).

@nomoa would this be a problem for the xgboost or other model formats?

**Comment by besson** [comment]
Thanks for the dedication to investigate the problem @softwaredoug 

I have a question, as models were designed to immutable, they have a copy of the
features in the featureSet, right ? When you say you get features count from the model, are you getting those from this copy of featureSet ?

I am asking that, because in our real life case, the model listed, when you request the model from the API, all 371 features although it was using only 133. So, it should work as vector was initialized with size 371, right ?

**Comment by softwaredoug** [comment]
The issue is we parse a Ranklib model, and notice it only uses feature 1, when we should be looking at the associated feature set and seeing it has 1...n features. So when we execute the Lucene queries, we make the false assumption the feature set has only 1 feature. So we get an out-of-bounds error when the feature set scores feature 2.

It's a good catch, as most of us have been using 100% of the features in the feature set, but it's a legitimate use case to only use a subset.

**Comment by softwaredoug** [comment]
This [test](https://github.com/o19s/elasticsearch-learning-to-rank/blob/104-hunt-for-bug/src/test/resources/rest-api-spec/test/fstore/80_search.yaml) recreates the issue

**Comment by softwaredoug** [comment]
I have a fix in [this branch](https://github.com/o19s/elasticsearch-learning-to-rank/tree/104-hunt-for-bug) which seems to be working fine.

I would argue we still have work to do if you have a feature set of 300 features, but your model only uses 100, so we don't execute all 100 features.

I'm having problems with a caching test (at least locally) when I added my integration test so I asked @nomoa to check it out before I can work on merging it

**Comment by besson** [comment]
thank you very much @softwaredoug and @nomoa

**Comment by softwaredoug** [comment]
Sent you a slack invite @besson to our relevancy slack where we discuss this project and other topics :)

**Comment by besson** [comment]
cool! thank you :)

**Comment by lonngxiang** [comment]
> This [test](https://github.com/o19s/elasticsearch-learning-to-rank/blob/104-hunt-for-bug/src/test/resources/rest-api-spec/test/fstore/80_search.yaml) recreates the issue

run do104.py ,there have a problem:

elasticsearch.exceptions.RequestError: RequestError(400, 'search_phase_execution_exception', 'failed to create query: java.lang.NullPointerException: Cannot invoke "com.o19s.es.ltr.feature.store.StoredFeatureSet.optimize()" because the return value of "com.o19s.es.ltr.feature.store.index.IndexFeatureStore.getAndParse(String, java.lang.Class, String)" is null')
