### ISSUE TITLE
Issues in the documentation

### ISSUE THREAD

**Issue by ashrafaaref** [o19s/elasticsearch-learning-to-rank#105]
I would like to share few issues in the documentation we found during our trial to use the plugin:

1- Docs says [here](http://elasticsearch-learning-to-rank.readthedocs.io/en/latest/building-features.html?highlight=delete#create-a-feature-set) to use PUT while the right method is POST

2- when creating the feature set [here](http://elasticsearch-learning-to-rank.readthedocs.io/en/latest/feature-engineering.html#feature-engineering) inside the template you should skip the "query" level and start from the query itself, in this example it should start from "match"

3- POST /_ltr/_clearcache is missing in the docs

4- GET /_ltr/_model/model_name is also missing in the docs

5-  Model names are unique globally across all featuresets

6- In the documentation [here](http://elasticsearch-learning-to-rank.readthedocs.io/en/latest/building-features.html#adding-to-an-existing-feature-set), you forgot  to add in the example that the feature to be added (inside features array) must be wrapped by curly brackets

**Comment by softwaredoug** [comment]
Thanks, some stuff is intentionally missing from the docs (there's a lot of bells and whistles). The docs could be enhanced to include this but we will fix any/all bugs you've found

**Comment by softwaredoug** [comment]
- 1,2, and 6 are fixed (please confirm)
- We should probably add 4 & 5 as an enhancement (will create a PR)
- 3 Perhaps we should create a section on "operational concerns"

**Comment by ashrafaaref** [comment]
I confirm 1,2 and 6 are fixed,Thanks 👍

**Comment by softwaredoug** [comment]
Resolved 4 & 5 in [this section](http://elasticsearch-learning-to-rank.readthedocs.io/en/latest/training-models.html#models-aren-t-owned-by-featuresets). Please review and let me know what you think @ashrafaaref

**Comment by softwaredoug** [comment]
Caching discussed in [advanced functionality](http://elasticsearch-learning-to-rank.readthedocs.io/en/latest/advanced-functionality.html) page. Thanks @ashrafaaref!

**Comment by ashrafaaref** [comment]
Thanks @softwaredoug, that looks great
