### ISSUE TITLE
Delete Feature API is not working properly/completely 

### ISSUE THREAD

**Issue by ashrafaaref** [o19s/elasticsearch-learning-to-rank#106]
when I tried to delete a Feature through the API, feature is deleted and I can't create a feature with the same name again, but still shows up in the list of features in the featureset and in the list of features in the model

**Comment by ebernhardson** [comment]
Sounds like a bug with the feature not being removed from the featureset. Will look into it. The feature not being removed from a model is intentional, the concept there is that models are immutable. When a model is uploaded it copies all the appropriate features into itself and that is an immutable definition. This is to prevent a model from breaking after it has been uploaded.

**Comment by softwaredoug** [comment]
@ebernhardson @nomoa The features are *copied into* the feature set as well, correct?

Also @ashrafaaref I have been trying to recreate not being able to recreate the feature. Do you have a list of REST commands that replicate the issue. I've tried the following:

```
DELETE /_ltr

PUT /_ltr


POST _ltr/_feature/titleSearch
{
    "feature":
      {
        "name": "titleSearch",
        "params": [
          "keywords"
        ],
        "template": {
          "match": {
            "title": "{{keywords}}"
          }
        }
      }
}

GET _ltr/_feature

DELETE _ltr/_feature/titleSearch

GET _ltr/_feature

POST _ltr/_feature/titleSearch
{
    "feature":
      {
        "name": "titleSearch",
        "params": [
          "keywords"
        ],
        "template": {
          "match": {
            "not_title": "{{keywords}}"
          }
        }
      }
}

GET _ltr/_feature
```

**Comment by ebernhardson** [comment]
@softwaredoug My memory may be failing me, but I'm pretty sure features cannot exist outside of a feature store. If the feature store is not provided in the URL (typical use case) then the feature is added to the feature store named `.ltrstore` (named stores are `.ltrstore_myname`).  Internally A feature store is just an elasticsearch index.

I did poke around a bit but didn't come up with any way to reproduce the problem either. For the most part  the feature management stuf calls into the elasticsearch cluster client to perform create/delete/get/etc. operations.

**Comment by ebernhardson** [comment]
So of course it was my mind failing me. We have

top level: Named feature stores. These are elasticsearch indexes. Most people will not use the names, and just use the default (`.ltrstore`)

second level: The index contains three document types: feature, feature set, model.

A feature is an individual elasticsearch query stored as a document
A feature set is a list of features stored as a document
A model is a model definition(ex: json blob for xgboost, string for ranklib) and a list of features stored as a document.


Adding features to a feature store adds the single document.
Adding features to a feature set copies the feature from the single document into the feature set list.
Adding a model to a feature set copies the feature set into a new document for the model, and adds the model data.

Deleting a feature from a feature store does not remove it from a model, as this would break models already uploaded.

Deleting a feature from a feature set is not supported. You can only delete the entire feature set. This was done to prevent mistakes where you build a feature set, collect data to train the model, and then somehow the features in the feature set change (perhaps one of your peers working on feature definitions) before uploading the model and the newly uploaded model is incorrect.

The part that surprised me in this report though is that once the feature was deleted (but still present in the feature set(s) and model(s)), it could not be re-uploaded. I've tested a couple times and while you need to create a new feature set to use it, uploading a feature with the same name as something already used by a model or feature set looks to work just fine.

**Comment by ashrafaaref** [comment]
@ebernhardson sorry for my late reply, we were too busy at the end of last year trying to get our model in good shape, but we couldn't yet :(. 
regarding this issue, I with my team-mate @besson tried for some time to reproduce it but we couldn't remember exactly how we did it, so I think you can close it for now, and if we find it again we will reopen it with the steps to reproduce it. 
Thanks for the help, and the information/ explanations you gave us here

**Comment by softwaredoug** [comment]
@ashrafaaref we did have a related issue #118 we fixed where caches weren't cleared, and perhaps it was related to this.

I'll close for now, feel free to reopen if you can recreate it!
