### ISSUE TITLE
multiple feature stores?

### ISSUE THREAD

**Issue by rpedela** [o19s/elasticsearch-learning-to-rank#107]
The documentation talks about a default feature store and [says](http://elasticsearch-learning-to-rank.readthedocs.io/en/latest/building-features.html):

> For most use cases, you can simply get by with the single, default feature store and never think about feature stores ever again.

That seems to imply that you can have multiple feature stores, but I don't see any documentation for them (I could have missed it). I don't personally have a use case for multiple feature stores, it just seemed weird when I read the docs.

**Comment by nomoa** [comment]
Yes the plugin supports multiple feature stores. All API endpoints can be prefixed with the name of the store `/_ltr/store_name/`.
I think when we discussed about adding it to the documentation we found that it could be misleading as it's rather an advanced use-case and preferred not to go into advanced details.
Now when I read back the doc I agree with you it seems that something is missing.

**Comment by rpedela** [comment]
I think the guide is great overall, and I agree not to pollute the main guide with advanced topics. Would having an advanced topics section help? Also an API reference section would be helpful to me too.

**Comment by softwaredoug** [comment]
@rpedela thanks for the kind feedback. Yes I think an advanced topics section could be called for to resolve this issue

**Comment by softwaredoug** [comment]
Thanks @rpedela . This has been documented in [advanced functionality](http://elasticsearch-learning-to-rank.readthedocs.io/en/latest/advanced-functionality.html)
