### ISSUE TITLE
clickthrough features

### ISSUE THREAD

**Issue by cnvince** [o19s/elasticsearch-learning-to-rank#111]
Hi 

I'm just wondering if clickthrough information can be called as a feature with the plugin. As the information is not indexed, it doesn't seem to be able to call that information. On the other hand, click information is very important for training L2R models. I wonder are there any solutions?

Regards,

**Comment by ebernhardson** [comment]
You didn't give a very complete description of the problem, so i'm going to guess a bit.

You have an index that looks something like:
```
{
  "mappings": {
    "page": {
      "properties": {
        "title": {
          "type": "string"
        },
        "clickthroughs": {
          "type": "object",
          "enabled": false
        }
      }
    }
  }
}```

You send elasticsearch clickthroughs in a map like structure mapping the query to some value:
```
{
  "title": "My awsome post",
  "clickthroughs": {
    "awsome": 4
  }
}
```

You then want some query, to be used as an ltr feature, that returns the value (or a default, like 0) for a particular query:
```
{
  "query": {
    "function_score": {
      "query": {
        "match_all": {}
      },  
      "script_score": {
        "script": {
          "lang": "painless",
          "inline": "def score = params._source.clickthrough.get(params.q); if (score == null) { score = 0; } return score",
          "params": {
            "q": "awsome"
          }
        }
      }
    }
  }
}
```

Is that approximately the question? I can imagine there could be many expansions on this as well, it would be nice if we could apply analysis chains and such to the query so they don't have to be byte-for-byte matches,  but if the data isn't indexed I don't think that's possible. This data could alternatively be integrated into the lucene index more directly, but not very simply.

**Comment by softwaredoug** [comment]
I corresponded with @cnvince over email and I think this helped clear up what he needed, I'll post my response here which I think closes this out

> For the most part, Elasticsearch isn't the infrastructure used to collect user behavioral data that would feedback into search/used to generate training labels. Or at the very least, the serving search system wouldn't collect clickthrough or user information itself as it has very different performance characteristics than read-intensive search. Usually other write-heavy systems are brought to bear to log this data and then this data is used to augment documents in Elasticsearch or used to create judgments and training data.
> 
> For example Cassandra, Snowplow and Google Data Layer often serve this role. 
> 
> Lucidworks Fusion, a product in the Solr world, provides a nice infrastructure for collecting user event data and metadata during search in a separate Solr collection.
> 
> Have you seen this talk I did with my colleague at Snagajob on learning to rank? It may help you. It discusses many practical considerations that have arisen for us
> 
> https://www.youtube.com/watch?v=JqqtWfZQUTU
>

**Comment by cnvince** [comment]
Thanks guys, the reason I asked the question was that previous research on personalization search found that the clickthrough rate of query-document pairs, or other user behaviour based features can help improve ranking effectiveness. So, I wanted to know how the features can be extracted efficiently. Doug has replied me in a separated email to give some ideas.

Regards,
Vincent.

**Comment by rpedela** [comment]
I found this paper recently which shows how to convert click rate to relevance judgments. They also found that relevance judgments based on order and click rates were better than crowd-sourced relevance judgments for e-commerce search.
https://www.researchgate.net/profile/Shubhra_Kanti_Karmaker_Santu/publication/316998625_On_Application_of_Learning_to_Rank_for_E-Commerce_Search/links/59d7cf73458515a5bc1ee532/On-Application-of-Learning-to-Rank-for-E-Commerce-Search.pdf

**Comment by ebernhardson** [comment]
If you're looking to convert implicit user data to labels, we are currently using http://olivier.chapelle.cc/pub/DBN_www2009.pdf which has some open source implementations (https://pypi.python.org/pypi/clickmodels/1.0.2, https://github.com/markovi/PyClick). There is also interesting work in this area from Joachims, although i havn't tried this one: https://arxiv.org/pdf/1608.04468.pdf

**Comment by rpedela** [comment]
@ebernhardson With PyClick, do you call ```click_model.predict_relevance()``` after training the model to get the relevance score, between 0 and 1, for each [query,document] pair and then scale the score to the 0-4 range the LTR models want?

**Comment by ebernhardson** [comment]
@rpedela exactly. I'm using clickmodels rather than pyclick but it's the same basic thing. Currently we use `int(prediction*10)` to get a label between 0 and 9. We are still evaluating what the best method to convert the prediction into a label and how many labels should be used. It's a tough problem so we looked at a sampling of results from a few different methods and decided this looked "good enough".

**Comment by cnvince** [comment]
Yes, DBN is one of the most accepted click model in the research community.

Regards,
Vincent

On 2 Dec 2017, at 4:41 am, ebernhardson <notifications@github.com<mailto:notifications@github.com>> wrote:


If you're looking to convert implicit user data to labels, we are currently using http://olivier.chapelle.cc/pub/DBN_www2009.pdf which has some open source implementations (https://pypi.python.org/pypi/clickmodels/1.0.2, https://github.com/markovi/PyClick). There is also interesting work in this area from Joachims, although i havn't tried this one: https://arxiv.org/pdf/1608.04468.pdf
