### ISSUE TITLE
Problem creating feature: contains unrecognised parameter store

### ISSUE THREAD

**Issue by jettro** [o19s/elasticsearch-learning-to-rank#113]
I am trying to play with the plugin, however in step two, creating a feature set I get an error. I used the following command:

```
POST _ltr/_featureset
{
  "validation": {
     "params": {
         "keywords": "java"
     },
     "index": "blog"
    },
   "featureset": {
        "name": "better_blogs",
        "features": [
            {
                "name": "title_query",
                "params": [
                    "keywords"
                ],
                "template_language": "mustache",
                "template": {
                    "match": {
                        "title": "{{keywords}}"
                    }
                }
            }
        ]
   }
}
```

I get this response:

```
{
  "error": {
    "root_cause": [
      {
        "type": "illegal_argument_exception",
        "reason": "request [/_ltr/_featureset] contains unrecognized parameter: [store]"
      }
    ],
    "type": "illegal_argument_exception",
    "reason": "request [/_ltr/_featureset] contains unrecognized parameter: [store]"
  },
  "status": 400
}
```
I verified the plugin is installed, using the same version as the cluster (5.6.4). Any help on trying to overcome this problem would be nice. Not sure if I am doing something wrong or not. Following a long with the documentation.

Thanks

**Comment by ebernhardson** [comment]
It looks like the documentation is wrong, the test suite runs two paths: `/_ltr/_featureset/{name}` and `/_ltr/{store}/_featureset/{name}`. 

Could you verify it works when specifying the name in the URL? If so i'll update the docs to match.

**Comment by jettro** [comment]
You are right, was looking into the code and got the stack trace, but it seems this is caused by the handlers in the class RestSimpleFeatureStore. I would still have the question why we also need to provide the name of the featureset in the request body than. It does not feel logical

**Comment by nomoa** [comment]
@jettro the name is expected on both `PUT` and `POST`.
Using `PUT` you tell the plugin to enter in create mode (it should fail if the entity already exists). Using `POST` you allow the plugin to update the element.

Now the error reported initially `POST _ltr/_featureset` seems more related to some other endpoints. I'll investigate.

**Comment by jettro** [comment]
Maybe I was not clear. Of course I did try your suggestion and providing the name does help to overcome the issue. So if I provide the name with the POST request there is no error.

**Comment by nomoa** [comment]
I think there are two issues here:
- problem with the documentation
- the error on `POST _ltr/_featureset` is unhelpful and mysterious
