### ISSUE TITLE
security_exception: [ltr:featurestore/data] is unauthorized for user

### ISSUE THREAD

**Issue by IamJeffG** [o19s/elasticsearch-learning-to-rank#116]
I am trying out your plugin for the first time and going through the demo. I can get the `tmdb` index fully populated but am finding problems when it comes to interacting with the plugin's endpoints.  I get a `security_exception` on most endpoints.

```
demo$ python loadFeatures.py 
DELETE http://elastic:changeme@localhost:9200/_ltr
200
PUT http://elastic:changeme@localhost:9200/_ltr
200
POST http://elastic:changeme@localhost:9200/_ltr/_featureset/movie_features
{
  "featureset": {
    "name": "movie_features",
    "features": [
      {
        "name": "1",
        ..snip!..
      }
    ]
  }
}
403
{"error":{"root_cause":[{"type":"security_exception","reason":"action [ltr:featurestore/data] is unauthorized for user [elastic]"}],"type":"security_exception","reason":"action [ltr:featurestore/data] is unauthorized for user [elastic]"},"status":403}
```

I am running on [the base Docker image](https://www.elastic.co/guide/en/elasticsearch/reference/5.6/docker.html) of Elasticsearch version 5.6.4.  The plugin version is `ltr-1.0.0-RC2-es5.6.4.zip`.  I'm running as a user with the `superuser` role as verified by:
```
demo$ curl 'elastic:changeme@localhost:9200/_xpack/security/user/elastic?pretty'
{
  "elastic" : {
    "username" : "elastic",
    "roles" : [
      "superuser"
    ],
    "full_name" : null,
    "email" : null,
    "metadata" : {
      "_reserved" : true
    },
    "enabled" : true
  }
}
```

Oddly enough, some plugin endpoints succeed, such as `DELETE /_ltr` and `PUT /_ltr` and `GET /_ltr/_featureset`.  I also tried both [old and new versions](https://github.com/o19s/elasticsearch-learning-to-rank/commit/67ee90893f819b0ec653d0998753c574a4b65d50) of feature set creation shown in the docs, namely `POST /_ltr/_featureset` and `POST /_ltr/_featureset/movie_features`.

Am I missing some initial set-up around permissions or user accounts?

**Comment by nomoa** [comment]
Thanks for the report, the plugin was never used with X-Pack. It's still unclear to me if it's the plugin fault or configuration issue. I'll try to get some help to figure this out.

**Comment by nomoa** [comment]
Posted a question here: https://discuss.elastic.co/t/plugin-development-custom-transport-actions-and-x-pack-integration/110805

**Comment by nomoa** [comment]
FWIW some endpoints work because they are just REST wrappers and use existing transport actions, the ones that fail seem to be the ones that uses the transport actions declared by the plugin.

**Comment by IamJeffG** [comment]
Good idea about X-Pack being involved. I set up a new cluster without that plugin and your API works fine now!

However we do deploy via Elastic.co's hosted cloud offering, where X-Pack is a required installation, so I'm curious what elastic's discussion board comes up with for eventual deployment.

**Comment by softwaredoug** [comment]
I @IamJeffG I have also fwd'd this issue onto friends at Elastic support. You're not the first one to run into issues with XPack and this plugin. We'll leave this open to see if we get a response on either front.

Thanks! Also feel free to [contact me](http://o19s.com/doug) if you want an invite to the slack channel we use to discuss this project and other relevance topics.

**Comment by james-daily** [comment]
Has there been any movement on this from either side?  We have a working local LTR implementation but are running into this same security issue on ES 5.6.6 on Elastic Cloud.

**Comment by JohnNay** [comment]
I'm also wondering where this stands on the Elastic Cloud and elasticsearch-learning-to-rank
sides, and looking for a solution to deploying elasticsearch-learning-to-rank on Elastic Cloud. Do there need to be changes to one or both of elasticsearch-learning-to-rank/Elastic Cloud?

**Comment by JohnNay** [comment]
ElasticCloud engineers just said it would be up to the LTR plugin to make it compatible with X-Pack Security (which sounds like it needs to expose a way of supplying credentials)

**Comment by nz** [comment]
Hey all, if folks are looking for a managed Elasticsearch hosting solution that supports LTR, feel free to reach out to me and the team at [Bonsai](https://bonsai.io/) ([info@bonsai.io](mailto:info@bonsai.io)). We’ve got some experience hosting LTR clusters, and collaborating closely with the O19S team. Our platform takes a different approach to managing security that’s more compatible with custom plugins like LTR.

**Comment by ebernhardson** [comment]
I spent some time digging into this today, and my brief summary is that, AFAICT, the list of allowable transport actions is hard coded into xpack (at least, for 5.5.2 which i happened to be looking at).  The decompiled bit of code looks roughly like:
```
if (ClusterPrivilege.ACTION_MATCHER.test(action)) {
    if (...) { this.grant() } else { this.denial() }
}
if (!IndexPrivilege.ACTION_MATCHER.test(action)) {
    this.denial()
}
```

The ACTION_MATCHER instances are statically created immutable objects inside xpack, there is no way to add our transport actions into the list of things xpack thinks are authorizable.  If anyone else wants to take a look around the relevant method where authorization finally takes place (and our actions are rejected) is `org.elasticsearch.xpack.security.authz.AuthorizationService.authorize`
