### ISSUE TITLE
python train.py command is throwing error

### ISSUE THREAD

**Issue by AamirNakhwa** [o19s/elasticsearch-learning-to-rank#123]
Hello, actually I am using elastic-search to create a test application just to understand how it works. And I have created indices and also indexed thousands of records. Now I am willing to attach learning-to-rank plugin and I got your demo. 
The problem is I have installed the plugin and it is also showing when I check the installed plugin list on the command line but when I am trying to use it, it says "no [query] registered for [sltr]".
Can you help me to understand what's wrong with it?

![image](https://user-images.githubusercontent.com/35491151/35269097-dfca4fde-004c-11e8-9209-06ea4d76108d.png)

**Comment by nomoa** [comment]
@AamirNakhwa could you specify the version of elasticsearch you are using and also post the link from where you downloaded the ltr plugin?

> I check the installed plugin list on the command line

Could you check the output of `curl localhost:9200/_nodes/_local/plugins?pretty=true` and verify that the ltr plugin is properly listed ?

Possible reasons could be that:
- you installed an old version of the plugin that does not have the `sltr`
- you installed the plugin but forgot to restart elasticsearch

**Comment by AamirNakhwa** [comment]
Hello @nomoa 
Thanks for your response.
I am using **elasticsearch 5.4.0** and downloaded **ltr-query-0.1.1-es5.4.0.zip** from [http://es-learn-to-rank.labs.o19s.com/]

![image](https://user-images.githubusercontent.com/35491151/35321816-d6004cfc-0109-11e8-947b-6db7c312cb7c.png)

It returned empty array of plugins...
But why it is showing ltr-query on command line

![image](https://user-images.githubusercontent.com/35491151/35321899-2b5790d4-010a-11e8-8ce4-801390c0f675.png)

Well, now what I should do?

**Comment by AamirNakhwa** [comment]
I have installed elasticsearch as a service and I just restart (stop/start) it and now getting this response from command localhost:9200/_nodes/_local/plugins?pretty=true

![image](https://user-images.githubusercontent.com/35491151/35325408-8287b7d4-0115-11e8-80b6-c565b09716c7.png)

**Comment by softwaredoug** [comment]
Hi @AamirNakhwa the 0.1.1 version of the plugin is the legacy version, whereas the demo on master is on 1.0.0. I would recommend installing 1.0.0 if possible. But 1.0.0 is currently available for 5.6.6 and 6.1.2. 

Sadly ES plugins need to be rebuilt and sometimes ported for even for patch versions, so we don't rebuild the plugin for every ES release. There's instructions for rebuilding 1.0.0 in the README for folks that need to target a very specific ES version.

Alternatively, you can try the demo for 0.1.1 located in [this branch](https://github.com/o19s/elasticsearch-learning-to-rank/tree/es_5_4_2)

**Comment by AamirNakhwa** [comment]
But Elasticsearch 5.6.0, based on Lucene 6.6.0 is the latest stable release...

**Comment by AamirNakhwa** [comment]
And can I clone this demo web application
[](http://es-learn-to-rank.labs.o19s.com/demo/ltr-search.html)?

**Comment by jettro** [comment]
Latest stable release is 6.1.2 and in the 5 series it is 5.6.6
https://www.elastic.co/downloads/past-releases

**Comment by AamirNakhwa** [comment]
I want to clone this [demo web application](http://es-learn-to-rank.labs.o19s.com/demo/ltr-search.html)?

**Comment by rishikumar** [comment]
@AamirNakhwa  - click on the link at the top right that says "fork me on github". You can clone it from there.

**Comment by AamirNakhwa** [comment]
@rishikumar I have cloned it but it is console demo. I want to review code of [this web based demo applciation](http://es-learn-to-rank.labs.o19s.com/demo/ltr-search.html)

**Comment by softwaredoug** [comment]
@AamirNakhwa there's a half baked app [here](http://github.com/o19s/elasticsearch-ltr-demo)

**Comment by AamirNakhwa** [comment]
Hello,
Thank you @jettro, I update ElasticSearch to **6.1.2** and configure **ltr-1.0.0** with it and now those scripts are working fine. Now I want to clear a confusion about the plugin. 

We give some relevant results for a query with grades, but obviously, your **judgment list** doesn't have relevant results for all the _indexed documents_. So how the plugin perform rescoring on remaining documents which don't have relevant results in **judgment list**?

**Comment by softwaredoug** [comment]
Answered @AamirNakhwa's question over email, so I think this is good to close. Feel free to reopen if you disagree.
