### ISSUE TITLE
Does LTR work for long-form questions

### ISSUE THREAD

**Issue by bigrig2212** [o19s/elasticsearch-learning-to-rank#127]
Is the solution ideally suited to keyword based search optimization - or do you think it would work also with longer form questions (with a lot of chaff in them)? 

ie: 
"Hi. I can't find the warranty information for my BlahX98. Can you send me the warranty stuff for it? Thank you for the help."

**Comment by softwaredoug** [comment]
It's honestly good for any ranking optimization. Spellchecking, autosuggest, recommendations, search... LTR is a pretty broad subgrouping under LTR that covers optimizing any ranking as a function of features. 

The *features* would be quite different. They'd likely be more related to understanding the intend of the question. With lots of NLP and what-not.

The overall topic of 'question answering' is very broad. [Taming Text](https://www.manning.com/books/taming-text) has some introductory chapters on the topic.

**Comment by rpedela** [comment]
Are you wanting to understand the query or optimize the ranking of the query's search results?

**Comment by bigrig2212** [comment]
I'm wanting to pick the best answer (or top 3 answers) out of a large number of possible answers. So, depends what you mean by "understand." I think that optimizing ranking would achieve the desired effect, given a great dataset of answers to start - and a reliable feedback loop (which I have).

(just ordered Taming Text. thx).

**Comment by bigrig2212** [comment]
Also have a hunch that there may be some interesting opportunities for pre-processing using AWS comprehend API...

**Comment by softwaredoug** [comment]
Thanks for the question @bigrig2212, don't hesitate to reach out to the LTR team on Relevancy Slack for further questions: http://o19s.com/slack
