### ISSUE TITLE
The X-Pack support should be back-ported to the 5.x bunch of releases.

### ISSUE THREAD

**Issue by purbon** [o19s/elasticsearch-learning-to-rank#128]
The X-Pack support published in https://github.com/o19s/elasticsearch-learning-to-rank/pull/126 should be backported to all the 5.x releases where x-pack has presence.

Versions:

- [ ] 5.6.6

versions without a 1.0 release has not been taken into account.

**Comment by softwaredoug** [comment]
@purbon love to see this, but as we're supporting 7 now, I will close this. But if you/others want to backport this don't hesitate to reopen
