### ISSUE TITLE
Would be helpful to output all feature-values with matching documents in the response.

### ISSUE THREAD

**Issue by peterdm** [o19s/elasticsearch-learning-to-rank#13]
This would make the feature-value inputs available to be logged (as future training data) without having to re-evaluate each feature query as a `script_field`.  

(Those weights could simply be output in the response)

E.g.  Instead of having to do

```
GET /rando/_search
{
    "query": {
        "ltr": {
            "model": {
                "stored": "testmodel"
            },
            "features": [{
                "script": {
                  "script": {        
                    "lang": "expression",
                    "inline": "doc['lucky_number']"
                  }
                }
            }]
        }
    },
    "script_fields": {
      "1": {
        "script" : {
          "lang": "expression",
          "inline" : "doc['lucky_number']"
        }
      }
    },
    "_source":true
}
```

to get:

```
{
  "took": 10,
  "timed_out": false,
  "_shards": {
    "total": 5,
    "successful": 5,
    "failed": 0
  },
  "hits": {
    "total": 3,
    "max_score": 0.5,
    "hits": [
      {
        "_index": "rando",
        "_type": "fortune",
        "_id": "2",
        "_score": 0.5,
        "_source": {
          "msg": "Let the deeds speak.",
          "lucky_number": 2.2
        },
        "fields": {
          "1": [
            2.2
          ]
        }
      },
      {
        "_index": "rando",
        "_type": "fortune",
        "_id": "1",
        "_score": 0.5,
        "_source": {
          "msg": "Be patient: in time, even an egg will walk.",
          "lucky_number": 0.9
        },
        "fields": {
          "1": [
            0.9
          ]
        }
      },
      {
        "_index": "rando",
        "_type": "fortune",
        "_id": "3",
        "_score": 0.5,
        "_source": {
          "msg": "Digital circuits are made from analog parts.",
          "lucky_number": 3.3
        },
        "fields": {
          "1": [
            3.3
          ]
        }
      }
    ]
  }
}
```

**Could we generate the same output by running this?:**   
(perhaps even incorporating query `_name`s for clarity?)

```
GET /rando/_search
{
    "query": {
        "ltr": {
            "output_feature_values": true,
            "model": {
                "stored": "testmodel"
            },
            "features": [{
                "script": {
                  "_name": "lucky",
                  "script": {        
                    "lang": "expression",
                    "inline": "doc['lucky_number']"
                  }
                }
            }]
        }
    }
    "_source":true
}
```

to produce something like this?

```
{
  "took": 10,
  "timed_out": false,
  "_shards": {
    "total": 5,
    "successful": 5,
    "failed": 0
  },
  "hits": {
    "total": 3,
    "max_score": 0.5,
    "hits": [
      {
        "_index": "rando",
        "_type": "fortune",
        "_id": "2",
        "_score": 0.5,
        "_source": {
          "msg": "Let the deeds speak.",
          "lucky_number": 2.2
        },
        "feature_values": [{
          "lucky": 2.2
        }]
      },
      {
        "_index": "rando",
        "_type": "fortune",
        "_id": "1",
        "_score": 0.5,
        "_source": {
          "msg": "Be patient: in time, even an egg will walk.",
          "lucky_number": 0.9
        },
        "feature_values": [{
          "lucky": 0.9
        }]
      },
      {
        "_index": "rando",
        "_type": "fortune",
        "_id": "3",
        "_score": 0.5,
        "_source": {
          "msg": "Digital circuits are made from analog parts.",
          "lucky_number": 3.3
        },
        "feature_values": [{
          "lucky": 3.3
        }]
      }
    ]
  }
}

**Comment by peterdm** [comment]
It's likely to be the common case to want to expose the computed feature-values to downstream consumers.  This would reduce the execution weight of this sort of query, by not having to calculate the same values twice.

**Comment by softwaredoug** [comment]
Good idea

**Comment by ebernhardson** [comment]
Indeed one common difficulty in ML systems is a disparity between the feature values used in production, and those used when training the system. Logging production feature generation is a good way to ensure that everything is consistent end to end. 

I'm not sure though how to get this into elasticsearch. I poked around quite a bit developing an LTR plugin for elasticsearch 2 and was not able to find a way to get the values into the response format. The difficulty is that the response from the data nodes to the original query nodes needs to be updated to include the extra data, such that it can be returned in the json response. Would be good to find a way to integrate this.

**Comment by softwaredoug** [comment]
At the very least, we can create debug output that could be used. We can keep an eye to having this be relatively consistent and machine readabel

**Comment by softwaredoug** [comment]
One todo I have is to make a query explain that at a mininum shows each feature's values for a doc. Now debug output is more costly in production, but not sure you want to log everyone's features anyway...

**Comment by nomoa** [comment]
Would it be possible to do this with a custom highlighter? The user would simply have to duplicate its LTR query as an highlight query. It then should be able to output a text blob, this blob could be even very close to ranklib line format. The highlighter would be highly coupled to the LTR query allowing it to disable the ranklib model to only inspect individual feature scorers.
I haven't thought about all the details and I doubt that it's a viable solution for production, but it could help to avoid mistakes such as the disparities described by Erik.

**Comment by softwaredoug** [comment]
Debug output was added in 0.1.0

Another option is to issue each query using `_msearch` against production for queries you want to log features for.

**Comment by ebernhardson** [comment]
_msearch is a possibility, certainly. I'm a bit wary of having too many different ways to provide the feature queries though. The more times something is duplicated the more opportunity there is to diverge between building data sets and what ends up running in production. I think the solr plugin had the right approach here: The queries used for generating features are stored inside the model, and the resulting vectors can be returned as part of the search result. This helps to reduce the surface area of errors.

**Comment by softwaredoug** [comment]
Going to investigate how feasible this would be. The complication is that it's relatively straightforward to build a plugin that creates a Lucene query, I suspect it's more complex to customize the response. I also would like to keep the plugin footprint small for maintenance and as ES plugins are relatively sandboxed with lots of nice strict enforcement of expected behaviors. So perhaps there's a combination of plugin work and existing features that can help get this.

**Comment by epugh** [comment]
@peterdm have you looked at what @nomoa added in PR #54 ?   Does that go far enough to call this "done" for our 1.0 release?

**Comment by softwaredoug** [comment]
This works in 1.0. Closing
