### ISSUE TITLE
Release new plugin version for 6.2.1 elasticsearch release

### ISSUE THREAD

**Issue by purbon** [o19s/elasticsearch-learning-to-rank#132]
Last 8 of February a new version of elasticsearch, 6.2.1 was released. We should cut a branch and release a new version of the plugin for this new release.

**Comment by webmasterscity** [comment]
-> Downloading http://es-learn-to-rank.labs.o19s.com/ltr-1.0.1-es6.1.2.zip
[=================================================] 100%   
Exception in thread "main" java.lang.IllegalArgumentException: plugin [ltr] is incompatible with version [6.2.1]; was designed for version [6.1.2]

**Comment by purbon** [comment]
Hi Leonardo, actually you downloaded the plugin for the 6.1.2 version.
There is still no plugin for 6.2.1.

/purbon

El dc., 21 de febr., 2018 20.38, Leonardo Meléndez <notifications@github.com>
va escriure:

**Comment by webmasterscity** [comment]
Ok, Thanks you for your answer

**Comment by purbon** [comment]
fixed in #147
