### ISSUE TITLE
Provide SSL URL

### ISSUE THREAD

**Issue by otrosien** [o19s/elasticsearch-learning-to-rank#134]
Please provide an SSL-enabled download link for the plugin.

**Comment by softwaredoug** [comment]
Currently we are using an s3 bucket, so for custom domain, we can't get https without paying for cloudflare or something. However, s3 has an https link:

https://s3.amazonaws.com/es-learn-to-rank.labs.o19s.com

So if you need an https download link, I would recommend using that for the time being.

**Comment by otrosien** [comment]
That's good enough for now.
