### ISSUE TITLE
Support Fewer Models (slim down to handful of Ranklib models)

### ISSUE THREAD

**Issue by softwaredoug** [o19s/elasticsearch-learning-to-rank#14]
Erik Bernhardson makes a good point that really there's only a few types of models you probably care about. Ranklib comes with all sorts of intermediate/weird models that most people probably don't care about.

## Maximum Interpretability

- Models, like the **linear model**, that are basically optimized boosts. Advantage: it's easy to interpret, debug, and understand these models

## Maximum Flexibility / Prediction Power

- LambdaMART/Boosted Tree model that does a great job of predicting the weird nooks and crannies of search relevance

Related, we probably don't need to really rely on Ranklib when we just care about these 2 or 3 models, and only the evaluation parts of those models as well

**Comment by epugh** [comment]
@softwaredoug is this something we care about for 1.0?   Is this a real "issue" or just a good idea?

**Comment by softwaredoug** [comment]
I think for 1.0 we will support ranklib and xgboost model serialization formats. As well as a few basic linear and other models.
