### ISSUE TITLE
Defining a custom feature

### ISSUE THREAD

**Issue by EgorLakomkin** [o19s/elasticsearch-learning-to-rank#145]
Hello and thank you for a great plug-in!
I want to ask if there is an example of defining a custom feature, like Jaccard distance between query and title? Is it possible to write this in Java for example or any other language?

Thanks in advance!

**Comment by ebernhardson** [comment]
Any elasticsearch query can be used as a feature. To create a custom elasticsearch query you will need to make a plugin in java that implements [SearchPlugin.getQueries()](https://github.com/elastic/elasticsearch/blob/master/server/src/main/java/org/elasticsearch/plugins/SearchPlugin.java#L115).  This repository contains one such example with the [query explorer](https://github.com/o19s/elasticsearch-learning-to-rank/tree/master/src/main/java/com/o19s/es/explore).

**Comment by EgorLakomkin** [comment]
Hi, @ebernhardson and thanks for your reply! Sorry, I am not very familiar with the ElasticSearch internals and I could not find where in the query explorer any class implementing getQueries.

Just wanted to clarify: you mean that elasticsearch query can be used as a feature what do you mean? I used to think that a feature could be a scalar or a vector and I am wondering how it can be extracted from the query? Can the query result has result fields with arbitrary values - for example, to measure the similarity between a title and user query in several ways (Levenshtein distance, Jaccard similarity, number of overlapping words etc). Thank you in advance for your help!

**Comment by softwaredoug** [comment]
Going to close this issue, thanks for the question @EgorLakomkin - I'm not sure how vector features would work, but if you have thoughts I encourage you to open an issue and we could discuss such functionality. I think as others have said, it might require something more fundamental to change in Lucene and Elasticsearch.
