### ISSUE TITLE
Kill the Ranklib dependency

### ISSUE THREAD

**Issue by softwaredoug** [o19s/elasticsearch-learning-to-rank#15]
Related to #14. Scientist say we only use 1% of our Brains err I mean Ranklib.

So when you focus on what actually matters, we don't really care about most of the models. We don't really care about the training side of Ranklib. And when you take all that stuff away you get a very small set of code for evaluating some models. 

This issue is to kill the dependency and just directly include the models/code we care about

**Comment by dacox** [comment]
seems like the milestone is a little out of date since `v1.1` is already out

**Comment by softwaredoug** [comment]
Good call @dacox... I'm going to close this issue as I don't think its a huge priority
