### ISSUE TITLE
How to upload XGBoost model to ES?

### ISSUE THREAD

**Issue by Greyvend** [o19s/elasticsearch-learning-to-rank#150]
[xgb.py](https://github.com/o19s/elasticsearch-learning-to-rank/blob/master/demo/xgboost-demo/xgb.py) file touches upon the training of XGBoost model. However, it's not clear how to deploy the model to ES. Calling `saveModel` function, like this:

```
saveModel(scriptName="test_%s" % 9, featureSet='movie_features',
          modelFname='xgb-model.json')
```
just as in [train.py](https://github.com/o19s/elasticsearch-learning-to-rank/blob/master/demo/train.py#L76), results in an error:
```
{
  "error": {
    "root_cause": [
      {
        "type": "illegal_argument_exception",
        "reason": "Error while parsing model [test_9] with type [model\/ranklib]"
      }
    ],
    "type": "illegal_argument_exception",
    "reason": "Error while parsing model [test_9] with type [model\/ranklib]",
    "caused_by": {
      "type": "rank_lib_error",
      "reason": "java.lang.NullPointerException",
      "caused_by": {
        "type": "null_pointer_exception",
        "reason": null
      }
    }
  },
  "status": 400
}
```

Can someone please explain the proper deployment for XGBoost? And what other models are supported?

**Comment by nomoa** [comment]
I think the `train.py` script is hardcoded to work with ranklib, I believe you can adapt the saveModel model to work with _xgboost_ format by changing the `modelPayload` variable to : 
```python
    modelPayload = {
        "model": {
            "name": scriptName,
            "model": {
                "type": "model/xgboost+json", # was hardcoded to model/ranklib
                "definition": {
                }
            }
        }
    }
```

**Comment by Greyvend** [comment]
Got it working, thanks again @nomoa !

**Comment by lonngxiang** [comment]
> I think the `train.py` script is hardcoded to work with ranklib, I believe you can adapt the saveModel method to work with _xgboost_ format by changing the `modelPayload` variable to :
> 
> ```python
>     modelPayload = {
>         "model": {
>             "name": scriptName,
>             "model": {
>                 "type": "model/xgboost+json", # was hardcoded to model/ranklib
>                 "definition": {
>                 }
>             }
>         }
>     }
> ```
> 
> Currently we only support:
> 
> * ranklib : `model/ranklib`
> * xgboost: `model/xgboost+json`
> * simple dot product: `model/linear`
> 
> It has been proven that one can transform a `lightgbm` model into `xgboost` (assuming you use dense vectors and only numerical features). See the lgb2xgb method [here](https://gerrit.wikimedia.org/r/#/c/403335/21/mjolnir/training/lightgbm.py).

still not work:
{
"error": {
"root_cause": [
{
"type": "parsing_exception",
"reason": "Field [feature_set] is mandatory",
"line": 1,
"col": 218
}
],
"type": "x_content_parse_exception",
"reason": "[1:218] [storable_elements] failed to parse field [model]",
"caused_by": {
"type": "parsing_exception",
"reason": "Field [feature_set] is mandatory",
"line": 1,
"col": 218
}
},
"status": 400
}
