### ISSUE TITLE
Can the newest plugin install on 5.2.2 elasticsearch?

### ISSUE THREAD

**Issue by miandai** [o19s/elasticsearch-learning-to-rank#151]
Sorry to bother everyone. The plugin is gorgeous. I try to use it in my elasticsearch. But the version of elasticsearch is 5.2.2. Can I install the newest plugin on 5.2.2 elasticsearch? 

Many thanks!

**Comment by softwaredoug** [comment]
Hi @miandai unfortunately its challenging to maintain back ports. I do believe we released on 5.6.x. An earlier / no longer supported version of the plugin (0.1.x line). See here:

https://github.com/o19s/elasticsearch-learning-to-rank/tree/es_5_2_2
