### ISSUE TITLE
Add more metrics to match_explorer

### ISSUE THREAD

**Issue by nomoa** [o19s/elasticsearch-learning-to-rank#155]
The match_explorer query allows to extract raw index numbers. Currently it allows to extract:
- the number of unique tokens in the query
- stats the term freq in the doc
- stats on document frequency

It could be extended to allow extract more numbers stored in lucene (if available position information for instance).

Please add your suggestions in the comments I'll try to summarize those and update the task description.

**Comment by li910802** [comment]
When we use the match_explorer query, we hope to extract more similarity features between query and documents for training ltr model, such as the startoffset of the first matched term, the proportion of matched terms and total terms. 

For different search circumstances, we need to use different search patterns (match, match_phrase, match_phrase_prefix for instance). So in my opinion it is necessary to extract the accurate feature numbers correspond to different search patterns . But currently passing a match or a phrase query will return the same results.
I wonder if my personal opinion is apporiate.
Thanks!

**Comment by GerardBouchar** [comment]
I think that the proportion of matched terms would be a very interesting feature.

**Comment by ebernhardson** [comment]
The proportion of matched terms is already available, albeit in an indirect way. Basically you can create a feature that counts the number of tokens in the query (using query explorer existing feature set), and you can create another feature that counts the number of matches (bm25 with the right k1 and b parameters will do this).  The existing derived feature functionality can then give you a new feature that is the proportion between those two. I'm not sure if it's better off documenting as a way to use more advanced functionality, or hard coding some particular items that are likely to be useful like % of matched terms.

**Comment by rtancman** [comment]
Hi @nomoa and @softwaredoug!

I saw in project code in [ExplorerQuery.java#L204-L216](https://github.com/o19s/elasticsearch-learning-to-rank/blob/master/src/main/java/com/o19s/es/explore/ExplorerQuery.java#L204-L216) one way to use `match_explorer` with `sum_raw_tf` creating features this way:

```
POST _ltr/_featureset/some_cool_features
{
  "featureset": {
    "name": "some_cool_features",
    "features": [
      {
        "name": "sum_raw_tf_text",
        "params": [
          "keywords"
        ],
        "template_language": "mustache",
        "template": {
          "match_explorer": {
            "type": "sum_raw_tf",
            "query": {
              "match": {
                "text": "{{keywords}}"
              }
            }
          }
        }
      }
    ]
  }
}
```

But we have a big message in this code to fix it. We tested this feature and sometimes when every word doesn't exist in documents we have a `null_pointer_exception` error in results. 

We really want to create features with `TF` * `IDF`. If is it a problem and if you want this feature we will create that. What do you think?

**Comment by nathancday** [comment]
I think this should have been closed via the ScriptScore feature capability.
