### ISSUE TITLE
es 5.5.1 version download failed.

### ISSUE THREAD

**Issue by kinglai** [o19s/elasticsearch-learning-to-rank#159]
when access http://es-learn-to-rank.labs.o19s.com/ltr-1.0.0-es5.5.1.zip, return access error, can I use latest version over es 5.5.1?

**Comment by kinglai** [comment]
http://es-learn-to-rank.labs.o19s.com/ltr-query-0.1.2-es5.4.0.zip  also failed, why?

**Comment by softwaredoug** [comment]
The 1.0 release was not built for 5.5.1. It was released coinciding with 6.0. Backporting to older version of Elasticsearch is quite complex, we would certainty welcome a PR to a branch for a specific Elasticsearch version, if it's important enough. [OSC](http://opensourceconnections.com) can also perform backporting as part of a consulting engagement.

All of the 0.1.2 were moved to the "Legacy" folder as it's defunct in favor of the supported 1.x line.

I recommend browsing at the top-level http://es-learn-to-rank.labs.o19s.com to see all the available versions of Elasticsearch+LTR

**Comment by purbon** [comment]
@kinglai also I can provide the backporting as part of freelance engagement if necessary. Happy to help your orgs.

**Comment by softwaredoug** [comment]
I can also recommend @purbon :)
