### ISSUE TITLE
Demonstrate xgboost usage

### ISSUE THREAD

**Issue by softwaredoug** [o19s/elasticsearch-learning-to-rank#16]
Apparently [xgboost](https://github.com/dmlc/xgboost) is the shiznit for training boosted trees. We should demonstrate how xgboost can be used with this plugin, with existing Ranklib XML method of specifying a LambdaMART model.

I would expect
- scripts directory showing off xgboost
- or another git repo demonstrating xgboost + ES w/ this plugin
- or a helpful blog post on xgboost + ES

**Comment by softwaredoug** [comment]
XGBoost has a text format listed [here](https://github.com/dmlc/xgboost/issues/1205) but it appears to perhaps be a debug project

**Comment by epugh** [comment]
There is a brief mention of xgboost in https://github.com/o19s/elasticsearch-learning-to-rank/blob/1_0/docs/models.md but no detail...
