### ISSUE TITLE
Unable to install plugin for elasticsearch 6.3.0

### ISSUE THREAD

**Issue by dharmanextsteps** [o19s/elasticsearch-learning-to-rank#168]
Could please help me in installing plugin for es 6.3.0 instead of es lower versions.

**Comment by purbon** [comment]
the plugin needs to be build for this new version, there is no official version compiled in http://es-learn-to-rank.labs.o19s.com/

**Comment by purbon** [comment]
if you are adventurous, you can take a look at https://github.com/o19s/elasticsearch-learning-to-rank#development and sort it out yourself in the meanwhile we release a new version.
