### ISSUE TITLE
String keys for feature-generating queries

### ISSUE THREAD

**Issue by peterdm** [o19s/elasticsearch-learning-to-rank#17]
In the current implementation feature-generating queries are matched to features in a trained model based on their _position_ in the `ltr` subquery.

This is extremely terse, and introduces many opportunities to introduce positional mismatches (during query development, or model development), without a validation step.

What could help, at least from a query-development perspective would be something similar to this:

http://alexbenedetti.blogspot.com/2016/08/solr-is-learning-to-rank-better-part-2.html

Where features are identified with a string-key in the query.  And the ordering/alignment of feature-inputs against the model is specified in a separate block from the feature-inputs themselves.

Significantly, then those feature description string-keys could then be carried through to the `_explain` (in place of **"Feature 7:"**) for more readable validation.

**Comment by softwaredoug** [comment]
Seems doable :+1:
