### ISSUE TITLE
unknow plugin ltr-1.0.0-es6.1.2

### ISSUE THREAD

**Issue by jihanxiaogo** [o19s/elasticsearch-learning-to-rank#175]
When i run ./bin/elasticsearch-plugin install http://es-learn-to-rank.labs.o19s.com/ltr-1.0.0-es6.1.2.zip,it shows that "unknow plugin ltr-1.0.0-es6.1.2".
In addition, i wonder why the site http://es-learn-to-rank.labs.o19s.com/ shows nothing.

**Comment by ebernhardson** [comment]
The site is back up now. Sorry for the inconvenience, we may need to consider other options for hosting the plugin artifacts.
