### ISSUE TITLE
Elastic Search LTR Plugin support on Elastic Cloud

### ISSUE THREAD

**Issue by wngawpk** [o19s/elasticsearch-learning-to-rank#181]
May I know if the LTR plugin is supported on Elastic Cloud?
As far as I know, Elastic cloud is the preferred way to host ES due to X Pack.
But within Elastic cloud, I could not figure out a way to activate Elasticsearch LTR Plugin.

**Comment by epugh** [comment]
Have you followed the steps on https://www.elastic.co/guide/en/cloud/current/ec-custom-bundles.html?   Looks like you need Gold or Platinum.   I know that other cloud providers do support the LTR plugin as well, specifically Bonsai.io, though I don't know which plan you need.

**Comment by wngawpk** [comment]
@epugh Thank you very much for your response.

I could not follow the steps on [](https://www.elastic.co/guide/en/cloud/current/ec-custom-bundles.html) as I do not have Gold/Platinum now. I have no issues getting one, but Elastic Cloud free trial does not allow me to test it out first.

Looking more into Elastic Cloud custom plugin [](https://www.elastic.co/guide/en/elasticsearch/plugins/6.4/index.html), it seems that Elastic Cloud does not recognise Elastic Search LTR Plugin as one of the _community contributed plugins_.

I have looked into Bonsai.io as well, but seems like Bonsai.io does not provide X-Pack support, which Elastic Cloud has.

Read more on Bonsai.io plugins: https://docs.bonsai.io/docs/plugins

**Comment by softwaredoug** [comment]
Hi @wngawpk ... Not sure you saw this writeup on the docs about using with XPack? That *should* be what you need 

https://elasticsearch-learning-to-rank.readthedocs.io/en/latest/x-pack.html

**Comment by softwaredoug** [comment]
Going to close, feel free to reopen if XPack support is not doing what you need
