### ISSUE TITLE
Can I build this plugin for elasticsearch version 2.4

### ISSUE THREAD

**Issue by dnmahendra** [o19s/elasticsearch-learning-to-rank#184]
We are still on es2.4 and want to try this plugin. I couldn't find much documentation on how to build this plugin for previous versions. Can you please advise?

**Comment by softwaredoug** [comment]
Sorry, we released this plugin for ES 5 & 6. Elasticsearch code base has changed dramatically that it would be quite a lot of work to backport it to ES 2.4.
