### ISSUE TITLE
Use features not in Elasticsearch

### ISSUE THREAD

**Issue by IamGianluca** [o19s/elasticsearch-learning-to-rank#185]
Hi,

I'm evaluating the use of the LTR plugin for a Search Engine on a medium size website (15M+ users per month). I can't find anywhere in the documentation information regarding the usage of user-level features to compute the ranking, e.g. price sensitiveness for each user. I'm assuming such features are better stored in a database like Cassandra and retrieved at search time from the LTR plugin.

Does the latest version of the plugin offer such feature?

**Comment by ebernhardson** [comment]
User-level features need to be provided to the sltr query as parameters. The most straightforward way to declare one is to private a "price_sensitivity" parameter to the sltr query, and define a script feature that simply returns the provided value (a painless script with source `params.price_sensitivity` should do the trick).

**Comment by softwaredoug** [comment]
Right now what @ebernhardson lists is the recommended approach. But I would recommend if you have any suggestions or ideas on improving this, please feel free to open another issue.

**Comment by zhuqingrui** [comment]
I provide a "price_sensitivity" parameter for the sltr query

> User-level features need to be provided to the sltr query as parameters. The most straightforward way to declare one is to provide a "price_sensitivity" parameter to the sltr query, and define a script feature that simply returns the provided value (a painless script with source `params.price_sensitivity` should do the trick).

but i have an error, like as
       "caused_by": {
            "type": "illegal_argument_exception",
            "reason": "Could not find method newInstance or method newFactory on FactoryType class [org.elasticsearch.script.ExecutableScript] for script context [search]"
          }

**Comment by zhuqingrui** [comment]
> I provide a "price_sensitivity" parameter for the sltr query
> 
> > User-level features need to be provided to the sltr query as parameters. The most straightforward way to declare one is to provide a "price_sensitivity" parameter to the sltr query, and define a script feature that simply returns the provided value (a painless script with source `params.price_sensitivity` should do the trick).
> 
> but i have an error, like as
> "caused_by": {
> "type": "illegal_argument_exception",
> "reason": "Could not find method newInstance or method newFactory on FactoryType class [org.elasticsearch.script.ExecutableScript] for script context [search]"
> }

this is my template
{
  "featureset": {
    "name": "qd_features_test_20181228001",
    "features": [
            {
                "name": "cat_query",
                "params": [
                    "keywords",
                    "categoryid",
                    "price_sensitivity"
                ],
                "template_language": "mustache",
                "template": {
                    "match": {
                        "categoryid": "{{categoryid}}"
                    }
                }
            },
            {
                "name": "title_query",
                "params": [
                    "keywords",
                    "categoryid",
                    "price_sensitivity"
                ],
                "template_language": "mustache",
                "template": {
                    "match": {
                        "title": "{{keywords}}"
                    }
                }
            },
          {
        "name": "dummy_feature",
        "params": [
            "keywords",
            "categoryid",
            "price_sensitivity"
        ],
        "template_language": "script_feature",
        "template": {
          "lang": "painless",
         "source": "params.price_sensitivity",
         "params": {
              "price_sensitivity": "price_sensitivity"
          }
        }
      }
    ]
  }
}

**Comment by zhuqingrui** [comment]
> > I provide a "price_sensitivity" parameter for the sltr query
> > > User-level features need to be provided to the sltr query as parameters. The most straightforward way to declare one is to provide a "price_sensitivity" parameter to the sltr query, and define a script feature that simply returns the provided value (a painless script with source `params.price_sensitivity` should do the trick).
> > 
> > 
> > but i have an error, like as
> > "caused_by": {
> > "type": "illegal_argument_exception",
> > "reason": "Could not find method newInstance or method newFactory on FactoryType class [org.elasticsearch.script.ExecutableScript] for script context [search]"
> > }
> 
> this is my template
> {
> "featureset": {
> "name": "qd_features_test_20181228001",
> "features": [
> {
> "name": "cat_query",
> "params": [
> "keywords",
> "categoryid",
> "price_sensitivity"
> ],
> "template_language": "mustache",
> "template": {
> "match": {
> "categoryid": "{{categoryid}}"
> }
> }
> },
> {
> "name": "title_query",
> "params": [
> "keywords",
> "categoryid",
> "price_sensitivity"
> ],
> "template_language": "mustache",
> "template": {
> "match": {
> "title": "{{keywords}}"
> }
> }
> },
> {
> "name": "dummy_feature",
> "params": [
> "keywords",
> "categoryid",
> "price_sensitivity"
> ],
> "template_language": "script_feature",
> "template": {
> "lang": "painless",
> "source": "params.price_sensitivity",
> "params": {
> "price_sensitivity": "price_sensitivity"
> }
> }
> }
> ]
> }
> }

and ltr_query:
post esite_hx_esearchrestype_text_index/_search
{
  "size": 10000,
  "query": {
    "bool": {
      "filter": [
        {
          "terms": {
            "CBID": [
              "11359020804605506",
              "3591328404033401",
              "12096015604053904"
            ]
          }
        }
      ],
      "should": [
        {
          "sltr": {
            "_name": "logged_featureset",
            "featureset": "qd_features_test_20181228001",
           "params": {
				"keywords": "hero",	
				"categoryid": 14300,
				"price_sensitivity":10
}
          }
        }
      ]
    }
  },
  "ext": {
    "ltr_log": {
      "log_specs": {
        "name": "main",
        "named_query": "logged_featureset",
        "missing_as_zero": true
      }
    }
  }
}

**Comment by luweizhang** [comment]
I'm having the same issue?  Any resolution here?

**Comment by liuzihaoboy** [comment]
I'm having the same issue too, Any resolution here?

**Comment by liuzihaoboy** [comment]
> I'm having the same issue? Any resolution here?

hi, do you resolut it ?

**Comment by softwaredoug** [comment]
Apologies I should reopen this issue, it fell through the cracks. We will look into this.

**Comment by liuzihaoboy** [comment]
what's your  solution for it?

**Comment by liuzihaoboy** [comment]
> Apologies I should reopen this issue, it fell through the cracks. We will look into this.

hi, why happend?

**Comment by liuzihaoboy** [comment]
i have a online problem like it, Any resolution here?

**Comment by softwaredoug** [comment]
This is a volunteer driven project, it will take several days to look into
it.

You're definitely encourage to take down the source code and contribute a
PR, we'd love to have your contributions!

**Comment by softwaredoug** [comment]
A more complete way to provide a user-specific feature is to use it in a function_score_query like follows:

```
            {
                "name": "user_price_sensitivity",
                "params": ["price_sensitivity"],
                "template": {
                  "function_score": {
                     "query": {
                        "match_all": {
                        }
                     },
                     "boost_mode": "replace",
                     "functions": [
                        {"script_score" : {
                            "script" : {
                              "lang": "painless",
                              "source": "{{user_recency_sensitivity}}"
                            }
                        }}

                     ]
                  }
                }
            },
```

The value of this query takes on the passed in value that an external system computes. You can use [painless](https://www.elastic.co/guide/en/elasticsearch/painless/current/index.html) to extend the math here further. Let us know if this helps...

**Comment by softwaredoug** [comment]
Haven't heard back in a while, going to close. Feel free to reopen/create a new issue if you need help. Thanks!
