### ISSUE TITLE
A/B testing

### ISSUE THREAD

**Issue by IamGianluca** [o19s/elasticsearch-learning-to-rank#186]
Hi,

Does the existing LTR plugin support run an A/B test between two different LTR models (or an LTR model vs no LTR model)?

Unfortunately, I couldn't find much about how people are running A/B tests in Elasticsearch. 

Many thanks,
Luca

**Comment by ebernhardson** [comment]
There is nothing in particular in the LTR plugin that supports AB testing, but nothing prevents it either

As one example of how AB testing could be done, we have our search application issue an _msearch query with two queries, one for each ranking model. In the application we interleave these using a [team draft](https://www.cs.cornell.edu/people/tj/publications/chapelle_etal_12a.pdf) methodolgy. We log clicks and evaluate roughly as proposed in the linked paper.

**Comment by softwaredoug** [comment]
Hi @IamGianluca yes as @ebernhardson says LTR isn't particularly related to A/B testing. It's a different way of doing ranking using machine learning. I agree though that this is definitely an area the search community could improve, but going to close this issue as it's outside the scope of this particular project.
