### ISSUE TITLE
Is there a way to see a list of all releases?

### ISSUE THREAD

**Issue by drusellers** [o19s/elasticsearch-learning-to-rank#19]
I get a 403 trying to visit: http://es-learn-to-rank.labs.o19s.com/

Additionally, in the instructions you say to visit the URL

`http://es-learn-to-rank.labs.o19s.com/ltr-query-0.0.5-es<ES VER>.zip` but there are no hints to the format of the `ES VER`. Is it `5.1` or `5.1.0`? 

I'm currently playing whack-a-mole to find the supported versions.

Thank you.

**Comment by softwaredoug** [comment]
Good call. Yes it's the 3-digit version number. So 5.1.0

**Comment by softwaredoug** [comment]
@epugh is working on a directory listing for the S3 bucket...

**Comment by epugh** [comment]
@drusellers I was going to let you know that it's fixed, since @sstults added a bit of JS goodness to list out the releases.    However, there appears to be a CORS type error with Chrome, though it works fine in Safari :-(

**Comment by epugh** [comment]
@sstults, here is what Chrome is reporting:

```
Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
index.html:21 GET https://rawgit.com/rufuspollock/s3-bucket-listing/gh-pages/list.js net::ERR_BLOCKED_BY_CLIENT
Navigated to http://es-learn-to-rank.labs.o19s.com/index.html
```

**Comment by sstults** [comment]
> net::ERR_BLOCKED_BY_CLIENT
Chrome privacy plugin blocked it.
