### ISSUE TITLE
add build for ltr-1.1.0-es6.3.2.zip

### ISSUE THREAD

**Issue by intergret** [o19s/elasticsearch-learning-to-rank#190]
we use es 6.3.2, please build one for us

**Comment by softwaredoug** [comment]
Hi @intergret this was relatively easy to do, so I cut a release for 6.3.2:

http://es-learn-to-rank.labs.o19s.com/ltr-1.1.0-es6.3.2.zip

In the future, we may not as easily be able to cut a release for an old version, so its a good idea to familiarize yourself with the steps for building the plugin

**Comment by intergret** [comment]
@softwaredoug ok, thanks
