### ISSUE TITLE
Requesting a build for es 5.5.3

### ISSUE THREAD

**Issue by superlyc** [o19s/elasticsearch-learning-to-rank#196]
Hi, is it possible to provide a release of ltr plugin for es 5.5.3 Attempt to build myself but didn't work

**Comment by nomoa** [comment]
Building for 5.5.3 should be fairly easy if you start from the es_5_5_2 branch, but beware to read https://github.com/o19s/elasticsearch-learning-to-rank/blob/master/KNOWN_ISSUES.md, es 5.5.3 is affected by a serious bug.

You could even try to hack the 5.5.2 build to change the plugin metadata to allow elastic 5.5.3 (http://es-learn-to-rank.labs.o19s.com/ltr-1.0.0-RC1-es5.5.2.zip)

**Comment by softwaredoug** [comment]
Hi @superlyc - To @nomoa's point we are not backfixing bug fixes to 5.x. We would be welcome to PRs to a 5.x release that did so. If you get around to building for 5.5.3 please feel free to issue a PR and we can put it in a branch for that ES release.

**Comment by cqasen** [comment]
能否es5.5.3呀

**Comment by cqasen** [comment]
能否支持es5.5.3版本呀
