### ISSUE TITLE
Testing model

### ISSUE THREAD

**Issue by sdemisse** [o19s/elasticsearch-learning-to-rank#199]
Hi

Is there a way to compare our models using test set? Is there a plan to add testing model on RankLib to the demo?

Thanks.

**Comment by softwaredoug** [comment]
I'm not sure what you mean exactly? Do you mean send all the judgments and rerun searches to score the model against the test set?

**Comment by softwaredoug** [comment]
If this were to be done, it would be best done in the demo. For the time being I would recommend [Rated Ranking Evaluator](https://github.com/SeaseLtd/rated-ranking-evaluator) for this kind of work

**Comment by softwaredoug** [comment]
Will close, I think RRE would be the best tool for the job
