### ISSUE TITLE
Cannot install ltr plugin ES 6.5.0

### ISSUE THREAD

**Issue by ygautomo** [o19s/elasticsearch-learning-to-rank#200]
Kindly needs help on installation on ltr plugin.

when i tried to run command
./bin/elasticsearch-plugin install \
http://es-learn-to-rank.labs.o19s.com/ltr-1.0.0-es6.5.0.zip

found error
 line 3: /usr/share/elasticsearch/bin/elasticsearch-plugin-cli: No such file or directory

actually elasticsearch-plugin-cli is in directory "/usr/share/elasticsearch/lib/tools/plugin-cli/elasticsearch-plugin-cli"

ES_HOME is set to /usr/share/elasticsearch,
java directory has no problem.

i've try change and add the directory in "elasticsearch-plugin" files but have no success.
I guess this is a directory problem, but i couldn't find reference on this.

Thanks.

**Comment by softwaredoug** [comment]
Hi @ygautomo I tried your command, but want to double check you have the correct version of the plugin. The command should be to install the **1.1.0** version of the plugin for Elasticsearch, as in:

```
./bin/elasticsearch-plugin install http://es-learn-to-rank.labs.o19s.com/ltr-1.1.0-es6.5.0.zip
```

**Comment by ygautomo** [comment]
yes. it's
`./bin/elasticsearch-plugin install http://es-learn-to-rank.labs.o19s.com/ltr-1.1.0-es6.5.0.zip`
when i run this command its return
`bash: ./bin/elasticsearch-plugin: No such file or directory`

I guess the problem is in elastic search bash command/script.
somehow not redirected into `usr/share/elasticsearch/lib/tools/plugin-cli/` where elastic plugin installation jar reside.

But i don't know how to resolve this problem.
Any reference or help would be appreciated.

**Comment by softwaredoug** [comment]
As this is rather old, going to close. But don't hesitate to reopen if anyone encounters this issue
