### ISSUE TITLE
Support for Weighted Average Ensemble of Multiple Models

### ISSUE THREAD

**Issue by saurzcode** [o19s/elasticsearch-learning-to-rank#203]
Is there a way this can be used to rank based on ensemble of 2 models , not in a stacking manner, but something like the weighted average of 2 model outputs. For e.g.
I want to rank using xgboost and another linear model and use a weighted average of the two models to compute final ordering of the results.

**Comment by softwaredoug** [comment]
Hi @saurzcode sorry for the late response, the holidays kind of took over!

First, one place to answer the question is over at [search relevance slack](http://o19s.com/slack). There is an #es-learn-to-rank channel that has contributors and users discussing their use of the plugin. We definitely invite you to participate!

Second, I think you could do a weighted linear average of two model outputs by using a boolean query, something like:

```
{"bool":
   "should": [
       {
           "sltr": {
                   ...
                 "boost": 5.0
             }
       },
     {
           "sltr": {
                  ...
                 "boost": 1.0
             }
       },
   ]
}
```

Which translates mathematically to 5 * model1 + 1 * model2

Hope that makes sense...

**Comment by saurzcode** [comment]
Thanks for the reply @softwaredoug , I will check the slack channel.

**Comment by softwaredoug** [comment]
Great, I'll go ahead and close this issue then
