### ISSUE TITLE
how to build the template ......

### ISSUE THREAD

**Issue by zhuqingrui** [o19s/elasticsearch-learning-to-rank#205]
must":{"bool":{"should":[{"match":{"title":{"query":"keyword1"}}},{"match":{"tilte":"keyword2"}},{"match":{"title":{"...... as a feature,how to build the template ......

**Comment by zhuqingrui** [comment]
I get an error when I use my template
post _ltr/_featureset/qd_features_test_20181228001
{
  "featureset": {
    "name": "qd_features_test_20181228001",
    "features": [
      {
        "name": "1",
        "params": [
            "clauses"
        ],
        "template": {
          "script": {
        "lang": "mustache",
        "source": "{\"query\":{\"bool\":{\"must\": {{#toJson}}clauses{{/toJson}} }}}"
    }
        }
      }
    ]
  }
}

this is the err
{
  "error": {
    "root_cause": [
      {
        "type": "parsing_exception",
        "reason": "[script] query does not support [lang]",
        "line": 1,
        "col": 19
      }
    ],
    "type": "search_phase_execution_exception",
    "reason": "all shards failed",
    "phase": "query",
    "grouped": true,
    "failed_shards": [
      {
        "shard": 0,
        "index": "esite_hx_esearchrestype_text_index",
        "node": "f0mPcAiwQliVPaAan0xhkg",
        "reason": {
          "type": "query_shard_exception",
          "reason": "Cannot create query while parsing feature [1]",
          "index_uuid": "p9aCtJyqRleDeEYulHraWw",
          "index": "esite_hx_esearchrestype_text_index",
          "caused_by": {
            "type": "parsing_exception",
            "reason": "[script] query does not support [lang]",
            "line": 1,
            "col": 19
          }
        }
      }
    ]
  },
  "status": 400
}

**Comment by zhuqingrui** [comment]
@nomoa

**Comment by zhuqingrui** [comment]
@epugh @purbon @sstults @jettro

**Comment by zhuqingrui** [comment]
====template
{
  "featureset": {
    "name": "qd_features_test_20181228001",
    "features": [
      {
        "name": "1",
            "params": [
            "clauses"
        ],
        "template_language": "script_feature",
        "template": {
          "script": {
         "lang": "native",
         "source": "{\"query\":{\"bool\":{\"should\": {{#toJson}}clauses{{/toJson}} }}}"
        //"id":"qd_features_test_20181228000",
    }
        }
      }
    ]
  }
}
=====query
get esite_qd_esearchrestype_text_index/_search
{
  "size": 10000,
  "query": {
    "bool": {
      "filter": [
        {
          "terms": {
            "CBID": [
              "11359020804605506"
            ]
          }
        }
      ],
      "should": [
        {
          "sltr": {
            "_name": "logged_featureset",
            "featureset": "qd_features_test_20181228001",
            "params": {
              "clauses": [
          {
            "match" : {
                "title" : "apple"
            }
          },
          {
            "match" : {
                "title" : "pig"
            }
          }
        ]
            }
          }
        }
      ]
    }
  },
  "ext": {
    "ltr_log": {
      "log_specs": {
        "name": "main",
        "named_query": "logged_featureset",
        "missing_as_zero": true
      }
    }
  }
}

===err
{
  "error": {
    "root_cause": [
      {
        "type": "query_shard_exception",
        "reason": "failed to create query: {\n  \"bool\" : {\n    \"filter\" : [\n      {\n        \"terms\" : {\n          \"CBID\" : [\n            \"11359020804605506\"\n          ],\n          \"boost\" : 1.0\n        }\n      }\n    ],\n    \"should\" : [\n      {\n        \"sltr\" : {\n          \"featureset\" : \"qd_features_test_20181228001\",\n          \"params\" : {\n            \"clauses\" : [\n              {\n                \"match\" : {\n                  \"title\" : \"apple\"\n                }\n              },\n              {\n                \"match\" : {\n                  \"title\" : \"pig\"\n                }\n              }\n            ]\n          },\n          \"boost\" : 1.0,\n          \"_name\" : \"logged_featureset\"\n        }\n      }\n    ],\n    \"adjust_pure_negative\" : true,\n    \"boost\" : 1.0\n  }\n}",
        "index_uuid": "C1bGnDL3S2G2DHpqUlzmYw",
        "index": "esite_qd_esearchrestype_text_index"
      }
    ],
    "type": "search_phase_execution_exception",
    "reason": "all shards failed",
    "phase": "query",
    "grouped": true,
    "failed_shards": [
      {
        "shard": 0,
        "index": "esite_qd_esearchrestype_text_index",
        "node": "f0mPcAiwQliVPaAan0xhkg",
        "reason": {
          "type": "query_shard_exception",
          "reason": "failed to create query: {\n  \"bool\" : {\n    \"filter\" : [\n      {\n        \"terms\" : {\n          \"CBID\" : [\n            \"11359020804605506\"\n          ],\n          \"boost\" : 1.0\n        }\n      }\n    ],\n    \"should\" : [\n      {\n        \"sltr\" : {\n          \"featureset\" : \"qd_features_test_20181228001\",\n          \"params\" : {\n            \"clauses\" : [\n              {\n                \"match\" : {\n                  \"title\" : \"apple\"\n                }\n              },\n              {\n                \"match\" : {\n                  \"title\" : \"pig\"\n                }\n              }\n            ]\n          },\n          \"boost\" : 1.0,\n          \"_name\" : \"logged_featureset\"\n        }\n      }\n    ],\n    \"adjust_pure_negative\" : true,\n    \"boost\" : 1.0\n  }\n}",
          "index_uuid": "C1bGnDL3S2G2DHpqUlzmYw",
          "index": "esite_qd_esearchrestype_text_index",
          "caused_by": {
            "type": "illegal_argument_exception",
            "reason": "Could not find method newInstance or method newFactory on FactoryType class [org.elasticsearch.script.ExecutableScript] for script context [search]"
          }
        }
      }
    ]
  },
  "status": 400
}

**Comment by softwaredoug** [comment]
Hi @zhuqingrui - sorry this issue came in during the holidays. Apologies for being late in getting back to you. Do you still have an issue here?

I would also invite you to come to [search relevance slack](http://o19s.com/slack) to the #es-learn-to-rank channel to discuss with the team

**Comment by softwaredoug** [comment]
Closing, don't hesitate to reopen or join us on slack if you need help

**Comment by luweizhang** [comment]
I'm having the same issue? Any resolution here?
