### ISSUE TITLE
Script Features Parameters - slows down Elasticsearch queries significantly

### ISSUE THREAD

**Issue by richardknox** [o19s/elasticsearch-learning-to-rank#207]
Hi,

We have been building a LTR system for our platform and have come across a significant performance decrease using Script Features Parameters as the inputs to our model.

We have a feature set containing 16 features, 14 of which were being generated using an inline painless script at rescore time. 

Under load testing we noticed significantly higher response times (p99 of 187ms) than using indexed features (p99 of 55ms) for a window size of 40, with this increasing to p99 of 55000ms for a window size of 1000 (with indexed features this stayed around the 60ms for p99).

It would be useful for the documentation to warn against using these inline scripts for feature generation where possible, and at a minimum state that there is a performance trade-off to consider.

**Comment by softwaredoug** [comment]
Thanks @richardknox 

Do feel free to submit a documentation PR.

One strategy for isolating performance issues is to issue the query as a boolean query with 16 should clauses. If you still have a performance issue, it's related to the queries themselves. If not, the plugin has an issue.

Also, feel free to join us at [search relevance community slack](http://o19s.com/slack) to discuss this plugin in the #es-learn-to-rank channel.

**Comment by softwaredoug** [comment]
Hi @richardknox is this worth closing now, it seems the script performance was poor independent of the LtR plugin?

**Comment by richardknox** [comment]
Hi @softwaredoug, it does seem to be the case our scripts are the cause and not the plugin itself. Depending on what you guys think, I still feel maybe even a warning regarding using painless could have merit.
Also, @nomoa mentioned that there may still be something going on with script_features as it is doubling our response times but that may be something requiring more investigation.
Happy to go with your feeling!
