### ISSUE TITLE
Prebuilt version for 6.5.4

### ISSUE THREAD

**Issue by cristi-maco** [o19s/elasticsearch-learning-to-rank#210]
Can you please build and publish a version for Elastichsearch 6.5.4 ?  (I see the prebuild versions go only up to 6.5.2)

Somehow unrelated question: any plans in near future to switch to ElasticSearch 6.6 ?  (recently released)

Thanks

**Comment by henrywallace** [comment]
See also https://github.com/o19s/elasticsearch-learning-to-rank/pull/213.

**Comment by ebernhardson** [comment]
We built a 6.5.4 version for our own deployment, should get a version officially deployed but for the moment you should be able to use this.

https://people.wikimedia.org/~dcausse/ltr-1.1.0-es6.5.4-597829e0.zip

**Comment by cristi-maco** [comment]
In the end we built and stored in a local repo our own artifact of the plugin, and also advanced to version 6.6.0, so no need for this prebuilt version, closing this task.
