### ISSUE TITLE
Where is zip located after gradlew clean check

### ISSUE THREAD

**Issue by henrywallace** [o19s/elasticsearch-learning-to-rank#211]
The README states that one can do
```
./gradlew clean check
```

> This runs the tasks in the `esplugin` gradle plugin that builds, tests, generates a Elasticsearch plugin zip file.

I can do so successfully, however, I don't see any fashioned zip. Is the proper thing to zip the build dir oneself?

I'm using Gradle 5.2, Java 11, with Elasticsearch 6.6.0. I've started to update the src to work with this here: https://github.com/o19s/elasticsearch-learning-to-rank/compare/master...henrywallace:hw/es-6.6.0.

**Comment by nomoa** [comment]
The plugin zip file is under `build/distributions`.
Don't forget to update lucene and other projects versions to the ones you see in https://raw.githubusercontent.com/elastic/elasticsearch/v6.6.0/buildSrc/version.properties.
Feel free to open a PR when you're done porting to 6.6.0, thanks!

**Comment by henrywallace** [comment]
@nomoa Can you elaborate on "update lucene and other project versions"? The possibly relevant bits that I could find might be

https://github.com/o19s/elasticsearch-learning-to-rank/blob/76df0170ef131e3c858cad4a115761efe0e880c5/build.gradle#L48-L58

None of which seemed applicable to what is listed in https://raw.githubusercontent.com/elastic/elasticsearch/v6.6.0/buildSrc/version.properties aside from possibly "org.apache.lucene:lucene-expressions:7.5.0" -> 7.6.0.

**Comment by nomoa** [comment]
In general versions should be bumped alongside es versions:
```
   compile "org.apache.lucene:lucene-expressions:7.5.0" 
   compile 'org.antlr:antlr4-runtime:4.5.1-1' 
   compile 'org.ow2.asm:asm:5.0.4' 
   compile 'org.ow2.asm:asm-commons:5.0.4' 
   compile 'org.ow2.asm:asm-tree:5.0.4'
```
should follow versions set in `modules/lang-expression/build.gradle` of the target version of elastic you want to support

```
   compile "com.github.spullara.mustache.java:compiler:0.9.3"
```
must follow the version set in `modules/lang-mustache/build.gradle`

If any of these reference versions.lucene it should be picked up from `buildSrc/version.properties`

Sources for 6.6.0 can be see from https://github.com/elastic/elasticsearch/tree/v6.6.0
