### ISSUE TITLE
Introduce static analysis tools

### ISSUE THREAD

**Issue by henrywallace** [o19s/elasticsearch-learning-to-rank#212]
Such as:
- https://github.com/checkstyle/checkstyle
- https://spotbugs.github.io/, or its variants n.b. https://find-sec-bugs.github.io/
- https://github.com/amaembo/huntbugs

By fixing existing errors, and then adding it to CI to reduce future bugs.

**Comment by softwaredoug** [comment]
FYI, some of this happens as part of Elastic's very stringent Elastic plugin gradle tooling. I believe checkstyle is one of the tasks run. But of course, if you wanted to hook up some of these other tools into our CI process, it'd be great - we'd of course love that contribution

**Comment by softwaredoug** [comment]
Just going through some issues! Going to close this one. But if you had a PR you'd like to open up, we would consider it.
