### ISSUE TITLE
TMDB.json

### ISSUE THREAD

**Issue by andreydung** [o19s/elasticsearch-learning-to-rank#217]
Thanks for the useful framework.

Could you please update the URL to `tmdb.json`? Current path is truncated and is not a valid json. I tried downloading directly from `https://github.com/o19s/relevant-search-book/blob/master/ipython/tmdb.json`, but this is missing a few item_id (for ex 17711).

**Comment by softwaredoug** [comment]
Hi @andreydung ! - FYI this is not a complete JSON file. It's based on gathering IDs from `top_rated` movies in TMDB. If you want a full TMDB dump, you'll have to run [TMDB Dump](http://github.com/o19s/tmdb_dump) to get a full dump. This project systematically crawls TMDB but it takes a lot of time (think days/weeks) to get all movies and respect the TMDB API guidelines.
