### ISSUE TITLE
sample models for rankNet, rankBoost, xgboost and AdaRank

### ISSUE THREAD

**Issue by putriwikie** [o19s/elasticsearch-learning-to-rank#218]
Hi, 

Thank you for the nice framework and the examples. 

Would you please provide samples for rankNet, rankBoost, xgboost and AdaRank? as you provide here: https://github.com/o19s/elasticsearch-learning-to-rank/tree/master/sample_models 

It would be really helpful for us and I will really appreciate it. 

Best, Putri

**Comment by softwaredoug** [comment]
To do this, I would recommend running the demo and exploring the generated models

https://github.com/o19s/elasticsearch-learning-to-rank/blob/master/demo/train.py#L64

I think you're free to do this and send a PR and we would accept this. For now though, I think the current contributors feel its best to just generate a model if you would need it.

Thanks - and don't hesitate to come to the slack channel http://o19s.com/slack to discuss further
