### ISSUE TITLE
ltr store index number_of_shards is 1

### ISSUE THREAD

**Issue by xianing66** [o19s/elasticsearch-learning-to-rank#220]
PUT _ltr create default feature store with number of shards 1 (hard coded). My questions are:
1. Why hardcoded shards as 1?
2. Is it possible to make number shards as input parameter when create default store?

This is because our indexing over 200 shards.  Rescoring always get feature-model from one shard, may turn that shard red.

**Comment by nomoa** [comment]
We could make it an input parameter but this is `number_of_shards` not the `number_of_replicas`.
So unless you have tens of thousands of models I doubt there's need to activate sharding on this index (bear in mind that elastic is able to optimize the 1 shard case).
If you're talking about the number of replicas by default it's set to `0-2` but you can update these settings using the index settings API (https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-update-settings.html).

**Comment by xianing66** [comment]
Thanks for reply. I asked number_of_shards not number_of_replicas. Out use case is:
Search query is over 100K / pre minutes, the indexing data spread to 200 shards, and all query need pass rescoring of LTR

.............
"rescore": {
        "window_size": 1000,
        "query": {
            "rescore_query": {
                "sltr": {
                    "params": {
                        "keywords": "xxxxx"
                    },
                    "model": "my_model"
                }
            },
            "rescore_query_weight": 5.0
        }
    }

.ltrstore at shard 0, showed busy. 
We tried set number_of_shards 10, but POST _ltr/_featureset/lrfeatures/myfeature will only set feature-set to one shard.  Therefore plug-in only work for feature store on one shard.  Is it possible to make feature and model store  on multiply shards?

**Comment by nomoa** [comment]
Unless I'm misunderstanding your use case I don't think that setting `number_of_shards` will help.
How many feature/featureset/model do you have?
How many elasticsearch nodes do you have?
How do you see that .ltrstore at shard 0 is `busy`?

If you want a `featureset` to spread accross multiple shards then you need to increase the `number of replicas` not the `number of shards`.

Additionally featureset & models are cached so a node should load them only once from the shard. If you have too many or too large featureset/models perhaps the cache is always invalidated hitting the shard very often. See [how caching work](https://elasticsearch-learning-to-rank.readthedocs.io/en/latest/advanced-functionality.html#model-caching) to tune its value.

**Comment by softwaredoug** [comment]
Hi @xianing66 - going to close this issue. But don't feel free to reopen if @nomoa didn't sufficiently answer your question. I think for most use cases we would not need sharding of the index storing features/models. I think the "official" recommendation would be to clean up models after a while

Feel free to reach out to us on http://o19s.com/slack in the Elastic LTR channel if you need to chat with the contributors about any issues
