### ISSUE TITLE
版本问题

### ISSUE THREAD

**Issue by 904766993** [o19s/elasticsearch-learning-to-rank#225]
目前用6版本的能支持es7版本吗

**Comment by softwaredoug** [comment]
From google translate: 

> Can I use the 6 version to support the es7 version?

To use this plugin with ES 7, you need  to install the ES 7 version. Plugins built for 6.x won't work for 7.x in the Elasticsearch ecosystem. Please clarify if this is what you're asking though (and likely google translate is doing a poor job, if you're able to post your question in English it would help a lot)

**Comment by softwaredoug** [comment]
Hopefully that helped @904766993 ... feel free to reopen if needed
