### ISSUE TITLE
ltr_log is broken for query with innert_hits

### ISSUE THREAD

**Issue by taoyyu** [o19s/elasticsearch-learning-to-rank#226]
ltr_log seems broken for query with inner_hits
I got an error like 
> "No query named logged_featureset found"

I can reproduce the issue in the following way.
Test Environment
elasticsearch version: 7.0.1
ltr plugin version: built from master

1. Create test Index with nested fields
`curl -X PUT "localhost:9200/test" -H 'Content-Type: application/json' -d'
{
	"settings": {
		 "number_of_replicas": 0
	},
	"mappings": {
			"properties": {
				"group_name": {"type": "text"},
				"years": {"type": "double"},
				"user": {
					"type": "nested"
				}
			}
		}
}
'`

2. Index a document
`curl -X POST "localhost:9200/test/_doc/1" -H 'Content-Type: application/json' -d'
{
	"group_name": "A",
	"years": 10,
	"user": [
		{
			"name": "B",
			"age": 20
		},
		{
			"name": "C",
			"age": 25
		}
	]
}'`

3. Create a simple LTR featureset
`curl -XPOST "localhost:9200/_ltr/_featureset/test_featureset" -H 'Content-Type: application/json' -d'
{
   "featureset": {
        "features": [
            {
                "name": "years",
                "params": [],
                "template_language": "script_feature",
                "template": {
                    "lang": "painless",
                    "source": "doc['\''years'\''].value"
                }
            }
        ]
   }
}'`

4. Create a simple model
`curl -XPOST "localhost:9200/_ltr/_featureset/test_featureset/_createmodel" -H 'Content-Type: application/json' -d'
{
	"model": {
		"name": "test_model",
		"model": {
			"type": "model/linear",
			"definition": "{\"years\": 1.0}"
		}
 	}
 }'`

5. Run a query with inner_hits
`curl -XPOST "localhost:9200/test/_search" -H 'Content-Type: application/json' -d'
{
	"query": {
		"bool": {
			"must": [
				{
					"nested": {
						"path": "user",
						"query": {
							"bool": {
								"filter": [
									{
										"term": {
											"user.age": 20
										}
									}
								]
							}
						},
						"inner_hits": {
							"sort": [
								{
									"user.age": {"order": "desc"}
								}
							]
						}
					}
				},
				{
					"sltr": {
						"model": "test_model",
						"params": {},
						"_name": "logged_featureset"
					}
				}
			]
		}
	},
	"ext": {
		"ltr_log": {
			"log_specs": [
				{
					"name": "features",
					"named_query": "logged_featureset"
				}
			]
		}
	}
}`

I got error 

> {"error":{"root_cause":[{"type":"illegal_argument_exception","reason":"No query named [logged_featureset] found"}],"type":"search_phase_execution_exception","reason":"all shards failed","phase":"query","grouped":true,"failed_shards":[{"shard":0,"index":"test","node":"hKCZockYSouUULbOrz9Unw","reason":{"type":"illegal_argument_exception","reason":"No query named [logged_featureset] found"}}],"caused_by":{"type":"illegal_argument_exception","reason":"No query named [logged_featureset] found","caused_by":{"type":"illegal_argument_exception","reason":"No query named [logged_featureset] found"}}},"status":400}

The query works fine if I remove the ext part or remove the inner_hits part in my query

The issue seems to be in inner_hits fetch phase,  the code tries to run the LoggingFetchSubPhase. However, in
https://github.com/o19s/elasticsearch-learning-to-rank/blob/8ab104ed5e97333548e06baa97da8a47ed3668d1/src/main/java/com/o19s/es/ltr/logging/LoggingFetchSubPhase.java#L52
the ext is not null for InnerHitSubContext.
But in 
https://github.com/o19s/elasticsearch-learning-to-rank/blob/8ab104ed5e97333548e06baa97da8a47ed3668d1/src/main/java/com/o19s/es/ltr/logging/LoggingFetchSubPhase.java#L61
the namedQueries is for nested query which does not have logged_featureset. 
This caused the error here
https://github.com/o19s/elasticsearch-learning-to-rank/blob/8ab104ed5e97333548e06baa97da8a47ed3668d1/src/main/java/com/o19s/es/ltr/logging/LoggingFetchSubPhase.java#L127

I got a temporary workaround like 
https://github.com/taoyyu/elasticsearch-learning-to-rank/commit/420bff623df57b00e520c0887747fb3b17b07c2a#diff-56f044d4495cd1bd9ff1e9b6e4eb2c5aR63 to just ignore logging when it is fetching innert hits since I don't need ltr for innert hits.

**Comment by umeshdangat** [comment]
The workaround seems fine to me @taoyyu . Might be good to check with others, maybe @nomoa and @softwaredoug?
  We are using nested queries at Yelp and have been running into this issue. If you folks think patch is reasonable we can write some tests and PR it.

**Comment by nomoa** [comment]
Looks good to me as well!

**Comment by taoyyu** [comment]
Thanks @umeshdangat @nomoa . I added some tests and submitted a PR for this. Let me know if you have any issues.
