### ISSUE TITLE
Reliable CI environment

### ISSUE THREAD

**Issue by softwaredoug** [o19s/elasticsearch-learning-to-rank#229]
Related to #224, we need a reliable CI environment. Default CircleCI with its base containers hasn't been cutting it (due to lack of agressively updating their JDK images as fast as ES does, and limited RAM given ES build pipelines needs). 

We need
1. Ability to control the JDK version on an installed environment to keep up with aggressive Elasticsearch upgrade cycle 
2. Ability to run ./gradlew clean check and all the various integration tests, spawned JVMs to build an ES cluster, etc without consuming memory (Circle CI only gives you 4 GB, which is rough for an ES cluster)
3. Stays within the approved way of fully building Elasticsearch plugins  (`gradle clean check`) which means spawning a full cluster for integration tests
4. Ability to display some kind of 'tests failed/passed' badge on the github page
5. Consistently reflects developer's local runs of unit tests without weird cloud environment errors (like error 137)

## What we've tried

We have attempted to do this by creating a container in #228 by creating our own container. We have fiddled with various memory settings running gradle, and limited the number of workers to 1. We tried both ubuntu and lighter alpine based linux containers to try to lower system needs for RAM.

However, in CircleCI, this fails with error 137 frequently. Research into this error with gradle/circle seems to indicate this is due to lack of sufficient resources. The error does not occur when we run the task locally `circleci local execute --job build`. That task passes consistently locally. When 137 does occur, it occurs randomly in the process of running tests, at no consistent location.

## Potential solutions

- Build our own CI pipeline that basically pulls down a docker container, checks out the code, and runs the tests in a beefier box... ie spin up some cloud resources, etc
- OSC pays for CircleCI for ES LTR to get more resources to build the plugin (do we pay for Circle on Quepid @epugh ?)
- Switch to Travis (which honestly seems simpler for what we want, just run the dang tests, nothing fancier)
- Continue tinkering with Circle, get someone that knows what they're doing to look at it

**Comment by epugh** [comment]
@softwaredoug right now we pay the 50/month plan for CircleCI that gives us unlimited "build minutes" across two containers/builds simultaneously.  We could easily add this project to the o19s circleci build plan, however, I don't know if that changes things unless we move up in `resource_class`: https://circleci.com/docs/2.0/configuration-reference/#resource_class    I will open a support ticket to find out pricing.    

Maybe try out Travis, see how it works, and if that solves things, great.   We don't have complex CI/CD processes built around CircleCI that would make switching hard.

**Comment by softwaredoug** [comment]
Travis just seems to be working pretty reliably... PR #231 changes from travis -> circle
