### ISSUE TITLE
Getting 403 Forbidden on 5.3.0 download link

### ISSUE THREAD

**Issue by AaronME14** [o19s/elasticsearch-learning-to-rank#23]
curl -I http://es-learn-to-rank.labs.o19s.com/ltr-query-0.1.1.es5.3.0.zip

> HTTP/1.1 403 Forbidden
> x-amz-error-code: AccessDenied
> x-amz-error-message: Access Denied
> x-amz-request-id: E871A1B78B77A821
> x-amz-id-2: uLiGTk/zq5ptDSP/bR5t5ZAziB15saBMCVBkEiby/KsNKRy9n0igclrputPSRTE4/Kyt6Yjwiuo=
> Transfer-Encoding: chunked
> Date: Thu, 06 Apr 2017 18:33:53 GMT
> Server: AmazonS3

**Comment by epugh** [comment]
Okay, the reason it didn't work is that there is another `-` in the url.  Try

http://es-learn-to-rank.labs.o19s.com/ltr-query-0.1.1-es5.3.0.zip

Having said that, it's still way too much magic to figure out these URL's!!!!!!

**Comment by epugh** [comment]
Here is a tool for directory listings..  http://hatim.eu/2014/05/26/directory-listing-in-s3-static-website/
