### ISSUE TITLE
Plugin Release for Elasticsearch 7.2.0

### ISSUE THREAD

**Issue by luto65** [o19s/elasticsearch-learning-to-rank#230]
It would be great if one could use ltr with Elasticsearch 7.2

**Comment by softwaredoug** [comment]
Thanks for the poke - I'll give it a shot and see what errors crop up in the build

PS don't hesitate to pull it down and build it yourself. If you get deep into this plugin. An ES upgrade as an easy way to get listed as a contributor :)

**Comment by bannima** [comment]
> 

can you share the elasticsearch learning-to-rank plugin for ES 7.2.0? I can't find in[ prebuit versions](https://github.com/o19s/elasticsearch-learning-to-rank/releases)
