### ISSUE TITLE
demo instructions seemingly out of sync with prepare.py

### ISSUE THREAD

**Issue by mooreniemi** [o19s/elasticsearch-learning-to-rank#233]
Currently the [demo instructions say to run `prepare.py`](https://github.com/o19s/elasticsearch-learning-to-rank//tree/master/demo/#download-the-tmdb-data--ranklib-jar) but the [download of `tmdb.json` is commented out](https://github.com/o19s/elasticsearch-learning-to-rank/blob/master/demo/prepare.py#L33).

Should this be uncommented, the demo instructions updated, or something else? Happy to fork and do it myself if you clarify the intent.

**Comment by softwaredoug** [comment]
Thanks for pointing this out @mooreniemi 

@jettro - I can git blame and it seems maybe this is leftover or accidentally committed from an older PR? See this diff: 

https://github.com/o19s/elasticsearch-learning-to-rank/commit/8cebdfa5fd2323edda074ab7027c434532b1f6f7

**Comment by jettro** [comment]
Good catch, I agree that it must be a mistake when changing the name of the jar. Will clean the commented lines and re-establish the tmdb download.

**Comment by softwaredoug** [comment]
Fixed in #233
