### ISSUE TITLE
Script evaluated differently in LTR?

### ISSUE THREAD

**Issue by peterdm** [o19s/elasticsearch-learning-to-rank#24]
I have a sample painless script which compares two static dates.  If I run it inside `script_fields` I see the value I expect.  However if I run it as a `script` query input to LTR, I get 1.  

Baffled!

**Test Setup:**

```
POST _scripts/ranklib/dummy
{
  "script": "## LambdaMART\n## No. of trees = 1\n## No. of leaves = 10\n## No. of threshold candidates = 256\n## Learning rate = 0.1\n## Stop early = 100\n\n<ensemble>\n <tree id=\"1\" weight=\"0.1\">\n  <split>\n   <feature> 1 </feature>\n   <threshold> 0.45867884 </threshold>\n   <split pos=\"left\">\n    <feature> 1 </feature>\n    <threshold> 0.0 </threshold>\n    <split pos=\"left\">\n     <output> -2.0 </output>\n    </split>\n    <split pos=\"right\">\n     <output> -1.3413081169128418 </output>\n    </split>\n   </split>\n   <split pos=\"right\">\n    <feature> 1 </feature>\n    <threshold> 0.6115718 </threshold>\n    <split pos=\"left\">\n     <output> 0.3089442849159241 </output>\n    </split>\n    <split pos=\"right\">\n     <output> 2.0 </output>\n    </split>\n   </split>\n  </split>\n </tree>\n</ensemble>"
}  

POST /test/empty/
{}
    
GET /test/empty/_search
{
  "query": {
    "match_all": {}
  }
}
```

**Query to Reproduce Error:**

```
GET /test/empty/_search?explain=true
{
  "query": {
      "match_all": {}
  },
  "script_fields": {
      "days_between": {
          "script": {
              "params": {
                  "search_timestamp": "2017-03-23T00:00:00.000Z",
                  "compare_to": "2017-03-18T04:34:15.606Z"
              },
              "lang": "painless",
              "inline": "return ChronoUnit.DAYS.between(Instant.parse(params.compare_to), Instant.parse(params.search_timestamp))"
          }
      }
  },
  "rescore": {
      "query": {
          "rescore_query": {
              "ltr": {
                  "model": {
                      "stored": "dummy"
                  },
                  "features": [
                      {
                          "script": {
                              "_name": "days_between",
                              "script": {
                                "params": {
                                    "search_timestamp": "2017-03-23T00:00:00.000Z",
                                    "compare_to": "2017-03-18T04:34:15.606Z"
                                },
                                "lang": "painless",
                                "inline": "return ChronoUnit.DAYS.between(Instant.parse(params.compare_to), Instant.parse(params.search_timestamp))"
                            }
                          }
                      }
                  ]
              }
          }
      }
  }
}
```

For me (5.3.0_0.1.0) the result comes out:

`fields.days_between = [ 4 ]`
`_explaination.details[1].details[0].details[0].details[0].value = 1`

**Comment by softwaredoug** [comment]
@peterdm

A `script` query doesn't actually return a score (it always returns 1 or a 0). I think this is similar to the other issue we discussed. A `function_score_query` appears to work:

POST _scripts/ranklib/dummy
{
  "script": "## LambdaMART\n## No. of trees = 1\n## No. of leaves = 10\n## No. of threshold candidates = 256\n## Learning rate = 0.1\n## Stop early = 100\n\n<ensemble>\n <tree id=\"1\" weight=\"0.1\">\n  <split>\n   <feature> 1 </feature>\n   <threshold> 0.45867884 </threshold>\n   <split pos=\"left\">\n    <feature> 1 </feature>\n    <threshold> 0.0 </threshold>\n    <split pos=\"left\">\n     <output> -2.0 </output>\n    </split>\n    <split pos=\"right\">\n     <output> -1.3413081169128418 </output>\n    </split>\n   </split>\n   <split pos=\"right\">\n    <feature> 1 </feature>\n    <threshold> 0.6115718 </threshold>\n    <split pos=\"left\">\n     <output> 0.3089442849159241 </output>\n    </split>\n    <split pos=\"right\">\n     <output> 2.0 </output>\n    </split>\n   </split>\n  </split>\n </tree>\n</ensemble>"
}  

POST /test/empty/
{}
    
GET /test/empty/_search
{
  "query": {
    "match_all": {}
  }
}

GET /test/empty/_search?explain=true
{
   "query": {
      "match_all": {}
   },
   "script_fields": {
      "days_between": {
         "script": {
            "params": {
               "search_timestamp": "2017-03-23T00:00:00.000Z",
               "compare_to": "2017-03-18T04:34:15.606Z"
            },
            "lang": "painless",
            "inline": "return ChronoUnit.DAYS.between(Instant.parse(params.compare_to), Instant.parse(params.search_timestamp))"
         }
      }
   },
   "rescore": {
      "query": {
         "rescore_query": {
            "ltr": {
               "model": {
                  "stored": "dummy"
               },
               "features": [
                  {
                     "function_score": {
                        "_name": "days_between",
                        "functions": [
                           {
                              "script_score": {
                                 "script": {
                                    "params": {
                                       "search_timestamp": "2017-03-23T00:00:00.000Z",
                                       "compare_to": "2017-03-18T04:34:15.606Z"
                                    },
                                    "lang": "painless",
                                    "inline": "return ChronoUnit.DAYS.between(Instant.parse(params.compare_to), Instant.parse(params.search_timestamp))"
                                 }
                              }
                           }
                        ]
                     }
                  }
               ]
            }
         }
      }
   }
}


















GET /tmdb/movie/_search?q=title:creed&_source=false&stored_fields=title&size=10

GET /

GET _scripts/ranklib/test_6

POST tmdb/movie/_search 
{
    "query": {
          "match": {
              "title": "space jam"
          }
    },
    "stored_fields": "title"
    
}


POST tmdb/movie/_search
{
  "explain": true,
   "query": {
      "ltr": {
         "model": {
            "stored": "test_6"
         },
         "features": [
            {
               "match": {
                  "title": {
                      "query": "rocky",
                      "_name": "rocky_query"
                  }
                  
               }
            },
            {
               "multi_match": {
                  "query": "rocky",
                  "fields": [
                     "overview",
                     "genres.name",
                     "title",
                     "tagline",
                     "belongs_to_collection.name",
                     "cast.name",
                     "directors.name"
                  ],
                  "tie_breaker": 1,
                  "type": "cross_fields"
               }
            },
            {"match": {"title": "no_matchy"}}
         ]
      }
   }
}
   

POST tmdb/movie/_search
{
   "query": {
      "match": {
         "_all": "rocky"
      }
   },
   "rescore": {
      "window_size": 500,
      "query": {
         "rescore_query": {         
            "ltr": {
               "model": {
                  "stored": "dougs_model"
               },
               "features": [
                  {
                     "match": {
                        "title": {
                            "_name": "title_query",
                            "query": "rocky"
                        }
                     }
                  },
                  {
                     "multi_match": {
                        "query": "rocky",
                        "fields": [
                           "overview",
                           "genres.name",
                           "title",
                           "tagline",
                           "belongs_to_collection.name",
                           "cast.name",
                           "directors.name"
                        ],
                        "tie_breaker": 1,
                        "type": "cross_fields"
                     }
                  }
               ]
            }
         }
      }
   }
}



GET _scripts/ranklib/test


DELETE snag

PUT snag
{
    "mappings": {
        "jerbs": {
            "properties": {
                "fextures": {
                   "type": "string",
                   "fielddata": true
            
                }
                }
        
        }
    }
}

PUT snag/jerbs/1 
{
    "title": "Ikea Meatball Maker",
    "zip_code": 22903,
    "fextures": ["retail", "food_prep"]
}

PUT snag/jerbs/2 
{
    "title": "Abercrombie",
    "zip_code": 22903,
    "fextures": ["retail", "clothing"]
}

PUT snag/jerbs/3 
{
    "title": "The Gap Manager",
    "zip_code": 22903,
    "fextures": ["retail", "clothing", "manager"]
}


PUT snag/jerbs/4 
{
    "title": "Pier I Cashier",
    "zip_code": 22903,
    "fextures": ["retail", "furniture", "cashier"]
}


PUT snag/jerbs/10
{
    "title": "Burger King",
    "zip_code": 22904,
    "fextures": ["food_prep_l1"]
}


PUT snag/jerbs/11
{
    "title": "Taco Bell Cook",
    "zip_code": 22904,
    "fextures": ["food_prep_l2"]
}

PUT snag/jerbs/12
{
    "title": "McDonalds Cashier",
    "zip_code": 22904,
    "fextures": ["food_prep_l1", "cashier"]
}

```
GET /test/empty/_search?explain=true
{
   "query": {
      "match_all": {}
   },
   "script_fields": {
      "days_between": {
         "script": {
            "params": {
               "search_timestamp": "2017-03-23T00:00:00.000Z",
               "compare_to": "2017-03-18T04:34:15.606Z"
            },
            "lang": "painless",
            "inline": "return ChronoUnit.DAYS.between(Instant.parse(params.compare_to), Instant.parse(params.search_timestamp))"
         }
      }
   },
   "rescore": {
      "query": {
         "rescore_query": {
            "ltr": {
               "model": {
                  "stored": "dummy"
               },
               "features": [
                  {
                     "function_score": {
                        "_name": "days_between",
                        "functions": [
                           {
                              "script_score": {
                                 "script": {
                                    "params": {
                                       "search_timestamp": "2017-03-23T00:00:00.000Z",
                                       "compare_to": "2017-03-18T04:34:15.606Z"
                                    },
                                    "lang": "painless",
                                    "inline": "return ChronoUnit.DAYS.between(Instant.parse(params.compare_to), Instant.parse(params.search_timestamp))"
                                 }
                              }
                           }
                        ]
                     }
                  }
               ]
            }
         }
      }
   }
}

```

**Comment by softwaredoug** [comment]
@peterdm safe to close?

**Comment by peterdm** [comment]
Yup.  Thanks.
