### ISSUE TITLE
How to upload my model

### ISSUE THREAD

**Issue by PeterMen** [o19s/elasticsearch-learning-to-rank#240]
Is there a API doucument that tell me how to upload my model and query with my model.

I have an error when I try upload my model 
![image](https://user-images.githubusercontent.com/18695024/63997536-5fa51080-cb31-11e9-8d7f-9adc84d46817.png)
What's wrong?

**Comment by softwaredoug** [comment]
Hi did you do a 

```
PUT _ltr
```

first? This initializes the default feature store

**Comment by softwaredoug** [comment]
Going to close, but feel free to reopen!
