### ISSUE TITLE
Support ltr es 7.3.0

### ISSUE THREAD

**Issue by WillianFuks** [o19s/elasticsearch-learning-to-rank#244]
Hello,

Is it possible to also offer support for ltr plugin for elasticsearch version 7.3.0?

As we are using a docker environment for building the models we ended up finding this conflicting versions issue, if we had this official support we'd be able to more easily replicate the building steps for the entire team.

Thanks,

Will

**Comment by jillesvangurp** [comment]
The 7.3.1 version was released a few days ago. Probably if you need 7.3.0, the fastest/easiest is to simply change the 7.3.1 with 7.3.0 everywhere and do a local build and install that. Look at my commit that updated the version numbers: https://github.com/o19s/elasticsearch-learning-to-rank/commit/a4624810aa9021c3c4eeb5b2bc008724b6b464d4

reverting that should allow you to build for 7.3.0

**Comment by WillianFuks** [comment]
Hi @jillesvangurp ,

Thanks for the reference, will use it here.

Best,

Will
