### ISSUE TITLE
Running as a standalone tool, not a plugin

### ISSUE THREAD

**Issue by bilbof** [o19s/elasticsearch-learning-to-rank#246]
AWS Elasticsearch does not support custom plugins. Are there any plans to make this plugin a standalone tool that one can run against Elasticsearch, but not as a plugin?

Is there an existing way to make use of Elasticsearch Learning to Rank without installing it as a plugin?

Thank you!

**Comment by ebernhardson** [comment]
The architecture of this project depends heavily on the way it integrates with elasticsearch, and uses elasticsearch to store and calculate features. A service that runs external to elasticsearch would require a rather different architecture than we have here. While a standalone LTR solution could certainly be developed, I don't see it being done with this code base.

**Comment by bilbof** [comment]
Thanks @ebernhardson, it felt like a long shot. I appreciate your quick response!
