### ISSUE TITLE
How can I get document's field values on scorer() function of RankerScorer class?

### ISSUE THREAD

**Issue by toanmxpixta** [o19s/elasticsearch-learning-to-rank#249]
Hi, I have an index like this.
ES version: 7.3.1
```
PUT my_index
{
  "mappings": {
    "properties": {
      "my_vector": {
        "type": "integer"
      },
      "my_text" : {
        "type" : "keyword"
      }
    }
  }
}
```
```
PUT my_index/_doc/1
{
  "my_text" : "text1",
  "my_vector" : [0.5, 10, 6]
}
```

I want to get `my_vector` field value to calculate my custom formula. In `scorer()` function in RankerScorer class, I'm trying to calling `context.reader().getPointValues("my_vector")` or `context.reader().document(docID()).getField("my_vector")` to get the value but still can't what I want to get. 

https://github.com/o19s/elasticsearch-learning-to-rank/blob/master/src/main/java/com/o19s/es/ltr/query/RankerQuery.java#L298

How can I get document field value in `score()` function of `RankerScorer` class?

Thanks a lot!

**Comment by nomoa** [comment]
Hi, RankerScorer is a generic scorer meant to collect feature scores and assemble a FeatureVector to be fed into a Ranker, it is not meant to do any calculation.

What you want (I think) is to write a custom lucene query.

**Comment by toanmxpixta** [comment]
@nomoa Thank you so muck for your answer :bowing_man: 

> What you want (I think) is to write a custom lucene query.

Yes, It is actually my case. I think I need to write new custom script score query like this. 

```
GET my_index/_search
{
  "query": {
    "script_score": {
      "query" : {
        "match_all": {}
      },
      "script": {
        "source": "myCustomCalculation(doc['my_vector'])",
         "params": {
          "query_vector": [1, 2, 3]
        }
      }
    }
  }
}
```
