### ISSUE TITLE
How to set True/False fields as features?

### ISSUE THREAD

**Issue by katebsaber96** [o19s/elasticsearch-learning-to-rank#250]
Hi everyone,
I am working with product documents which have a True/False field indicating their category (i.e accessory). I know that this field carries a lot of information on the ranking mechanism however I'm not sure how to build a query to use a true false field as a feature. I would grateful to have your opinions.
Thanks in advance

**Comment by softwaredoug** [comment]
Hi @katebsaber96 were you able to solve this? Sorry for getting back to you so late
