### ISSUE TITLE
ES 6.6.2 -> LTR Build Request

### ISSUE THREAD

**Issue by Phoenix9867** [o19s/elasticsearch-learning-to-rank#253]
Hi, i'd like to get a Build for Elasticsearch Version 6.6.2.
Thank you for your great tool!

**Comment by softwaredoug** [comment]
Hi @Phoenix9867! I noticed we jumped from 6.5 to 6.7 ES. So we don't currently have a 6.6 branch. If you want, you could take the 6.5 branch, change the version numbers in `build.gradle` to 6.6 and rebuild it. If you did this and wanted to send us a PR to a es_6_6 branch we'd probably take it!

**Comment by Phoenix9867** [comment]
i tried to push the changes to a new 6.6. branch, but it seems that i have to the right permissions to do that. So here is the build zip file for 6.6:
[ltr-1.1.0-es6.6.0.zip](https://github.com/o19s/elasticsearch-learning-to-rank/files/3830704/ltr-1.1.0-es6.6.0.zip)
Thank you a lot for your effort 👍
