### ISSUE TITLE
ES 6.8.0 -> LTR Build Request

### ISSUE THREAD

**Issue by DAVIDFlavien** [o19s/elasticsearch-learning-to-rank#257]
Hi, do you mind publishing a build for Elasticsearch Version 6.8.0.

I tried to adjust the version to build for this specific version but it did not work out.

Thanks!

**Comment by softwaredoug** [comment]
Hi @DAVIDFlavien we don't. There's probably various (hopefully minor) build issues. We would welcome a PR to an es_6_8 branch if you had a chance to work through those issues.

To do this, you would want to start with the branch es_6_7 branch and change the build version to 6.8

**Comment by softwaredoug** [comment]
I went ahead and cut a build for 6.8.0, please open an issue if you have any issues with the build.
