### ISSUE TITLE
ERROR: This plugin was built with an older plugin structure.

### ISSUE THREAD

**Issue by lasagar** [o19s/elasticsearch-learning-to-rank#258]
Do you have latest plugin for version 6.4

**Comment by lasagar** [comment]
ERROR: This plugin was built with an older plugin structure. Contact the plugin author to remove the intermediate "elasticsearch" directory within the plugin zip.

**Comment by softwaredoug** [comment]
When I look in the file listing, I see builds for ES 6.4.1 and 6.4.2. Which are you having problems with. So yes there are 6.4 builds.

For your error, I would please ask you include more information.  Please list a full set of detailed instructions to recreate the issue. It's possible a 6.4.x build is not working correctly, but we need to know

1. What version of ES you are trying to install it in
2. What command exactly you're running to install the plugin
3. What the exact output is

Thanks!

**Comment by lasagar** [comment]
Hi Doug,

Thank you for the response. 
 
I am running in ES 6.4.0 
I am following the instructions from https://github.com/o19s/elasticsearch-learning-to-rank/tree/master/demo <https://github.com/o19s/elasticsearch-learning-to-rank/tree/master/demo>. 
Following is the command used: ./bin/elasticsearch-plugin install http://es-learn-to-rank.labs.o19s.com/ltr-1.0.0-es6.1.2.zip <http://es-learn-to-rank.labs.o19s.com/ltr-1.0.0-es6.1.2.zip>

Following is the error: 
-> Downloading http://es-learn-to-rank.labs.o19s.com/ltr-1.0.0-es6.1.2.zip <http://es-learn-to-rank.labs.o19s.com/ltr-1.0.0-es6.1.2.zip>
[=================================================] 100%
ERROR: This plugin was built with an older plugin structure. Contact the plugin author to remove the intermediate "elasticsearch" directory within the plugin zip.
[esp@srch-dev-136 elasticsearch]$

Can you assist me on where do I find the plugin for 6.4.0. 


Thanks
Lavanya

**Comment by TactiC** [comment]
You can download 6.4.x version from here http://es-learn-to-rank.labs.o19s.com/

**Comment by lasagar** [comment]
> You can download 6.4.x version from here http://es-learn-to-rank.labs.o19s.com/

Thank you

**Comment by softwaredoug** [comment]
To echo @TactiC, you appear to be downloading the incorrect plugin version for your version of Elasticsearch (notice the version es6.1.2 in your command). You'll need the 6.4.0 version.

I noticed there's not a 6.4.0 build. I have built one and uploaded it. You should be able to install into 6.4.0 with the command:

```
./bin/elasticsearch-plugin install http://es-learn-to-rank.labs.o19s.com/ltr-1.1.0-es6.4.0.zip
```

Going go ahead and close. Don't hesitate to reopen/create a new issue if you have any issues with that build.

**Comment by lasagar** [comment]
> To echo @TactiC, you appear to be downloading the incorrect plugin version for your version of Elasticsearch (notice the version es6.1.2 in your command). You'll need the 6.4.0 version.
> 
> I noticed there's not a 6.4.0 build. I have built one and uploaded it. You should be able to install into 6.4.0 with the command:
> 
> ```
> ./bin/elasticsearch-plugin install http://es-learn-to-rank.labs.o19s.com/ltr-1.1.0-es6.4.0.zip
> ```
> 
> Going go ahead and close. Don't hesitate to reopen/create a new issue if you have any issues with that build.

thank you

**Comment by lasagar** [comment]
Hi Doug

Can I get a plugin for 7.5.0 version?

**Comment by lasagar** [comment]
Can I get a plugin for 7.5.0 version?
