### ISSUE TITLE
Please publish a version for Elasticsearch 7.5.0

### ISSUE THREAD

**Issue by gtsoukas** [o19s/elasticsearch-learning-to-rank#260]
I have tried various versions of the JDK, but did not manage to build it by myself :(

**Comment by lasagar** [comment]
I am facing similar issue

**Comment by softwaredoug** [comment]
Thanks for giving it a go @gtsoukas - there is a PR #259 for upgrading to 7.4 that needs to happen first. That's in progress. After that we'll work on 7.5. Apologies we are a few versions behind.

**Comment by softwaredoug** [comment]
The 7.4 is upgraded, next we'll work on 7.5 when we get some time (though PRs always welcome!)

**Comment by lasagar** [comment]
Any update on 7.5.0

**Comment by gtsoukas** [comment]
Are there any thoughts on integrating the LTR plugin into the Elasticsearch releases as is the case with Solr? I am having a major issue in implementing LTR since production is on 7.5.0 and I need to use production index snapshots for LTR development which turn out to not be backward compatible with e.g. 7.4.x (contradicting ES documentation). I am afraid that by the time the plugin for 7.5.0 is ready, production will be on the next release and my LTR project will go from delay to delay. I am sorry for currently not having the skills and capacity to contribute code.

**Comment by divyanshumarwah** [comment]
I have version 7.5.1 in the production environment, when can we expect an LTR update for it.

**Comment by softwaredoug** [comment]
Hey @divyanshumarwah @gtsoukas the PR is ready for 7.5, #259. Haven't gotten around to releasing it, might get to it Friday. But please do feel free to pull that PR down, and rebuild things, it should be fine

**Comment by softwaredoug** [comment]
Hi @divyanshumarwah and @gtsoukas 7.5.0 and 7.5.1 have been uploaded. Thanks!

**Comment by lasagar** [comment]
> Hi @divyanshumarwah and @gtsoukas 7.5.0 and 7.5.1 have been uploaded. Thanks!

Thank you Doug

**Comment by gtsoukas** [comment]
> Hi @divyanshumarwah and @gtsoukas 7.5.0 and 7.5.1 have been uploaded. Thanks!

Thanks a lot Doug! Just installed it.

**Comment by divyanshumarwah** [comment]
Thanks a million, Doug!
