### ISSUE TITLE
Request cache not being used

### ISSUE THREAD

**Issue by brunoaguiar** [o19s/elasticsearch-learning-to-rank#269]
Hi,

It seems like when using the plugin the [shard request cache](https://www.elastic.co/guide/en/elasticsearch/reference/current/shard-request-cache.html#shard-request-cache) is never used.

This is causing massive performance issues in our applications, we generally have a 20% hit ratio in the request cache, which now needs to be computed for every request.

As for my understanding the guilty for not using the cache is [this line](https://github.com/o19s/elasticsearch-learning-to-rank/blob/master/src/main/java/com/o19s/es/ltr/query/StoredLtrQueryBuilder.java#L158)

When `context.getClient()` method is called , the request cache will be set to disabled.

Would it be possible to improve this behavior in the plugin?

Thanks

**Comment by softwaredoug** [comment]
This should be closed, no?
