### ISSUE TITLE
Upgrade 7.5.x maintenance versions

### ISSUE THREAD

**Issue by softwaredoug** [o19s/elasticsearch-learning-to-rank#276]
Elastic wants an exact version match for plugins, just an issue to go about cutting a new release

- Use the es_75 branch
- Change the versions in build.gradle to 7.5.2 and beyond
- Push changes up to es_75 branch (should hopefully just be versions)
- Build a version for each 
- Bug Doug to get S3 bucket permissions to upload latest if your name is Nathan Day

**Comment by nathancday** [comment]
Bump to 7.5.2 completed on the branch `es_7_5` and [the commit](https://github.com/o19s/elasticsearch-learning-to-rank/commit/b2a159fb25cf456372ca9334eb8d26adbd50ef72) has been cherr-picked to  `master`. Zip file uploaded to S3 bucket.
