### ISSUE TITLE
Please publish a version of LTR for Elasticsearch 7.6.0 

### ISSUE THREAD

**Issue by vishalnatani** [o19s/elasticsearch-learning-to-rank#277]

**Comment by thePanz** [comment]
@softwaredoug any updates here? :)

**Comment by nathancday** [comment]
We have it in our queue to cut an upgraded version of this plugin, hopefully this week.

**Comment by softwaredoug** [comment]
I will say that a big part of this project is keeping up with Elastic's builds (and the weaving refactorings of the ES codebase :) )... As this is a beefy plugin, we really do need as much community support as possible to help with the upgrades. It's not a terribly hard thing to get into if you are interested in contributing (there's some documentation we [wrote on upgrades here](https://github.com/o19s/elasticsearch-learning-to-rank/blob/master/CONTRIBUTING.md#upgrading-to-latest-elasticsearch-majorminor-version-ie-es_6_7). 

But in general, we do our best. As most of our clients don't run the latest and greatest Elasticsearch in prod, we don't always ourselves rush to do the upgrade. However, we recognize that folks want to experiment with LtR and new features in Elasticsearch, so do our best!
