### ISSUE TITLE
how to add document features and Query/User-Dependent Features?

### ISSUE THREAD

**Issue by tornadozou** [o19s/elasticsearch-learning-to-rank#28]
How to add document features and Query/User-Dependent Features both for the training stage and the reranking stage? can anyone give a demo during the use of the plugin

**Comment by softwaredoug** [comment]
- Document features can be added simply as a `function_score` query that pulls in say a field value. You can use the demo
- Query/User dependent can be done the same way, with paramaterized scripts using `function_score`

**Comment by epugh** [comment]
@tornadozou we are working on updating the demo for the 1.0 release of the plugin.  Please watch issue #62 for updates.

**Comment by epugh** [comment]
Thanks!
