### ISSUE TITLE
match_explorer documentation

### ISSUE THREAD

**Issue by lasagar** [o19s/elasticsearch-learning-to-rank#281]
I have a qn on the below documentation where it talks about match_explorer. Where can i get more information on the stats available to use, formula and how to use it. max_raw_df is working, rest of the other metrics mentioned are giving me invalid stat type
https://elasticsearch-learning-to-rank.readthedocs.io/en/latest/feature-engineering.html?highlight=match_explorer

**Comment by rtancman** [comment]
@lasagar good question! I have some ideas to put in documentation articles and papers to emphasize these features. My Idea is creating a topic in the documentation to explain some features and show others ways to training your model with good features. What do you think?

**Comment by lasagar** [comment]
> @lasagar good question! I have some ideas to put in documentation articles and papers to emphasize these features. My Idea is creating a topic in the documentation to explain some features and show others ways to training your model with good features. What do you think?

Sounds good. Also another qn, while creating the feature, should i apply the same boost as my search query for the fields. Will there be any additional impact to the model due to that?

**Comment by worleydl** [comment]
The types documented should work, also be sure to checkout the new https://elasticsearch-learning-to-rank.readthedocs.io/en/latest/advanced-functionality.html#termstat-query which allows for more custom formulas.  If you're still having trouble with match explorer feel free to bump the issue.
