### ISSUE TITLE
Add term position feature in match_explorer

### ISSUE THREAD

**Issue by rtancman** [o19s/elasticsearch-learning-to-rank#288]
We saw in [PostingsExplorerQuery.java#L86-L88](https://github.com/o19s/elasticsearch-learning-to-rank/blob/master/src/main/java/com/o19s/es/explore/PostingsExplorerQuery.java#L86-L88) one way to implement term position feature.

Is this important? Because we started to do that ;)

This feature is very important for us and we want to contribute to the project.

**Comment by worleydl** [comment]
Thanks for the PR!
