### ISSUE TITLE
Add possibility to normalize the average term position feature

### ISSUE THREAD

**Issue by MaquisW** [o19s/elasticsearch-learning-to-rank#295]
Relating to the new feature added in #288, we would like to add the possibility to normalize the average term position passing a parameter.

The actual `avg_raw_tf` is computed with the positions of all occurrences of the query terms, the idea is that this feature demonstrates how far, on average, the query terms are in the document. 
But in cases where just one or a few query terms occur in the document, it may have an advantage in calculating this average over documents with all query terms.

With that in mind, we have been thinking of adding the query terms that not occur in the document on the average computation with fake occurrence positions.
This fakes occurrences should penalize the average term position, considering that this document hasn't any occurrence of these terms, which must be bad for its score. 

Ideally, one way to penalize is to simulate that the fake occurrence happens at the end of the document. So, we could set the fakes occurrence position to a default value such as `size_of_the_document + 1`.

But, in some cases, small documents could continue to have an advantage, for this we have been thinking to also allow the feature to receive a parameter to use as a custom fake position.

**Comment by nathancday** [comment]
@worleydl do you think this was addressed with termStats?
