### ISSUE TITLE
Add classic idf multiplied by tf in match_explorer

### ISSUE THREAD

**Issue by rtancman** [o19s/elasticsearch-learning-to-rank#296]
We want to add new feature `idf_x_tf` in `match_explorer`. This feature is referenced in [Microsoft's LETOR](https://www.microsoft.com/en-us/research/project/letor-learning-rank-information-retrieval/).

-------------
_LETOR is a package of benchmark data sets for research on LEarning TO Rank, which contains standard features, relevance judgments, data partitioning, evaluation tools, and several baselines._
> https://arxiv.org/ftp/arxiv/papers/1306/1306.2597.pdf
> Tao Qin and Tie-Yan Liu. Introducing LETOR 4.0 Datasets, arXiv preprint arXiv:1306.2597.

**Comment by nomoa** [comment]
Not entirely convinced that the match_explorer is the right place for this kind of features. This query was designed to help surfacing low level features stored in lucene. I believe that the `derived_expression` feature of the plugin can be used for that. There's also an experimental feature we added in another [plugin](https://github.com/wikimedia/search-extra/blob/master/docs/simswitcher.md) that allows to experiment with different similarities (without having to close/reopen an index). Note that elastic also provides a nice way to create custom similarities using painless script (https://www.elastic.co/guide/en/elasticsearch/painless/current/painless-similarity-context.html).

**Comment by softwaredoug** [comment]
@worleydl gonna see if this is doable in a derived expression... 

I agree with the general principal if there was a way to script these various things (both the positional info & the raw idf tf math) then we would prefer that. It would give a lot of freedom to experiment with many / different types of features.

**Comment by rtancman** [comment]
@nomoa @softwaredoug I saw the [similarity module](https://www.elastic.co/guide/en/elasticsearch/reference/current/index-modules-similarity.html#index-modules-similarity) and I have some questions. We want to use BM25 scores in all fields but in rescore, we need to create features using TF and IDF. Is there a way to create this feature without change the BM25 scores by fields? 

I will test that with `weight_script` to check the score.

**Comment by worleydl** [comment]
@rtancman here's an example of creating custom formulas using the raw statistics via a script feature: https://gist.github.com/worleydl/4b3c7cf150185459aa538bc7f4f63a52

Regarding the BM25 question, you should be able to setup features that utilize the defined similarity for your index in conjunction with features that are using raw statistics from the match explorer.  The only caveat I see right now is that any statistics you wish to use in your custom formula need to be included in the feature set.

Also validation appears to be failing for the gist I linked, the expected values are generated when logging the features so I think this is a bug.  I'm having a colleague double-check to verify.

**Comment by rtancman** [comment]
@worleydl I know this feature `params.feature_vector` but this doesn't help us. We need to multiply each TF and IDF before the sum/mean/max/min. In that gist example, you are doing TF and IDF mean first and after that you multiple the results. It will give us the multiplication of the means (or sums, etc) of the TFs and IDFs  `[mean(TF) * mean(IDF)]`, and what we need is the mean (or sum, etc) of `TF * IDF` for each document `[mean(TF * IDF)]`, which is pointed out by LETOR.

**Comment by worleydl** [comment]
Okay that makes sense.  Let me think about this a little more.  I don't think it's currently achievable via a derived expression, you could probably get at the data with a big scripted feature but we may be able to make it more convenient to work with the raw values in scripts.

**Comment by worleydl** [comment]
Hi @rtancman,

We're kicking around the idea for a new query that would look like something like this:
```
"term_stat": {
    "expr": "avg(product(tf(), idf()))”,
    “similarity”: “classic”,
    "terms": {
        "title": "rambo rocky"
    }
}
```

Would you be able to work with something like this?  The main idea is to replace `type` in match_explorer with an expression and to get rid of passing in a query in favor of just passing in a list of terms per field.

**Comment by rtancman** [comment]
> Hi @rtancman,
> 
> We're kicking around the idea for a new query that would look like something like this:
> 
> ```
> "term_stat": {
>     "expr": "avg(product(tf(), idf()))”,
>     “similarity”: “classic”,
>     "terms": {
>         "title": "rambo rocky"
>     }
> }
> ```
> 
> Would you be able to work with something like this? The main idea is to replace `type` in match_explorer with an expression and to get rid of passing in a query in favor of just passing in a list of terms per field.

I really appreciate that! I will start to change this in PR #297 . Thanks for the idea!

**Comment by worleydl** [comment]
Just to be clear, this concept is still in development :)  I'm hoping to have something for review early next week.

**Comment by worleydl** [comment]
I was hoping I could get away with some beefier custom lucene expression functions but it's limited to double typed params/return values.   Unfortunately that won't let us easily get away with the one-liner expr I was suggesting.  I'm still experimenting with some concepts.  I will have more updates by Friday.

**Comment by worleydl** [comment]
Sorry for the wait, my estimate accuracy is abysmal with the quarantine stuff going on.  My current WIP is allowing a lucene expression low level in the PostingsExplorerQuery.  This should allow for experimentation with different formulas using the raw term statistics.  A caveat of this approach is that it would require grabbing all of the term statistics to inject them as variables within the lucene expression similar to how we do it with derived expressions.

The other thing I'm working on is decoupling the statistical function (max/min/avg) from what gets selected out of the term positions.  This would allow us to the minimum avg term position for example instead of min always being locked to the min term position.

**Comment by rtancman** [comment]
> Sorry for the wait, my estimate accuracy is abysmal with the quarantine stuff going on. My current WIP is allowing a lucene expression low level in the PostingsExplorerQuery. This should allow for experimentation with different formulas using the raw term statistics. A caveat of this approach is that it would require grabbing all of the term statistics to inject them as variables within the lucene expression similar to how we do it with derived expressions.
> 
> The other thing I'm working on is decoupling the statistical function (max/min/avg) from what gets selected out of the term positions. This would allow us to select the minimum avg term position for example instead of min always being locked to the min term position.

Do you need some help? Because this is very important for us in Jusbrasil. We put this change in a specific project here using PR #297 to check this feature. But I prefer your idea! Because it is more naturally in ltr project. What do you think?

**Comment by worleydl** [comment]
I could definitely use another set of eyes. I'll try to get my fork ready to share this evening.  Thanks!

**Comment by worleydl** [comment]
Resolved by TermStatQuery: https://elasticsearch-learning-to-rank.readthedocs.io/en/latest/advanced-functionality.html#termstat-query
