### ISSUE TITLE
Push ltr to maven repository

### ISSUE THREAD

**Issue by rtancman** [o19s/elasticsearch-learning-to-rank#298]
We have to use some builders in our project and we need to add this plugin in maven dependencies but it doesn`t exist there. We are looking for in https://mvnrepository.com/artifact/com.o19s.

**Comment by rjansen** [comment]
I have the same problem here.

**Comment by nathancday** [comment]
Hey coming back to this, sorry for the delay.

The idea of automating more of the release process came up around creating the zip files. This feels very similar to that, could either of you point me to a maven workflow for something like this?

**Comment by rtancman** [comment]
> Hey coming back to this, sorry for the delay.
> 
> The idea of automating more of the release process came up around creating the zip files. This feels very similar to that, could either of you point me to a maven workflow for something like this?

We need to use specific plugins builders to create a rescore query with ltr. Example:

```
import com.o19s.es.ltr.feature.store.index.IndexFeatureStore;
import com.o19s.es.ltr.query.StoredLtrQueryBuilder;
import com.o19s.es.ltr.ranker.parser.LtrRankerParserFactory;
import org.elasticsearch.index.query.MatchQueryBuilder;
import org.elasticsearch.index.query.QueryBuilder;
import org.elasticsearch.search.rescore.QueryRescorerBuilder;
import org.elasticsearch.search.rescore.RescorerBuilder;
```

Because of that, we need to add ltr in our `pom.xml`. I create a specific package here in nexus with ltr plugin to fix my problem.

**Comment by nathancday** [comment]
Great, that sounds like a reasonable solve. I wonder that would work for @rjansen 's situation.

We obviously haven't published to Maven in while, but we're open to adding a Travis (or Github actions) way to to do it

**Comment by pakio** [comment]
Hi all, I made some change for building scripts to make uploading maven repository possible. Could someone review my change?
I'm new to elasticsearch-ltr and trying to use our production env, but faced same issue.

**Comment by nathancday** [comment]
Absolutely, we will get a review this week. Thank you for contributing this
❤️
