### ISSUE TITLE
The ltr query vs sltr query

### ISSUE THREAD

**Issue by jngz-es** [o19s/elasticsearch-learning-to-rank#299]
I notice the ltr query is working which uses ES scripting functionality. Should ltr query be deprecated by sltr query? Looks like sltr query using ranklib is an upgraded version of ltr query.

**Comment by worleydl** [comment]
The `ltr` query supports a workflow in which you provide features and a model at query time.  This can be useful for debugging for some users.  Most users will probably prefer `sltr` in which features and models are stored inside of elastic.

If you haven't already please join the #es-learn-to-rank channel on relevancy.slack.com in case you have more questions.
