### ISSUE TITLE
ERROR: This plugin was built with an older plugin structure

### ISSUE THREAD

**Issue by ayush-1506** [o19s/elasticsearch-learning-to-rank#300]
Looks like the zip file linked in the readme [here](https://github.com/o19s/elasticsearch-learning-to-rank#installing) is outdated. Might be a good idea to replace this with a newer version, perhaps ltr-1.2.1-es7.6.2.zip ?

**Comment by ayush-1506** [comment]
(Should be a small change in the readme file. Let me know if you need me to open a PR)

**Comment by nathancday** [comment]
Thanks for flagging this, I'll make an edit to clarify.

**Comment by thePanz** [comment]
@nathancday would it make sense to build those packages in Githib and have them available here?

**Comment by nathancday** [comment]
That's an intriguing idea @thePanz. Do you have a specific tool in mind for the Github build process?

**Comment by thePanz** [comment]
@nathancday I have no specific tools in mind, but IIRC GitHub is already running the tests right?
It would allow us to build the zip there (maybe sign it too?) and upload the file to the release.
I remember GitHub has an API to do that

**Comment by thePanz** [comment]
see #316
