### ISSUE TITLE
Add _stats API to retreive statistics on plugin. 

### ISSUE THREAD

**Issue by adnapibar** [o19s/elasticsearch-learning-to-rank#302]
Currently, the plugin exposes a `_cachestats` API to get some information on the cache usage. It could be a good idea to provide a `stats` API which will provide an overall combined usage and performance statistics on the plugin, 

node level statistics including the cache statistics with more details (as mentioned in #140), e.g,

```
 "nodes" : {
    "IgWDUfzFRzW0FWAXM5FGJw" : {
      "timestamp": 1585250953737,
      "name": "elasticsearch1",
      "cache": {
        "feature": {
            "eviction_count": 0,
            "miss_count": 1,
            "hit_count": 2,
            "entry_count": 10,
            "memory_size_in_bytes": 200
        },
        "featureset": {
            "eviction_count": 0,
            "miss_count": 1,
            "hit_count": 2,
            "entry_count": 1,
            "memory_size_in_bytes": 300
        },
        "model": {
            "eviction_count": 1,
            "miss_count": 9,
            "hit_count": 10,
            "entry_count": 9,
            "memory_size_in_bytes": 2000
        }
      }
    },
    "y7YUQWukQEWOYbfdEq13hQ" : {
      ...
    }
  }
```

cluster wide information on the plugin such as overall health and information on stores, e.g.,

```
"status": "green",
"stores": {
    ".ltrstore": {
        "status": "green",
        "feature_count": 2,
        "feature_set_count": 1,
        "model_count" : 9
    },
  }
```

I'd like to know your views on this and any suggestions on other metrics (such as model performance) that might be helpful to add as part of the API.

**Comment by nathancday** [comment]
I like this idea a lot. I think it would be a huge improvement for visibility.

I'm not immediately sure what other metrics should be added, but would love input for other folks on what they'd like to see. Even exposing the eviction count would be a win to address #140

**Comment by nathancday** [comment]
Can not say thank you enough for the awesome contribution! Very much appreciated @adnapibar 🙇‍♂️
