### ISSUE TITLE
Add setting for enable/disable plugin

### ISSUE THREAD

**Issue by jngz-es** [o19s/elasticsearch-learning-to-rank#304]
I'd like to add a cluster setting for enable/disable plugin's functionalities.

**Comment by nathancday** [comment]
Can you point me to another plugin where this is done? Trying to figure out a common use case, right now it feels similar to node roles.

**Comment by jngz-es** [comment]
It's similar with https://github.com/opendistro-for-elasticsearch/anomaly-detection/pull/105.

**Comment by nathancday** [comment]
Thanks for sharing that ref. If this becomes desired by more folks we may consider developing it. In the mean time, if you feel like making a PR based on the AD work, that would be lovely. We are always happy to have new project contributors!
