### ISSUE TITLE
请问作者 java可以和这个集成吧？ 谢谢

### ISSUE THREAD

**Issue by zhanghengze** [o19s/elasticsearch-learning-to-rank#319]

**Comment by nathancday** [comment]
Translation: Can the author java be integrated with this? Thank you

I'm not sure I understand your issue. If you are talking about using a different versions of Java those requirement are set by Elasticsearch not the plugin. So we just have to keep up with the version they are requiring. 

我不确定我是否理解您的问题。如果您正在谈论使用其他版本的Java，则这些要求是由Elasticsearch而非插件设置的。因此，我们只需要跟上他们所需的版本即可。

**Comment by gallupliu** [comment]
Do you have plans to launch demo with java version?
