### ISSUE TITLE
Feature Store API: Store all/most as search templates

### ISSUE THREAD

**Issue by sstults** [o19s/elasticsearch-learning-to-rank#32]
May not be possible. Let's keep track of the roadblocks if that's the case so that we might revisit later.

**Comment by epugh** [comment]
@sstults can you elaborate more on this one?   Talking to @worleydl and not sure we grok what this one means!

**Comment by sstults** [comment]
@epugh, this ticket was created from the "Elasticsearch LTR version 1.0" roadmap in GoogleDocs, so maybe @softwaredoug or @nomoa can elaborate more.

https://docs.google.com/document/d/1_DWPmLi9oDem3QWxQAgKbqZ5F9oo0XXyHicsXmbWFDQ/edit#

**Comment by ebernhardson** [comment]
nomoa is taking a well deserved vacation, will be out until basically the beginning of next month.  I'm not 100% sure what this is, but the feature store has 3 ways of storing features: A plain un-parameterized elasticsearch query, a mustache template, or a lucene expression (taking the features from the other 2 as parameters).  

So, basically everything is a template unless you want to use something else. It seems "done" ?

**Comment by epugh** [comment]
Yep, sounds like it’s done barring some documentation covering those three approaches!

**Comment by softwaredoug** [comment]
I think this is done
