### ISSUE TITLE
es6.3.1集成插件 上传模型完用   sltr查询报错

### ISSUE THREAD

**Issue by zhanghengze** [o19s/elasticsearch-learning-to-rank#320]
![b1b1a076d11a64f903f79afa1561fb1](https://user-images.githubusercontent.com/66267248/87756664-e4794580-c83b-11ea-8d04-34542556e050.png)

**Comment by nathancday** [comment]
Your model is looking for `some_multiplier` in the feature template you have provided, when you created the model. It only sees `keywords` because that is what you are passing in the `params: {...}`. What happens if you change it to `some_multiplier` instead of `keywords`?

**Comment by nathancday** [comment]
创建模型时，您的模型正在提供的功能模板中寻找 `some_multiplier`。它只会看到 `keywords`，因为这就是您在 `params：{...}`中传递的内容。如果将其更改为 `some_multiplier` 而不是 `keywords`，会发生什么？
