### ISSUE TITLE
How to install the source code version of this plugin under ES source code?

### ISSUE THREAD

**Issue by charleswu52** [o19s/elasticsearch-learning-to-rank#329]
I am a novice and did not understand the tutorial, please advise me the detailed steps, thank you!

**Comment by nathancday** [comment]
Hi there,

Did you get a specific error message?

If you are on ES 7.9.0 today, you'd use:
`bin/elastic-plugins install https://s3.amazonaws.com/es-learn-to-rank.labs.o19s.com/ltr-plugin-v1.4.0-es7.9.0.zip`

-Nate

**Comment by charleswu52** [comment]
I have solved the problem. Thank you for your answer.
