### ISSUE TITLE
LTR plugin not working on elastic cloud

### ISSUE THREAD

**Issue by shah-sid-cutshort** [o19s/elasticsearch-learning-to-rank#331]
While trying to use LTR plugin of elasticsearch by making a PUT request to _ltr to initialize the , Ref - https://elasticsearch-learning-to-rank.readthedocs.io/en/latest/index.html on elastic cloud , It gives back an error saying -

```
{
  "status": 400,
  "error": {
    "index_uuid": "_na_",
    "index": "_ltr",
    "root_cause": [
      {
        "index_uuid": "_na_",
        "index": "_ltr",
        "reason": "Invalid index name [_ltr], must not start with '_', '-', or '+'",
        "type": "invalid_index_name_exception"
      }
    ],
    "type": "invalid_index_name_exception",
    "reason": "Invalid index name [_ltr], must not start with '_', '-', or '+'"
  }
}
```
The error is basically of an index naming rule but when the plugin is installed locally , it works correctly. The problem occurs only when the plugin is installed on elastic cloud. Elastic cloud gives a confirmation saying that your extension is installed but the route still doesn't work. Tried restarting the deployment after and it still the same.

**Comment by nathancday** [comment]
Thanks for reporting. We have not been testing against Elastic Cloud, but perhaps we should. 

For troubleshooting what version of ES are you running?

**Comment by shah-sid-cutshort** [comment]
Tested against 7.8.1
Production running on 7.5.2

**Comment by shah-sid-cutshort** [comment]
Closing the issue as it was resolved by elastic giving the access to upload plugins instead of just bundles.

**Comment by nathancday** [comment]
Was this access setting something you had to change? (Interested in documenting it for future Cloud users)
