### ISSUE TITLE
v1.5.3 es7.9.3 missing on the pre-built repo

### ISSUE THREAD

**Issue by KamyarGhajar** [o19s/elasticsearch-learning-to-rank#339]
It looks the pre-built plugin v1.5.3 es7.9.3 is missing on the pre-built repo. The installation documentation does not refer to download the plugin from github either and the build is not synced between the [pre-built site](http://es-learn-to-rank.labs.o19s.com) and github tags. What should be done?

**Comment by nathancday** [comment]
https://s3.console.aws.amazon.com/s3/object/es-learn-to-rank.labs.o19s.com/ltr-plugin-v1.5.3-es7.9.3.zip

**Comment by KamyarGhajar** [comment]
Thank you @nathancday I am using this link in the ES cluster to build the ES docker images now.
