### ISSUE TITLE
Filter and rescore with SLTR

### ISSUE THREAD

**Issue by hassaanseeker** [o19s/elasticsearch-learning-to-rank#341]
Guys I am trying to run the rescore the query when I have a particular id only then the model should rescore as below:

```
GET index/_search
{"query": {
      "nested": {
          "path": "name",
      
  
  "query": {
      "bool": {
      "must": [
      {"match": {
          "name.id": 5}
       }]
   }
  }
      }
  },
  "rescore": {
  	"window_size": 150,
      "query": {
        "rescore_query": {
          "nested": {
            "path": "name",
            "query": {
           "bool": {
             "filter": {
        "term" : { "name.id": 5}},
        "must": [{
          
            "sltr": {
                "params": {
                    "keywords": ""
                },
                "model": "test_8"
            }
        }]
             
           }
         }
      }
   }
 }
}
}
```
But
I get the below error:

{
  "error" : {
    "root_cause" : [
      {
        "type" : "illegal_state_exception",
        "reason" : "Child query must not match same docs with parent filter. Combine them as must clauses (+) to find a problem doc. docId=29675, class org.apache.lucene.search.ConjunctionScorer"
      },
      {
        "type" : "illegal_state_exception",
        "reason" : "Child query must not match same docs with parent filter. Combine them as must clauses (+) to find a problem doc. docId=29926, class org.apache.lucene.search.ConjunctionScorer"
      }
    ],
    "type" : "search_phase_execution_exception",
    "reason" : "all shards failed",
    "phase" : "query",
    "grouped" : true,
    "failed_shards" : [
      {
        "shard" : 0,
        "index" : "prelive-vezeeta-en",
        "node" : "2H0TdjZuRjSlQCiTJ06gZQ",
        "reason" : {
          "type" : "illegal_state_exception",
          "reason" : "Child query must not match same docs with parent filter. Combine them as must clauses (+) to find a problem doc. docId=29675, class org.apache.lucene.search.ConjunctionScorer"
        }
      },
      {
        "shard" : 1,
        "index" : "prelive-vezeeta-en",
        "node" : "2H0TdjZuRjSlQCiTJ06gZQ",
        "reason" : {
          "type" : "illegal_state_exception",
          "reason" : "Child query must not match same docs with parent filter. Combine them as must clauses (+) to find a problem doc. docId=29926, class org.apache.lucene.search.ConjunctionScorer"
        }
      }
    ],
    "caused_by" : {
      "type" : "illegal_state_exception",
      "reason" : "Child query must not match same docs with parent filter. Combine them as must clauses (+) to find a problem doc. docId=29675, class org.apache.lucene.search.ConjunctionScorer",
      "caused_by" : {
        "type" : "illegal_state_exception",
        "reason" : "Child query must not match same docs with parent filter. Combine them as must clauses (+) to find a problem doc. docId=29675, class org.apache.lucene.search.ConjunctionScorer"
      }
    }
  },
  "status" : 500
}

**Comment by worleydl** [comment]
The underlying cause doesn't jump out at me but I would suggest creating a feature with a bool query that has the ID under a must clause.  

I'm closing this issue out as we don't typically provide general support under github issues.  You may get more discussion in the slack channel.
