### ISSUE TITLE
Use LTR in Elasticsearch Java high level API

### ISSUE THREAD

**Issue by KamyarGhajar** [o19s/elasticsearch-learning-to-rank#344]
Hi,
Have you tested the ES high-level API to get the logs or run the model for reranking by LTR in java?
I am doing it and I need java builder files from the library and I use maven in my project, how should I use the built LTR library in java? I have tried jitpack on the GitHub code but it does not work.

**Comment by nathancday** [comment]
HI Kamyer,

I don't understand your reference to the high-level API. You won't need to build any `jar` files in order to install and use the plugin properly. Remember this plugin is focused on bringing trained models into ES for use in queries, not building the models themselves.

Perhaps you are really seeking how to build and incorporate `Ranklib`/`RankyMcRankFace`, the Java tools that are estimating the actual models.

Hope that helps and also happy to help more if it doesn't.

**Comment by KamyarGhajar** [comment]
Hi Nathan,
Actually I am referring to [this](https://www.elastic.co/guide/en/elasticsearch/client/java-rest/7.10/java-rest-high.html) Java High-Level client by ES. To use SLTR, Logger, etc. queries provided by the ES-LTR plugin, you need to have java implementations to call them properly, it is not simple json rest api. In LTR documentation this looks not supported yet and the jar library is not provided in maven central.

**Comment by nathancday** [comment]
I know we have not be the best about supporting our maven repo so I'm guessing any code there is woefully behind the current master here. (we have flagged Maven as an area we want to be better about; automatic builds etc).

To the best of my knowledge we have not written an implementation of the special queries in this plugin for the high-level Java lib you reference. I can see how that could help users, I'm not sure where the best place for that code would live. Have you seen other plugins implement similar classes to mimic the behavior of the high-level API wrapper Elastic maintains?

**Comment by KamyarGhajar** [comment]
Having the query builders and ext log builder in the src of the library can do the trick here. With some changes to support all the queries with builders in java by importing the maven library of this very project people will be able to use high-level client API in their java projects.

**Comment by KamyarGhajar** [comment]
btw I have worked on it in a project of mine that works now with the ES high-level API, except it needed an empty constructor for StoredLTRQueryBuilder for not to need a model as a logging filter.

**Comment by nathancday** [comment]
That does sound like an easy add that would help java API users. Would you mind dropping a link for your project with the similar code?  We can use it as a template for porting `sltr`

**Comment by KamyarGhajar** [comment]
@nathancday Sorry for the delay. I can not share the project as it is a commercial project of the company I am working for. But for logging now I have copied this repo's `LoggingSearchExtBuilder` and `StoredLtrQueryBuilder` into my project (as there were no es-ltr builds in the maven repo so I can use it as an external library) then I have added the filter query in the original query like this:

```
if (Configuration.instance().getLtr().isEnabled()) {
                fsQuery.filter(new StoredLtrQueryBuilder()
                        .featureSetName(Configuration.instance().getLtr().getFeatureSetName())
                        .params(new HashMap<>() {{
                            put("query", text);
                            if (userLocationStr != null) put("location", userLocationStr);
                        }})
                        .queryName("logged-features"));
            }
```

And then before performing the query to get results from ES I have the following modification:

```
var sourceBuilder = new SearchSourceBuilder()
                .query(query)
                .fetchSource(_sources, null)
                .size(hitsCount);
        if (Configuration.instance().getLtr().isEnabled())
            sourceBuilder.ext(List.of(new LoggingSearchExtBuilder().addQueryLogging("features", "logged-features", false)));
        var request = new SearchRequest(Configuration.instance().getElasticsearch().getPlacesIndex()).source(sourceBuilder).preference("_local");
        client.searchAsync(request, RequestOptions.DEFAULT, (ActionListener) listener);
```

Please let me know if you want more info.

**Comment by nathancday** [comment]
No worries, everything you provided is a help! We want to get this added to the project and have some dev time planned to tackle it next week. Thanks for your support and I will reach out for more help once we get the code cooking.

We are aware of the empty maven build and working on that too, thanks for flagging.

**Comment by nathancday** [comment]
Two things:

1) The maven build should be not empty now: https://repo1.maven.org/maven2/com/o19s/elasticsearch-learning-to-rank/1.5.4.1-es7.10.0/

2) Looks like you have the code you need for your use case, is that correct?

And just to make sure I understand your original motivation for this, it would be to have Java alternatives to the DSL for executing common LTR tasks (like logging features for a given query+feature_set). Thank you.

**Comment by KamyarGhajar** [comment]
@nathancday thanks, I will try it. So, now I think I do not need to copy the java files into my project to use the logger.

**Comment by rudibatt** [comment]
Just in case someone else stumbles upon this issue. To use the "sltr" query, it is not required to have @KamyarGhajar modified StoredLtrQueryBuilder. You can simply pass "null" to the builder, because that FeatureStoreLoader is not required by the called "doXContent" method. 

```
var rescoreQuery = new StoredLtrQueryBuilder(null)
			.modelName("test_6")
			.params(Collections.singletonMap("keywords", parameters.userQuery));
searchSourceBuilder.addRescorer(new QueryRescorerBuilder(rescoreQuery).windowSize(1000));
```

@nathancday Thanks for fixing the Maven artifact. :)

**Comment by Hronom** [comment]
Actually it's very hard to use LTR with Java High-Level client, if you can build a client library, it will be very helpful
