### ISSUE TITLE
Model Language: Change from ordinals to names

### ISSUE THREAD

**Issue by sstults** [o19s/elasticsearch-learning-to-rank#35]
The names may refer to search templates.

**Comment by epugh** [comment]
@worleydl can you investigate if this is done?

**Comment by nomoa** [comment]
This is I think the last bits that still need to be done for v1, currently few model parsers (linear, xgboost) can understand named features. The ranklib model languages (AFAIU) currently only supports ordinals.
Maybe we could rename as: support named features in ranklib model formats?

**Comment by softwaredoug** [comment]
Largely done, however we will need to support ordinal-based ranklib forever I suspect. So I think we will need to fix issue #85
