### ISSUE TITLE
Jar file is empty when installing with maven

### ISSUE THREAD

**Issue by pakio** [o19s/elasticsearch-learning-to-rank#350]
# Description
When installing this plugin with maven, downloaded jar file is empty and cannot be imported from program.
and Jar file on central repository is empty, size is only about < 1kB
ref : https://repo1.maven.org/maven2/com/o19s/elasticsearch-learning-to-rank/1.5.4-es7.10.0/

# Cause
It because the publish script is defined as **subproject**, so the source code of main project is not included.
Here is the history of publishing process in GitHub Actions, it says NO-SOURCE.
https://github.com/o19s/elasticsearch-learning-to-rank/runs/1553487714?check_suite_focus=true
![image](https://user-images.githubusercontent.com/11995398/102778607-3cf9d380-43d6-11eb-823a-18cd5dcbf2fa.png)

I'm really sorry for the bug, and working on fixing and can open pull request to fix it in this week.
 (I did [some work](https://github.com/pakio/elasticsearch-learning-to-rank/tree/bugfix/build-script) already and it worked ok at my local environment. Now asking my co-worker to test the script for 
final confirmation)

**Comment by nathancday** [comment]
No worries at all. We've asked people to test b/c we don't use Maven ourselves. We can rebuild images no problem. Thanks for doubling back and catching this. Really appreciate you donating your time.

**Comment by worleydl** [comment]
Fixed by #352 I will work on cleaning up the previous releases.

**Comment by worleydl** [comment]
I'm unable to overwrite the existing releases, but I created a 1.5.4.1 which is populated: https://repo1.maven.org/maven2/com/o19s/elasticsearch-learning-to-rank/1.5.4.1-es7.10.0/.

Future releases should be good to go.
