### ISSUE TITLE
Cannot resolve com.o19s:RankyMcRankFace:0.1.1

### ISSUE THREAD

**Issue by yoyo185** [o19s/elasticsearch-learning-to-rank#351]
Hi, when I add the dependency elasticsearch-learning-to-rank 1.5.4-es7.10.0 in maven and it shows this error 'Cannot resolve com.o19s:RankyMcRankFace:0.1.1'. When I add https://mvnrepository.com/artifact/com.o19s/RankyMcRankFace/0.1.1 this dependency, it still could not resolve this problem, can anyone help me to solve it? Thank you.

**Comment by nathancday** [comment]
Thanks for flagging this. Looks like we might not have the resource link for RankyMcRankFace (Ranklib) set properly. Can you try installing outside of Maven to confirm that?

You can use the zip files here on GIthub Releases or from AWS s3:
https://github.com/o19s/elasticsearch-learning-to-rank/releases
http://es-learn-to-rank.labs.o19s.com/

**Comment by nathancday** [comment]
Linking #350

**Comment by nathancday** [comment]
@yoyo185 Can you check if you still get the failed to find error with the non-empty build we just fixed:
https://repo1.maven.org/maven2/com/o19s/elasticsearch-learning-to-rank/1.5.4.1-es7.10.0/

**Comment by yoyo185** [comment]
> @yoyo185 Can you check if you still get the failed to find error with the non-empty build we just fixed:
> https://repo1.maven.org/maven2/com/o19s/elasticsearch-learning-to-rank/1.5.4.1-es7.10.0/

No, the issue still exists. It seems that RankyMcRankFace is not published to the maven.

**Comment by nathancday** [comment]
Thanks for checking again.

I'm not sure why this is happening. It looks like Ranky is published to maven: https://mvnrepository.com/artifact/com.o19s/RankyMcRankFace/0.1.1. Perhaps our link is still wrong...

**Comment by yoyo185** [comment]
> Thanks for checking again.
> 
> I'm not sure why this is happening. It looks like Ranky is published to maven: https://mvnrepository.com/artifact/com.o19s/RankyMcRankFace/0.1.1. Perhaps our link is still wrong...

It shows that RankyMcRankFace is indexed in mulesoft but I cannot find it in https://repository.mulesoft.org/nexus/content/repositories/public/

**Comment by nathancday** [comment]
Yea, we've figured Mulesoft removed Ranky at some point. We are publishing new versions of Ranky to Central now. Thanks for helping us knock the cobwebs off of this and looking forward to having it all working bug free.

**Comment by nathancday** [comment]
@worleydl is this fixed with the newest maven repos?

**Comment by worleydl** [comment]
Yep!
