### ISSUE TITLE
when logging features used in model，response took more time

### ISSUE THREAD

**Issue by WaitInRaining** [o19s/elasticsearch-learning-to-rank#354]
I need log features used in model. But the took time is higher 5 ms than logging nothing.
logging  nothing: 50ms 
logging  features: 55ms
feature: bm25

I think sltr query filter nothing and rankQuery only cost 0.1ms(from profile). so I wonder if the cost during feature fetch phase and what I can do to reduce took time?

**Comment by nomoa** [comment]
Logging features is not free, it needs to re-extract the features (run the feature queries) during the fetch phase.
You can reduce this time only by reducing the number of docs you fetch or by reducing the number of features.
For some users doing online feature logging is not possible and must be done offline as part of a batch/async process.

**Comment by WaitInRaining** [comment]
> Logging features is not free, it needs to re-extract the features (run the feature queries) during the fetch phase.
> You can reduce this time only by reducing the number of docs you fetch or by reducing the number of features.
> For some users doing online feature logging is not possible and must be done offline as part of a batch/async process.

if reducing the number of feature, i run model with feature A, and logging some features in A as feature B. So,when logging feature B, does it need to re-calculate feature B ?

**Comment by nomoa** [comment]
> > Logging features is not free, it needs to re-extract the features (run the feature queries) during the fetch phase.
> > You can reduce this time only by reducing the number of docs you fetch or by reducing the number of features.
> > For some users doing online feature logging is not possible and must be done offline as part of a batch/async process.
> 
> if reducing the number of feature, i run model with feature A, and logging some features in A as feature B. So,when logging feature B, does it need to re-calculate feature B ?

The query behind your feature will be executed:
- once per shard during the search phase if the //sltr// query is used as a scoring query
- once per matching shard during the fetch phase if logging is enabled

There is not way to re-use what was extracted during the search phase when running the fetch phase.

If doing "logging-only" you can avoid the extraction of the feature during the search phase by wrapping it inside filter (see the example in the doc: https://elasticsearch-learning-to-rank.readthedocs.io/en/latest/logging-features.html#).

But please share some examples with accompanying numbers I might have misunderstood your problem.

**Comment by WaitInRaining** [comment]
> > > Logging features is not free, it needs to re-extract the features (run the feature queries) during the fetch phase.
> > > You can reduce this time only by reducing the number of docs you fetch or by reducing the number of features.
> > > For some users doing online feature logging is not possible and must be done offline as part of a batch/async process.
> > 
> > 
> > if reducing the number of feature, i run model with feature A, and logging some features in A as feature B. So,when logging feature B, does it need to re-calculate feature B ?
> 
> The query behind your feature will be executed:
> 
> * once per shard during the search phase if the //sltr// query is used as a scoring query
> * once per matching shard during the fetch phase if logging is enabled
> 
> There is not way to re-use what was extracted during the search phase when running the fetch phase.
> 
> If doing "logging-only" you can avoid the extraction of the feature during the search phase by wrapping it inside filter (see the example in the doc: https://elasticsearch-learning-to-rank.readthedocs.io/en/latest/logging-features.html#).
> 
> But please share some examples with accompanying numbers I might have misunderstood your problem.
I search and rescore docs. When logging all features with `sltr query` and `ext` used in model, it will cost 80ms. So i reduce the 
 number of logging features, just logging bm25。
