### ISSUE TITLE
Feature score logging does not work against rescore query without named query in v1.5.4-es7.10.0

### ISSUE THREAD

**Issue by tmanabe** [o19s/elasticsearch-learning-to-rank#357]
Hi. We recently upgraded our search engine cluster from 1.1.2-es7.5.1 to v1.5.4-es7.10.0 and
found that feature score logging does not work against a rescore query without named query.
This may be a bug.

I wrote a new test case to reproduce the problem and tried to fix the problem,
but the modification make another test case fail.
https://github.com/tmanabe/elasticsearch-learning-to-rank/commit/97ffe95afd2cb1c3ab8eccb5f9af70ceae4e3185

Thanks!

**Comment by nathancday** [comment]
Thanks for reporting this and passing along what you did to fix it.

**Comment by tmanabe** [comment]
Thank you for your quick response!
Do you think this is a bug? If so, is there anything we can do?

**Comment by nathancday** [comment]
I'm not sure yet, it seems weird that something would have broken with `rescore` between 7.5 and 7.10 but it is Elastic

**Comment by tmanabe** [comment]
You mean it is a problem of Elasticsearch itself, not this plugin?

**Comment by nathancday** [comment]
no just that we use a lot of elastic's libraries in the plugin and they iterate/deprecate functions quickly

**Comment by tmanabe** [comment]
I got it. Thanks.

**Comment by worleydl** [comment]
@nomoa I messed this up in the 7.10 PR.  The SearchContext has moved into the FetchContext with private access, I tried digging a little more last night but haven't found a way to replicate the logic that was once here: https://github.com/o19s/elasticsearch-learning-to-rank/pull/348/files#diff-a58a7d8b9fafdd39c377aa27b54445905578c38761e32e3c5911c58b757024adL63

Any ideas?  Maybe we ping ES for access to the context again? Or at least a method that checks to see if it's the inner subcontext?

**Comment by worleydl** [comment]
We've been encouraged to raise this issue to the ES team. There has been a little internal ES discussion on the matter already but not enough momentum to make any calls on it.  If David is able to come up with a solution we can roll with that otherwise we can draft some justification for our request and raise the issue to the ES team.

**Comment by nomoa** [comment]
@worleydl thanks for the ping, I'll take a look tomorrow!

**Comment by nomoa** [comment]
@worleydl I could not find a direct way to know in which context the processor is run but delaying construction of the various components until we can read the first hit with can know reading `SearchHit#getNestedIdentity()` if we can safely extract the named/rescore queries. Not sure where the discussion with upstream if happening but I think it might make sense to give some hint through FetchContext to let plugins know if they are going to process top level or nested hits.

@tmanabe I took the liberty to embark your test case, please let me know if you have any problem with that. Thanks!

**Comment by tmanabe** [comment]
@nomoa No problem! Thanks!
