### ISSUE TITLE
Cannot compile ltr with Elasticsearch 7.11.1

### ISSUE THREAD

**Issue by JeremieDoctrine** [o19s/elasticsearch-learning-to-rank#359]
Hello,

First of all, thanks for your work 👏 

We are currently in the process of upgrading our current Elasticsearch server to 7.11.1 but I cannot make it works with the LTR plugin.

But I'm not sure where to start to look to fix this issue?

```
* Where:
Build file '/private/tmp/fork/build.gradle' line: 66

* What went wrong:
A problem occurred evaluating root project 'ltr'.
> Could not find method dependencyLicenses() for arguments [build_9u45wsw68wafumsl5evd1qqp6$_run_closure4@42cdf53a] on root project 'ltr' of type org.gradle.api.Project.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.6.1/userguide/command_line_interface.html#sec:command_line_warnings
```

If I can have any guidance on how to build it it will be very much appreciated.

**Comment by nathancday** [comment]
We are working on figuring this out too. I don't have any useful guidance yet, other than I can reproduce the same error.

Beside that I'd recommend not to use the bleeding edge of ES is you need plugins, they break things (like this) all the time.

Please update here if you (or anyone else) finds something fruitful and I will do that same.

**Comment by JeremieDoctrine** [comment]
Ok, thanks for the reply, your experience is very much appreciated. I will go with 7.10.2 (we are few versions behind) let me know if you want me to close the issue.

**Comment by nathancday** [comment]
Let's leave it open for now and we can close when we fix. This seems to be what broke it: https://github.com/elastic/elasticsearch/issues/63697#issuecomment-728847973

**Comment by ayushKataria** [comment]
Hi, wanted to ask whether there is a planned timeline  for support of ES 7.11 and 7.12?

**Comment by nathancday** [comment]
No planned timeline, but we are aware 7.12 is out. We work on maintaining this plugin in our free time and the last few months have been exceptionally busy for us.

We always want to welcome in new contributors, if the version support is a blocker for you we'd gladly review a PR.

**Comment by nathancday** [comment]
Tagged release is out now here on GH,  working to get it up on Maven too.

**Comment by kylelyk** [comment]
@nathancday Could you also upload the zip archive to http://es-learn-to-rank.labs.o19s.com since that's the normal location to use when installing the plugin to an ES cluster?

**Comment by nathancday** [comment]
Just uploaded to AWS.

Consider updating the install to use the zip in [GH Releases](https://github.com/o19s/elasticsearch-learning-to-rank/releases/download/v1.5.4-es7.11.1/ltr-plugin-v1.5.4-es7.11.1.zip). It feels silly to have things in two places, so we may deprecate the AWS repo in favor of new releases being on GH at some point

**Comment by kylelyk** [comment]
I should have realized that the GitHub release had a valid zip archive to use. Maybe the README should be updated to reference that instead? Anyways, thanks for the effort on this release.
