### ISSUE TITLE
license issue

### ISSUE THREAD

**Issue by jngz-es** [o19s/elasticsearch-learning-to-rank#363]
Hi team,

As you might know, elasticsearch changed the license from Apache 2.0 to new SSPL+Elastic-2.0 license from 7.11 version. I am curious if you have a plan to follow this new license. As an option, I'd like to introduce opensearch (https://opensearch.org/) here which is a community-driven, open source search and analytics suite derived from Apache 2.0 licensed Elasticsearch 7.10.2 & Kibana 7.10.2. You might think about migrating the LTR plugin to opensearch. We definitely can help on it.

Best regards,
Jing

**Comment by worleydl** [comment]
Hi Jing,

We're aware of of opensearch as a new player however we currently have no plans to abandon ES support.  This project will continue under Apache 2 license so you're free to do as you wish if you'd like to create a fork that provides OS support.  It would be my recommendation that such support is created in a different repository as it will involve swapping out a major dependency.

**Comment by dblock** [comment]
@worleydl Has anything changed since last year regarding OpenSearch support? We would like to contribute and are wondering whether we should try to make an incremental change and PR upstream here and try to maintain both ES and OS support, or fork LTR and build OpenSearch support in the fork dropping ES support?

**Comment by worleydl** [comment]
There's been some discussion but no official plans yet for OS.

Depending where the change lives and what it requires it could live here and trickle down to the current existing forks.  If you go the fork strategy and get ideas on supporting both ES & OS from one project we'd be open to it but my gut feeling is it would require a significant amount of code refactoring.
