### ISSUE TITLE
Execute LTR queries without specifying features

### ISSUE THREAD

**Issue by sstults** [o19s/elasticsearch-learning-to-rank#37]
- Pass a model
- Needs to be parameterized to include whatever the templates require
  - Query string
  - Location
  - ...

**Comment by epugh** [comment]
@nomoa in talking with @worleydl, and looking at https://github.com/o19s/elasticsearch-learning-to-rank/blob/1_0/docs/rest_api.md, it appears this is done?   thoughts?

**Comment by nomoa** [comment]
yes this is done.
