### ISSUE TITLE
How to use an array as a param for feature logging?

### ISSUE THREAD

**Issue by ndkmath1** [o19s/elasticsearch-learning-to-rank#370]
I want to create a feature in my feature set and its param is an array. I known how to use a single value for feature logging but I don't know how to use an array. I tried something like below but it didn't help. Do you have any solutions for that?

```
PUT _ltr/_featureset/test
{
    "featureset": {
        "features": [
            {
                "name": "matched_author",
                "params": [
                    "authors"
                ],
                "template_language": "mustache",
                "template": {
                    "terms": "{{#toJson}}{{authors}}{{/toJson}}"
                }
            }
        ]
    },
    "validation": {
        "params": {
            "authors": {
                "id": [1, 2]
            }
        },
        "index": "my_index"
    }
}
```

**Comment by nomoa** [comment]
Could you try encoding the whole feature into a string and remove the quotes around the call to `#toJson` e.g.:

```
"template": "{ \"terms\": {{#toJson}}{{authors}}{{/toJson}} }"
```

I think similar approach was discussed in #164 as well.

**Comment by ndkmath1** [comment]
Yeah, the problem is solved by your suggestion.
Thank you so much.
