### ISSUE TITLE
Failed to apply plugin class 'org.elasticsearch.gradle.testclusters.TestClustersPlugin'.

### ISSUE THREAD

**Issue by ayushKataria** [o19s/elasticsearch-learning-to-rank#377]
Hi,

While trying to import the project gradle is giving below error:
```
A problem occurred evaluating root project 'ltr'.
> Failed to apply plugin class 'org.elasticsearch.gradle.testclusters.TestClustersPlugin'.
   > can not determine architecture from [x86]
```

I am new to gradle and elasticsearch plugins. Please let me know what I need to do to fix this.

**Comment by worleydl** [comment]
Hello,

Can you let us know what version of the plugin you're using and which IDE if any? Are you able to check out the project and run `./gradlew clean check` without issue?

**Comment by ayushKataria** [comment]
I am using 1.5.5-es7.12.1 version and intellij IDEA IDE. And yes I am able to run ```./gradlew clean check``` without and issues.

**Comment by worleydl** [comment]
Can you give the branch on this PR a whirl to see if it makes things nicer for you?
https://github.com/o19s/elasticsearch-learning-to-rank/pull/379

**Comment by ayushKataria** [comment]
The ```can not determine architecture``` issue turns out to be something else. It was me using a JVM with x86 architecture which seems like is not supported by ES (https://github.com/elastic/elasticsearch/blob/master/build-tools/src/main/java/org/elasticsearch/gradle/Architecture.java), with Architecture.current() method only supporting amd64, x86_64 and aarch64.

With the existing code I did face the external dependency issue which this PR solves.
