### ISSUE TITLE
Feature Store API: Add ability to derive features

### ISSUE THREAD

**Issue by sstults** [o19s/elasticsearch-learning-to-rank#38]

**Comment by epugh** [comment]
This seems like it has been done...   Talking to @worleydl....    @nomoa can you confirm we can close this?

**Comment by ebernhardson** [comment]
Yup. This has been completed with @worleydl  work on integrating lucene expressions taking features to make new features.

**Comment by epugh** [comment]
Thanks!    Another issue closed!
