### ISSUE TITLE
match_explorer query: a problem with docFreq while calculating IDF

### ISSUE THREAD

**Issue by ndkmath1** [o19s/elasticsearch-learning-to-rank#381]
Hi everyone, @worleydl,

I wanted to reopen issue #375 but I couldn't because it wasn't closed by me. There's a problem while you clean up deprecated method usage. Now you're using [TermStates.docFreq()](https://github.com/o19s/elasticsearch-learning-to-rank/pull/378/commits/3a0e2ef1ca572c294ebc61d27a853abb50d291a2#diff-b689de90d39430a4a1071f41bd3f0895ff38ef92eeace7764d16766877844cfaR110) to calculate `docFreq`. It leads to `docFreq` is always calculated over shard.

Example: if I do the following request
```
POST my_index/_search?search_type=dfs_query_then_fetch
{
   "query": {
       "match_explorer": {
           "type": "sum_classic_idf",
           "query": {
               "match": {
                   "title": "when breath becomes air"
               }
           }
       }
   }
}
```
I see the plugin is using `docFreq` over shard and `docCount` over index to calculate `idf`. It will be better if `docFreq` is also calculated over index.

We will make `docFreq` better and clean up deprecated method usage if we do the same as my [PR](https://github.com/o19s/elasticsearch-learning-to-rank/pull/380).
I temporary delete a test ([testNonExistentVocab](https://github.com/o19s/elasticsearch-learning-to-rank/blob/main/src/test/java/com/o19s/es/explore/ExplorerQueryTests.java#L314)) in my [PR](https://github.com/o19s/elasticsearch-learning-to-rank/pull/380) because it doesn't pass if we do the same thing as [v1.5.5](https://github.com/o19s/elasticsearch-learning-to-rank/releases/tag/v1.5.5-es7.13.2) or my [PR](https://github.com/o19s/elasticsearch-learning-to-rank/pull/380). Maybe that test related to another problem?

Please let me know if I need to clarify anything.

Thanks.

**Comment by worleydl** [comment]
Resolved and fixed in version 1.5.7.  Thanks for all the help and sorry for the wait!
