### ISSUE TITLE
How to deal with category-type features

### ISSUE THREAD

**Issue by yzc1103** [o19s/elasticsearch-learning-to-rank#386]
By looking at the document, we know that numeric features need to be normalized. However, in some scenarios, category attributes of documents need to be extracted, such as labels and security levels. What should be done with these features? Need to change to one-hot form?
Could you give me some advice?

**Comment by worleydl** [comment]
You either need a way to to convert your non-numeric data to numeric (one-hot could be an approach), or you can setup boolean features for each kind of label and use a 0/1 to track it.

**Comment by yzc1103** [comment]
Thank you very much for your reply, but I also have a question.
For example, there is a feature with 6 categories, and the feature value is a character string, including "A", "B", "C", "D", "E", "F". If I want to input this feature into the RankLib or SVM-Rank model for training, can I change the feature to 0, 1, 2, 3, 4, 5？Is this non-boolean format allowed? 
Looking forward to your answers.

**Comment by nathancday** [comment]
Only if you want to convey a continuous or ordered relationship between A,B,...

If you don't want that (ie they are really discrete values with no order) then one-hot encoding will do that for you in terms of how the model appreciates the data.
