### ISSUE TITLE
_score is 0 while extracting feature values in LTR

### ISSUE THREAD

**Issue by MeghanaSreenath** [o19s/elasticsearch-learning-to-rank#387]
Hi,

I am very new to Elasticsearch and LTR. I an working on my first project on LTR and the results are poor. I have found an issue which might be cause of poor relevance. The feature set has many features including user interaction features and product specific features. I am using a similar query like below to get the feature values for my feature set. And the result of the below query has an _score value of 20.291. But in my application the _score value is 0 even though there are positive values for features I have given. I am guessing this might be the issue and hence the results are poor. Any help in this would be greatly appreciated. Thankyou. 
Query:
      "bool": {
              "filter": [
              {
                  "terms": {
                      "_id": ["7555", "1370", "1369"]

                  }
              },
              {
                  "sltr": {
                      "_name": "logged_featureset",
                      "featureset": "more_movie_features",
                      "params": {
                          "keywords": "rambo"
                      }
              }}

          ]
  }
}}

RESULT:
{
    "_index": "tmdb",
    "_type": "movie",
    "_id": "1370",
    "_score": 20.291,
    "_source": {
        ...
    },
    "fields": {
        "_ltrlog": [
            {
                "log_entry1": [
                    {"name": "title_query"
                     "value": 9.510193},
                    {"name": "body_query
                     "value": 10.7808075}
                ]
            }
        ]
    },
    "matched_queries": [
        "logged_featureset"
    ]
}

**Comment by nathancday** [comment]
You are using a `filter` context, which will always return a score of 0 or 1. This is defined by Elasticsearch and has nothing to do with the plugin. Also of note since you have two filter clauses, those are interpreted with the boolean AND operator, meaning that both would have to match for doc to be scored as a 1.

If you instead move your `sltr` query to the `should` clause of your `bool` query you will see a _score that matches what you see when you run it independently.

**Comment by MeghanaSreenath** [comment]
Yes, I actually tried putting it in must and it worked. But now I have another problem. My results are still poor, I am not sure if my rescore query is working is not. As in, I tried checking the results from a query which got trained, even for this I'm getting bad results. Anyway I can check if my model is working or not?

**Comment by MeghanaSreenath** [comment]
So I found another problem here. I did an _explain on one of my document which had to be displayed on top but its not. _explanation tells me that _score for this doc is 1.82 which is the sum of 2 values. 1.82 + 0. This 1.82 is the score of my LTR model. I do not understand how its 1.82 when each feature match score is greater than 1.82. If instead the sum of all the features are taken into account then definitely this document would be the top one.  Can you please help me out here?
