### ISSUE TITLE
xgboost.txt format

### ISSUE THREAD

**Issue by meg261995** [o19s/elasticsearch-learning-to-rank#389]
Hi,

Could someone explain me the below format?
4 1:9.169009 2:22.169247
3 1:6.9903145 2:20.8937
3 1:4.972313 2:19.01041
3 1:0.0 2:14.370026
0 1:0.0 2:0.0
0 1:0.0 2:0.0
0 1:0.0 2:0.0
0 1:0.0 2:0.0
0 1:0.0 2:0.0
0 1:0.0 2:0.0

column 1 is the relevance ranking, and the rest is feature vector. I get this. But where is the qid which indicates the document belong to that particular query?

**Comment by nathancday** [comment]
Correct you are missing the query grouping information in your output, perhaps this is for the explain of single query? How did you generate the data you copy and pasted here?

**Comment by meg261995** [comment]
Hi,

Thanks for the reply. This is not my data. I found it on a website which was used to as an input. 
Closing this issue now. Thank you!
