### ISSUE TITLE
Getting unknow features in xgboost model while doing ranking

### ISSUE THREAD

**Issue by meg261995** [o19s/elasticsearch-learning-to-rank#390]
Hi All,

I have trained an xgboost ranking model with certain features. The problem is the model is getting one particular numeric feature which is not included in the featmap. Can anyone please let me know the reason behind this? This is leading to unknown feature error.

"caused_by":{"type":"parsing_exception","reason":"Unknown feature [32]","line":1434,"col":10}}}}},"status":400}

**Comment by meg261995** [comment]
Adding to the above, the spilt condition is exactly 1.5 for this particular unknown feature

**Comment by nathancday** [comment]
Closing as not reproducible. If you can make this into a full reproducible example, with data, requests and anything else needed to regenerate the error message you are getting, please re-open. 

In general issues to the plugin should be about problems with plugin code, not data issues like this, when you are passing in an additional feature that model does not have.
