### ISSUE TITLE
prebuilt release for Elastic 7.14.1 

### ISSUE THREAD

**Issue by scrush** [o19s/elasticsearch-learning-to-rank#392]
Dear LTR plugin developers, could you please build the version for newly released Elastic ver. 7.14.1? Previous plugin version (for 7.13) cannot be used with it (backward compatibility was lost). Thanks much in advance!

**Comment by worleydl** [comment]
We have the code changes ready for 7.14 releases but elastic changed some of the build tools upstream which broke our testing setup.  From the commit log [here](https://github.com/elastic/elasticsearch/commits/7.14/build-tools/build.gradle) it looks like the gradle plugins that were removed are being added back in which should help us get back on track.  Because of this hold up 7.14.2 may be the first version we support from the 7.14 line tho we're exploring a possible hotfix to get the other versions out as well.

**Comment by thePanz** [comment]
In the meantime:
- ES 7.15.0 got released → https://github.com/elastic/elasticsearch/releases/tag/v7.15.0
- ES 7.14.2 got released → https://github.com/elastic/elasticsearch/releases/tag/v7.14.2

**Comment by nathancday** [comment]
I think we shoudl cut 7.14.0 and 7.14.1 without running units. As of 7.14.2 the tests will come back. I think this is reasonably safe as there will be no real code changes aside from functions being relocated in Elastic dependencies. And it gets us back to current (with functional unit tests)

**Comment by thePanz** [comment]
I agree with having a green pipeline against ES 7.14.2 and tag a new release.
I would expect people to upgrade to the latest minor releases of ES anyway.

WDYT? Is it safe to try?

**Comment by worleydl** [comment]
Yup, we'll just make a note on those releases.  I see the `java-rest-test` plugin is back in 7.14.2 but no luck with `rest-resources` which I think is causing our API spec to be lost.  Worst case I think we can just clone what that plugin was doing.  The branch is up here if you have ideas: https://github.com/o19s/elasticsearch-learning-to-rank/tree/es_7_14_2.

It may be the case we just have to reorganize some folders to play along with the new java-rest-test plugin (I haven't dug in to see the differences between that and the old one that was moved to the internal build tools).

**Comment by nathancday** [comment]
Ahh the old ES shell game of moving/removing/renaming things to keep those pesky plugins on their toes, gotta love it

**Comment by thePanz** [comment]
Hi there, any progress in having a release for the newest releases of ES? how can we/I help?

- v1.15.2 https://github.com/elastic/elasticsearch/releases/tag/v7.15.2
- v1.14.2 https://github.com/elastic/elasticsearch/releases/tag/v7.14.2

**Comment by worleydl** [comment]
Hey Panz, pushing again on this today.  If I don't get releases out I'll try to get an update on the current status & todo items.

**Comment by worleydl** [comment]
Releases have been cut and tests are restored (for now!) :)
