### ISSUE TITLE
Error uploading RankLib model (null_pointer_exception)

### ISSUE THREAD

**Issue by ur2021** [o19s/elasticsearch-learning-to-rank#401]
Hi,
I am trying to upload a RankLib model, but I get the follwing error:
```
{
    "error": {
        "root_cause": [
            {
                "type": "null_pointer_exception",
                "reason": "Cannot invoke \"org.elasticsearch.common.xcontent.XContentParser.currentToken()\" because \"parser\" is null"
            }
        ],
        "type": "null_pointer_exception",
        "reason": "Cannot invoke \"org.elasticsearch.common.xcontent.XContentParser.currentToken()\" because \"parser\" is null"
    },
    "status": 500
}
```
I checked other issues here and couldn't find anything with such error. The payload is here: [upload_model.zip](https://github.com/o19s/elasticsearch-learning-to-rank/files/7417568/upload_model.zip)

**Comment by nomoa** [comment]
@ur2021 I think you did not provide any content to the _createmodel endpoint. The json model must be passed as the request body of the POST request:

```
curl -XPOST -H "Content-Type: application/json" localhost:9200/_featureset/orbis_features/_createmodel -d @model_file.json
```

But I agree that the plugin should provide better explanation of what is missing instead of throwing an NPE.
