### ISSUE TITLE
match_explorer type 'min_raw_tp' are illegal 

### ISSUE THREAD

**Issue by bannima** [o19s/elasticsearch-learning-to-rank#404]
I'm using ElasticSearch 7.2.0 with LTR plugin to construct learning-to-rank plugins. However I found the match_exploer search type
'min_raw_tp ' are illegal.Same problem has also been found for term position statistics.  My search query are as followers:

```
POST tmdb/_search
{
    "query": {`
       "match_explorer": {
            "type": "min_raw_tp ",
            "query": {
                "match": {
                    "title": "rambo rocky"
                }
            }
        }
    }
}
```
Can anyone help me with this issue? Is the ES  and LTR plugin version 7.2.0 are not satisfied with the match_explorer search?

**Comment by worleydl** [comment]
Term position support wasn't added until 1.2.2. initially added in this PR: https://github.com/o19s/elasticsearch-learning-to-rank/pull/289.  I believe it was added as part of 1.3.0.
