### ISSUE TITLE
PinnedSearchQuery being overridden by LTR

### ISSUE THREAD

**Issue by Sutty100** [o19s/elasticsearch-learning-to-rank#407]
When I run a [pinned search query](https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-pinned-query.html) that has x documents pinned to the top and then the main query which includes learn to rank running on those query results the pinned documents are moved from the top of the result set by learn to rank. My understanding is that the pinned results should override anything that happens within the query so this seems like a bug.

**Comment by worleydl** [comment]
Can you provide an example query that surfaces this behavior?  Just want to confirm whether you were running a rescore or doing LTR under the organic parameter.

**Comment by Sutty100** [comment]
Realised that I think this is a limitation of the elastic pinned search query. The pin happens first and then the rescore is run across the result set. In effect I need a way to pass to the LTR rescorer the fact that when computing the new scores it needs to ensure the following lines are kept in positions 1,2,3 etc. But that would be a feature request rather than a bug! I'll close this.

**Comment by Sutty100** [comment]
Figured out I just needed to run a second rescore after LTR to re-pin. In the unlikey event anybody else runs into this putting the query here:
`{
  "from": 0,
  "size": 128,
  "query": {
    "pinned": {
      //First pinned query to ensure you get documents that are outside the rescore window
      "organic": {
        //whatever your query is
      },
      "ids": [
        "1",
        "2"
      ],
      "boost": 1
    }
  },
  "rescore": [
    //First run the LTR rescore
    {
      "window_size": 1000,
      "query": {
        "rescore_query": {
          "wrapper": {
            "query": "ltrQuery"
          }
        },
        "query_weight": 1,
        "rescore_query_weight": 14563.632,
        "score_mode": "total"
      }
    },
    //Then run a pinned query rescore with the same window size
    {
      "window_size": 1000,
      "query": {
        "rescore_query": {
          "pinned": {
            "organic": {
              //Just do a match all query to not affect the result order outside of your pinning
              "match_all": {
                "boost": 1
              }
            },
            "ids": [
              "1",
              "2"
            ],
            "boost": 1
          }
        },
        "query_weight": 1,
        "rescore_query_weight": 1,
        "score_mode": "total"
      }
    }
  ],
  "ext": {
    "ltr_log": {
      "log_specs": [
        {
          "name": "ltrLog",
          "named_query": "logged_featureset",
          "missing_as_zero": true
        }
      ]
    }
  }
}`
