### ISSUE TITLE
How Features work after model creation

### ISSUE THREAD

**Issue by andreluiz1987** [o19s/elasticsearch-learning-to-rank#411]
I'm studying the LTR and I have a question about the Features.
After I create the judgment list, add the features and record their scores, I train a model to deploy in the LTR plugin.

All this done I would like to understand how reordering works. I saw that the model directly depends on the features I created. When the search is performed, the result is sent to the model through the "rescore". At that moment the reordering is done through the feature queries on the results?
If after training the model, I edit the features with new queries, will the documents score change?

**Comment by nathancday** [comment]
The reordering will be done based on model output score, this is synthesis of walking the decision tree based on the feature values. This score is combined based on how you parameterize the `rescore` portion of the entire ES query.

If the features change then the document score will likely change.

**Comment by andreluiz1987** [comment]
Thank you for the explanation
