### ISSUE TITLE
LTR model not working

### ISSUE THREAD

**Issue by andreluiz1987** [o19s/elasticsearch-learning-to-rank#416]
Hello everybody.

I'm trying to run the LTR example from the link below (My environment is an elastic cluster inside AWS):
https://docs.aws.amazon.com/opensearch-service/latest/developerguide/learning-to-rank.html#ltr-gsg

I followed all the instructions, created the tmdb index (with all the movies), created the features and model.

When I run the query with the "rescore sltr" the ordering is exactly the same as the query that doesn't have it and the _score changes slightly.

Is there any step that I skipped because the impression I have is that the model is not being used.

**Comment by nathancday** [comment]
If the score is changing, then the rescore/sltr is working. Is it doing anything useful? Probably not.

The example you linked to, has a base query: `multi_match(overview, keyword)` and the LTR models features are just isolated `match` queries over the same fields. So no "new" information is being exposed with the model, we couldn't expect the values to change much. Try search over different fields in either the base query or the feature set.
