### ISSUE TITLE
where to find elasticsearch-learning-to-rank plugin for ES 8.0

### ISSUE THREAD

**Issue by lasagar** [o19s/elasticsearch-learning-to-rank#419]
Looking to explore the new version

**Comment by coolsuntraveler** [comment]
Hello @nathancday, any plan to release recently?

**Comment by Sutty100** [comment]
Hey, is there any update on this?

**Comment by laxmimerit** [comment]
Hey, do we have plugin for ES8.x?

**Comment by nathancday** [comment]
Please don't cross post in issues :) 

I shouldn't have closed this as completed in February. Progress is in the open PR: https://github.com/o19s/elasticsearch-learning-to-rank/pull/428

**Comment by laxmimerit** [comment]
Any update on this?

**Comment by worleydl** [comment]
The upstream fix is targeted for ES 8.5.  We will create a new release of the plugin when it becomes available.

**Comment by worleydl** [comment]
Fixed in https://github.com/o19s/elasticsearch-learning-to-rank/pull/443
