### ISSUE TITLE
Update elasticsearch to 7.17.5

### ISSUE THREAD

**Issue by mifune-cedrowo** [o19s/elasticsearch-learning-to-rank#433]
https://www.elastic.co/guide/en/elasticsearch/reference/7.17/release-notes-7.17.5.html

**Comment by nathancday** [comment]
Thanks for flagging this.

Would you want to make a PR and bump the versions and open a PR? Something like this old PR: https://github.com/o19s/elasticsearch-learning-to-rank/pull/427 should just be a little change and good to go?

**Comment by mifune-cedrowo** [comment]
@nathancday Thanks for reply. I opened Issue as it was suggested in [installing section](https://elasticsearch-learning-to-rank.readthedocs.io/en/latest/).
Opened [#434](https://github.com/o19s/elasticsearch-learning-to-rank/pull/434)

**Comment by nathancday** [comment]
https://github.com/o19s/elasticsearch-learning-to-rank/releases/tag/v1.5.8-es7.17.5 Thanks again!
