### ISSUE TITLE
elasticsearch-learning-to-rank plugin for ES 8.x

### ISSUE THREAD

**Issue by laxmimerit** [o19s/elasticsearch-learning-to-rank#435]
Hi,
Is there any ETA for plugin which supports latest version of ES?

**Comment by nathancday** [comment]
Please see the open PR: https://github.com/o19s/elasticsearch-learning-to-rank/pull/428

**Comment by nathancday** [comment]
Link issue #419

**Comment by worleydl** [comment]
There was some changes upstream which broke compatibility until ES 8.5, fixed in: https://github.com/o19s/elasticsearch-learning-to-rank/pull/443
