### ISSUE TITLE
ES 6.8.23 -> LTR Build Request 

### ISSUE THREAD

**Issue by siddhu208** [o19s/elasticsearch-learning-to-rank#436]
Hi, do you mind publishing a build for Elasticsearch Version 6.8.23 (latest 6.x).

Thanks,
Sai.

**Comment by nathancday** [comment]
could you contribute a PR? would love to merge it for LTS 6 support

The last commit:  https://github.com/o19s/elasticsearch-learning-to-rank/commit/3bfa05013ffaf17a737d9c2b0819f880d8fafa45
on the `es_6_8` branch: https://github.com/o19s/elasticsearch-learning-to-rank/tree/es_6_8
should show you the lines you may have to update.

**Comment by siddhu208** [comment]
There is already a merged PR for it at https://github.com/o19s/elasticsearch-learning-to-rank/pull/413 and I do see a tag for 6.8.23 - https://github.com/o19s/elasticsearch-learning-to-rank/tree/v1.1.1-es6.8.23
No builds though. Also, some test cases are failing while I tried to build it. Could you help take a look please.
Thanks.

**Comment by nathancday** [comment]
sorry I misunderstood your ask. Will look but not promising I can figure out a build, going way back in the build machine is tricky.

**Comment by nathancday** [comment]
@worleydl not sure if you have any tricks up your sleeve for this thing

**Comment by worleydl** [comment]
This is a little tricky since it's before we built out workflows for publishing releases.  In lieu of an official release here's a build you can snag:
[ltr-1.1.1-es6.8.23.zip](https://github.com/o19s/elasticsearch-learning-to-rank/files/9409153/ltr-1.1.1-es6.8.23.zip)

**Comment by siddhu208** [comment]
Thank you @worleydl

**Comment by siddhu208** [comment]
@worleydl when I try to install this plugin in elasticsearch 6.8.23, I get the following - any suggestions please? 

ERROR: This plugin was built with an older plugin structure. Contact the plugin author to remove the intermediate "elasticsearch" directory within the plugin zip.

I very much appreciate it. Thanks.

**Comment by worleydl** [comment]
I tested in Docker with success, here's the associated Dockerfile:
```
FROM docker.elastic.co/elasticsearch/elasticsearch:6.8.23

 RUN bin/elasticsearch-plugin install --batch \
   "https://github.com/o19s/elasticsearch-learning-to-rank/files/9409153/ltr-1.1.1-es6.8.23.zip"
```

Please doublecheck your ES version and plugin zip.  It's an odd message as the zip doesn't include an intermediate elasticsearch folder.  If you're still seeing issues after confirming versions please send me the commands you're running and I'll try to reproduce.

**Comment by siddhu208** [comment]
It works, thank you. Sorry for raising the alarm, I accidentally used a different version of the plugin. I will close the issue now. Thanks.
