### ISSUE TITLE
Cannot Install Plugin 

### ISSUE THREAD

**Issue by soumilshah1995** [o19s/elasticsearch-learning-to-rank#440]
While installing plugin Getting Error 

Exception in thread "main" java.lang.IllegalArgumentException: Plugin [ltr] was built for Elasticsearch version 7.11.2 but version 7.17.5 is running

**Comment by worleydl** [comment]
Hello @soumilshah1995,

The plugin version must match your ES version.  Please use the version built for ES 7.17.5: https://github.com/o19s/elasticsearch-learning-to-rank/releases/tag/v1.5.8-es7.17.5

**Comment by nathancday** [comment]
dang beat me to it:
![image](https://user-images.githubusercontent.com/808225/198088758-d8566bde-51e9-487d-9b66-21257889ce4e.png)
