### ISSUE TITLE
Wrong plugin version showing at _cat/plugins

### ISSUE THREAD

**Issue by Fillipedem** [o19s/elasticsearch-learning-to-rank#492]
Hello everyone,

I am currently migrating an Elasticsearch instance to the new 8.14.1 version and testing the [1.5.9](https://github.com/o19s/elasticsearch-learning-to-rank/releases/tag/v1.5.9-es8.14.1) plugin release for this version. However, I've encountered an inconsistency.

When I run `GET _cat/plugins` it returns: `181e5621ef1d ltr 1.5.8-es8.14.1`. This suggests that the plugin version is 1.5.8, not 1.5.9 as expected.

Futhermore, the `gradle.properties` file also shows that the ltr plugin version is 1.5.8:

```
ltrVersion = 1.5.8
elasticsearchVersion = 8.14.1
luceneVersion = 9.10.0
ow2Version = 8.0.1
antlrVersion = 4.5.1-1
```

From what I can tell, it appears that the ltrVersion may not have been updated when the release was changed to 1.5.9.

Thanks!

**Comment by Philippus** [comment]
I think this was fixed in https://github.com/o19s/elasticsearch-learning-to-rank/pull/495.

**Comment by wrigleyDan** [comment]
Thanks for spotting and reporting that one.
As @Philippus pointed out: we addressed that inconsistency in https://github.com/o19s/elasticsearch-learning-to-rank/pull/495 with the latest plugin release supporting 8.14.2.
