### ISSUE TITLE
version in build.gradle in 1_0 branch is behind version in master

### ISSUE THREAD

**Issue by robbymeals** [o19s/elasticsearch-learning-to-rank#58]
@nomoa We're trying to get 1.0 up and running over here and I noticed that the version number in the build spec is behind the version in master.

Should we update to `1.0.0-es5.3.0-SNAPSHOT` or something similar to avoid confusion?

**Comment by nomoa** [comment]
@robbymeals sure I'll change this soon, hopefully today

**Comment by nomoa** [comment]
1_0 should be up to date with master and compatible es 5.5.0.
I've setup 1_0-es5.3 to maintain a backport branch on top of es 5.3.2 (version currently deployed on wmf infra)

(closing manually as gh does not want to do this automatically)
