### ISSUE TITLE
Build failed with gradle

### ISSUE THREAD

**Issue by BeifeiZhou** [o19s/elasticsearch-learning-to-rank#6]
Hi guys, I can not build the project with gradle, and it gives this error:

FAILURE: Build failed with an exception.

    Where:
    Build file '/file/elasticsearchLtrPlugin/elasticsearch-learning-to-rank/build.gradle' line: 18

    What went wrong:
    A problem occurred evaluating root project 'ltr-query'.

    Failed to apply plugin [id 'carrotsearch.randomized-testing']
    Could not create task of type 'RandomizedTestingTask'.

    Try:
    Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Do you have any suggestions?

Many thanks,
Beifei

**Comment by BeifeiZhou** [comment]
Sorry to raise the issue, and in the end I found that it needs Gradle-2.13 instead of any other versions. I will leave this issue here just for people who have the same issue as me.

**Comment by softwaredoug** [comment]
@BeifeiZhou thanks. There is a quirk with Gradle and Elasticsearch where 2.13 is required. I use [dotenv](https://www.npmjs.com/package/dotenv) and point GRADLE_HOME to a 2.13 in my home directory. Specifically I use a .envrc

```
export PATH=/home/doug/bin/gradle-2.13/bin:/usr/lib/jvm/java-8-openjdk-amd64/jre/bin/:$PATH
# Gradle 2.13 required by Elasticsearch
export GRADLE_HOME=/home/doug/bin/gradle-2.13
export JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64
```
