### ISSUE TITLE
Update demo for v1.0

### ISSUE THREAD

**Issue by softwaredoug** [o19s/elasticsearch-learning-to-rank#60]
The demo scripts need to be updated for 1.0 and tested

**Comment by epugh** [comment]
Branch off of 1.0, and submit PR's to that branch has been the pattern.

- [ ]  build plugin for latest version of Elasticsearch.   
- [ ]  install plugin via ./bin/elasticsearch-plugin using file:///
- [ ]  need to update the features.py to work with the new 1.0 feature logging enhancement
- [ ]  validate that training.py continues to work properly.
- [ ]  update search.py to use the new query form.

**Comment by softwaredoug** [comment]
Done in #78 when it's merged

**Comment by softwaredoug** [comment]
Merged in #78
