### ISSUE TITLE
Release candidate 1.0 for ES 5.5.x

### ISSUE THREAD

**Issue by softwaredoug** [o19s/elasticsearch-learning-to-rank#61]
Build Elasticsearch 1.0 for ES 5.5.x as a release candidate

**Comment by epugh** [comment]
- [ ] update Readme, update Java code, document different types of rankers
- [ ] write blog post announcing update
- [ ] triage tickets assigned to 1.0
- [ ] Create 1.1 branch
- [ ] publish plugin

**Comment by softwaredoug** [comment]
Release Candidate out as in #95 ... Master is now 1.0, Branch 0_1_2 points at previous version for maintenance.
