### ISSUE TITLE
Document v1.0 features

### ISSUE THREAD

**Issue by softwaredoug** [o19s/elasticsearch-learning-to-rank#62]
Update README and any other documentation to reflect v1.0 features. What other documentation do we need?

**Comment by nomoa** [comment]
I don't know if we should consider this a blocker but we recently found that the plugin may hit a circuit breaker in elastic, see https://phabricator.wikimedia.org/T171579 for more context.
The easy fix we plan to apply for now is setting `script.max_compilations_per_minute` to a large value (10000 for us).
I don't know if I'll have time to fix this properly before we release 1.0

**Comment by nomoa** [comment]
Just a note to say that the `script.max_compilations_per_minute` is no longer needed.
