### ISSUE TITLE
Minor HTTP status code nitpicks in 1.0

### ISSUE THREAD

**Issue by softwaredoug** [o19s/elasticsearch-learning-to-rank#67]
I noted when rebuilding the demo that

- Trying to GET a missing feature store (to check if it exists) returns a 400, not a 404
- PUT'ing a new feature store should return 201, instead it returns 200

**Comment by nomoa** [comment]
> PUT'ing a new feature store should return 201, instead it returns 200
Actually it returns a 400 with index_already_exists_exception same as the PUT /_existing_index
It's probable that this got created while you were still fighting with #80 ?

**Comment by softwaredoug** [comment]
FIxed in #92
