### ISSUE TITLE
The query example does not work

### ISSUE THREAD

**Issue by BeifeiZhou** [o19s/elasticsearch-learning-to-rank#7]
Hi, 

I have used this query example, however, it did not work.  
```
{
    "query": {...}
    "rescore": {
        "query": {
            "ltr": {
                "model": {
                    "stored": "dummy"
                },
                "features": [{
                    "match": {
                        "title": userSearchString
                    }
                },{
                    "constant_score": {
                        "query": {
                            "match_phrase": {
                                "title": "userSearchString"
                            }
                        }
                    }
                }]
            }
        }
    }
}
```

It seems that the query is wrong, and a "," seems to be missing after "query":{...}. After I added ",", and run the query, it gives such error:

{
  "error": {
    "root_cause": [
      {
        "type": "illegal_argument_exception",
        "reason": "[query] unknown field [ltr], parser not found"
      }
    ],
    "type": "illegal_argument_exception",
    "reason": "[query] unknown field [ltr], parser not found"
  },
  "status": 400
}

I have checked the source code, in this class "LtrQueryBuilder", it does not mention "rescore", does it mean that "rescore" is not implemented?

I am looking forward to your reply. 
Thanks,
Beifei

**Comment by softwaredoug** [comment]
Thanks, I will try this out tonight

**Comment by softwaredoug** [comment]
Does it work to just run 'ltr' by itself? Does it only fail in a rescore context?

**Comment by softwaredoug** [comment]
Could you confirm the plugin is installed via `GET _cat/plugins`?

**Comment by softwaredoug** [comment]
Hey @BeifeiZhou that ... is expecting you to place your own initial query such as `{"match": {"_all": "<your query here>"}}"

**Comment by BeifeiZhou** [comment]
Hi @softwaredoug 

Thanks a lot for answering my questions. In the end, I have figured out that by using this query it is working:

GET shakespeare/_search
{
   "query": {
     "query_string": {
       "query": "story"
     }
   },
   "rescore": {
     "window_size" : 50,
      "query": {
        "rescore_query": {
          "ltr": {
            "model": {
              "stored": "dummy"
            }
          }          
        }
      }
   }
}

I think the example provided from your documentation missed "rescore_query".

However, I have another question here. "ltr" can pass a trained model, but how does it pass doc features to re-calculate score for each doc, so that the top-K docs can be reranked? 

Thanks,
Beifei

**Comment by softwaredoug** [comment]
Hi @BeifeiZhou this blog article might help clarify things, it details our full example:

http://opensourceconnections.com/blog/2017/02/14/elasticsearch-learning-to-rank/

**Comment by BeifeiZhou** [comment]
@softwaredoug Thanks for the link. 
However, the features in the examples are not generic enough for LTR. Is it possible to add one functionality which allows to upload features for each doc from external resources(files, databases, etc)?

**Comment by softwaredoug** [comment]
> However, the features in the examples are not generic enough for LTR. Is it possible to add one functionality which allows to upload features for each doc from external resources(files, databases, etc)?

Yes we certainly could use more documentation. It sounds like what you want is document-only (not query-dependent features). For example, popularity or some other factor. I would recommend adding those values as fields on the documents and using a [Function Score Query](https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-function-score-query.html), specifically [field_value_factor](https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-function-score-query.html#function-field-value-factor) to retrieve their values directly to be used as features in ranking.
