### ISSUE TITLE
Random test failures

### ISSUE THREAD

**Issue by nomoa** [o19s/elasticsearch-learning-to-rank#75]
`com.o19s.es.ltr.feature.store.index.CachedFeatureStoreTests.testExpirationOnGet` is failing randomly and probably others that rely on system clock.
We need to find a way to make it run nicely or disable it to avoid annoyance.

**Comment by softwaredoug** [comment]
Leaving this open to fix the tests, but for 1.1 to see if it's fixable

**Comment by softwaredoug** [comment]
@nomoa is this still an issue?

**Comment by nomoa** [comment]
@softwaredoug I may not have enough time to properly investigate, I'll close this ticket since it's basically testing the elastic cache which is not owned by this plugin.
I'll try to find time to cleanup the test code.
