### ISSUE TITLE
Create build for ES 2.4

### ISSUE THREAD

**Issue by gibrown** [o19s/elasticsearch-learning-to-rank#8]
There are a number of barriers to getting ES 5.x deployed (for us it is partly that we are still working to get off of 1.x and supporting three major versions in production would require even more hacks). If it's possible to get a 2.x version of this plugin that would make it a lot easier to experiment with existing indices and should increase the user base of people contributing.

**Comment by gibrown** [comment]
Don't really have a PR yet, but in case anyone is also trying to get this to work, we seem to be able to build it with the following build.gradle. Unfortunately lots of other compilation errors...

```
buildscript {
  repositories {
    mavenCentral()
    jcenter()
    mavenLocal()
  }
 
}
 
group = 'com.o19s'
version = '0.0.5-es2.4.3'
 
apply plugin: 'java'
apply plugin: 'idea'
 
task buildPluginZip(type: Zip, dependsOn:[':jar']) {
    baseName = 'ltr-query'
    classifier = 'plugin'
    from files(libsDir) // include output dirictory into archive
}
 
// In this section you declare the dependencies for your production and test code
// Note, the two dependencies are not really needed as the buildscript dependency gets them in already
// they are just here as an example
repositories {
    mavenCentral()
    mavenLocal()
}
dependencies {
  compile 'org.elasticsearch:elasticsearch:2.4.3'
  compile 'com.o19s:RankLibPlus:0.1'
  testCompile 'org.elasticsearch.test:framework:2.4.3'
}
```

**Comment by singhsimranjot** [comment]
Thanks!

**Comment by singhsimranjot** [comment]
Thanks! Updates? :)

**Comment by epugh** [comment]
@gibrown I'm working towards getting the 1_0 branch of the plugin released.   Have you looked at it for ES 2.4?   Is this still a live issue?   I was planning on releasing only for Elasticsearch 5.x.

**Comment by gibrown** [comment]
Beyond the above we haven't been able to work on it unfortunately. Not having 2.x support is still an issue for us. Will probably be a while (a year?) before we are off of 2.x.

**Comment by epugh** [comment]
I think this is going to be one of those “contributions welcome” things.   The folks using this is production are all on a 5.x line, and the 1.0 release will target a 5.0 release.

If we don’t think a contribution is going to be forthcoming, then I think we should close it as a “Won’t fix” type of thing.

**Comment by gibrown** [comment]
We may still get to it, but some other priorities are currently in blocking us. If you'd prefer to close it to clear out your backlog and indicate that you aren't planning to fix it that's fine with me. We can reopen it if we start working on it. Thanks

**Comment by epugh** [comment]
Thanks!   THough fingers crossed you do pick it back up, or get to 5.x sooner!
