### ISSUE TITLE
Add full example for simple testing

### ISSUE THREAD

**Issue by gibrown** [o19s/elasticsearch-learning-to-rank#9]
It would be good to have a working example data set and set of click data to have a simple smoke test for devs to run.

I think what is needed is:
- A set of index data. Settings, mappings, and json docs
- Scripts to load the data. Here's some bash scripts I've used for stuff like this: https://gist.github.com/gibrown/b039039666e387ed6b0dcefb45203420
- Click data for building the ranklib file (or just a ranklib file)
- A test query

This is also mentioned in the current README, just figured opening an issue would help.

**Comment by softwaredoug** [comment]
Thanks @gibrown. Not click data, but hand-rolled movie example can be found in the scripts folder. Perhaps another repo would be more appropriate for a more click-traffic based example?

**Comment by gibrown** [comment]
Oh, I see it now. So that uses the movie data set. Thanks for clarifying, sounds like I should just try that example to verify how stuff works on 2.4...

Is "Create a full example" then to just add documentation for how to run it to the Readme?

**Comment by softwaredoug** [comment]
Thanks, I think I just forgot to delete that line in the README

**Comment by gibrown** [comment]
OK, closing this out. Will reopen if I find problems. Thanks.
