### ISSUE TITLE
403 Error to download RC1 for ES5.5.2

### ISSUE THREAD

**Issue by fmbesson** [o19s/elasticsearch-learning-to-rank#96]
Hi, could you please check the access permission to download:
http://es-learn-to-rank.labs.o19s.com/ltr-query-1.0.0-RC1-es5.5.2.zip

thank you

**Comment by epugh** [comment]
@fmbesson thanks for the sharp eyes.   I just fixed the permissions on the file in s3....   Can you confirm it works?

**Comment by softwaredoug** [comment]
I uploaded but did not set the right permissions. Fixing now.

**Comment by softwaredoug** [comment]
The new plugin is called "ltr" so I corrected that. Can you confirm you can download 5.5.2 from here: http://es-learn-to-rank.labs.o19s.com/

**Comment by fmbesson** [comment]
It is working :)
Thank you @softwaredoug and @epugh
