### ISSUE TITLE
can I use feature which not in es?

### ISSUE THREAD

**Issue by comdotwang162** [o19s/elasticsearch-learning-to-rank#98]

**Comment by nomoa** [comment]
The plugin only allows you to use features provided by elasticsearch or other plugins, so if the question is can the plugin provide a way to access features that are declared outside the index you're trying to rank results for the answer is no.
But assuming that you have a plugin that exposes a query or a function score that allows you to access external resources (e.g. a key value store) then it's perfectly fine to use that query in a model managed by the ltr plugin.

I'd be curious to know more about your setup and the kind of features you'd like to use inside the ltr plugin, thanks.

**Comment by comdotwang162** [comment]
Thanks for your response. I'd like to use the features of User portrait in ltr. so users can get different retrieval results.

**Comment by nomoa** [comment]
In that case it's certainly possible to pass the user data as a param to the ltr query. How it looks like highly depends on the data you want pass and moreover if this data needs to be joined with the data in the index.
But note that adding more parameters may increase the sparsity of queries making it hard to group them to have enough labels per query to generate your training data.
In short you can do that with the plugin if the user data is fetched from client prior to sending the query to elasticsearch.
See https://github.com/o19s/elasticsearch-learning-to-rank/blob/master/docs/building-features.rst#what-is-a-feature-in-elasticsearch-ltr on how to build features, one example describes how to use user location as a feature in the model, the user data in this example is passed thanks to a ltr query param.

**Comment by softwaredoug** [comment]
Did this help @comdotwang162 ? 

You should be able to construct a `function_score` query that can use data sent either externally with the query or in the document.
