### ISSUE TITLE
ltr-query-0.1.2-es5.5.2.zip and ltr-query-0.1.2-es5.5.1.zip downloads fail

### ISSUE THREAD

**Issue by doombongo** [o19s/elasticsearch-learning-to-rank#99]
The prebuilt versions page is throwing a 403 when attempting download these versions from http://es-learn-to-rank.labs.o19s.com/:
ltr-query-0.1.2-es5.5.1.zip
ltr-query-0.1.2-es5.5.2.zip

Are these plugin versions no longer available?

**Comment by o19s-admin** [comment]
Argh.  We need to automate the build/publish cycle, because we keep forgetting to put World Readable on the files when deployed in the S3 bucket.    Please try now.

**Comment by doombongo** [comment]
It works! Thank you very much @o19s-admin
